Cimi Production KW/src/objects/Client_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Client Summary</label>
    <nameField>
        <displayFormat>summary-{000000}</displayFormat>
        <label>Client Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Cimi Production KW/src/objects/DS_DATA__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Section</label>
        <type>Checkbox</type>
    </fields>
    <label>DS DATA</label>
    <nameField>
        <displayFormat>DS DATA - {000000}</displayFormat>
        <label>DS DATA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS DATA</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Cimi Production KW/src/objects/DS_TSCC_TSCYC_B__c.object
<CustomObject>
    <fields>
        <fullName>BANG_R2__c</fullName>
        <description>Anger Scale Raw Score
9-36</description>
        <label>BANG_R2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BANG_R__c</fullName>
        <description>Anger Scale Raw Score
9-36</description>
        <label>BANG_R</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BANG_T2__c</fullName>
        <description>Anger Scale T Score
30-140</description>
        <label>BANG_T2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BANG_T__c</fullName>
        <description>Anger Scale T Score
30-140</description>
        <label>BANG_T</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BANX_R2__c</fullName>
        <description>Anxiety Scale Raw Score
9-36</description>
        <label>BANX_R2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BANX_R__c</fullName>
        <description>Anxiety Scale Raw Score
9-36</description>
        <label>BANX_R</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BANX_T2__c</fullName>
        <description>Anxiety Scale T Score
30-140</description>
        <label>BANX_T2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BANX_T__c</fullName>
        <description>Anxiety Scale T Score
30-140</description>
        <label>BANX_T</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BATR_R2__c</fullName>
        <description>Hyperresponsive Scale Raw Score
9-36</description>
        <label>BATR_R2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BATR_R__c</fullName>
        <description>Hyperresponsive Scale Raw Score
9-36</description>
        <label>BATR_R</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BATR_T2__c</fullName>
        <description>Hyperresponsive Scale T Score
30-140</description>
        <label>BATR_T2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BATR_T__c</fullName>
        <description>Hyperresponsive Scale T Score
30-140</description>
        <label>BATR_T</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BDEP_R2__c</fullName>
        <description>Depression Scale Raw Score
9-36</description>
        <label>BDEP_R2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BDEP_R__c</fullName>
        <description>Depression Scale Raw Score
9-36</description>
        <label>BDEP_R</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BDEP_T2__c</fullName>
        <description>Depression Scale T Score
30-140</description>
        <label>BDEP_T2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BDEP_T__c</fullName>
        <description>Depression Scale T Score
30-140</description>
        <label>BDEP_T</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BDIS_R2__c</fullName>
        <description>Dissociation Scale Raw Score
9-36</description>
        <label>BDIS_R2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BDIS_R__c</fullName>
        <description>Dissociation Scale Raw Score
9-36</description>
        <label>BDIS_R</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BDIS_T2__c</fullName>
        <description>Dissociation Scale T Score
30-140</description>
        <label>BDIS_T2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BDIS_T__c</fullName>
        <description>Dissociation Scale T Score
30-140</description>
        <label>BDIS_T</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BDOATSCC__c</fullName>
        <description>Briere/TSCC date of administration</description>
        <label>BDOATSCC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BDOATSCYC__c</fullName>
        <description>TSCYC date of administration</description>
        <label>BDOATSCYC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BPTSAR_R2__c</fullName>
        <description>PTS Arousal Subscale Raw Score
9-36</description>
        <label>BPTSAR_R2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSAR_R__c</fullName>
        <description>PTS Arousal Subscale Raw Score
9-36</description>
        <label>BPTSAR_R</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSAR_T2__c</fullName>
        <description>PTS Arousal Subscale T Score
30-140</description>
        <label>BPTSAR_T2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSAR_T__c</fullName>
        <description>PTS Arousal Subscale T Score
30-140</description>
        <label>BPTSAR_T</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSAV_R2__c</fullName>
        <description>PTS Avoidance Subscale Raw Score
9-36</description>
        <label>BPTSAV_R2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSAV_R__c</fullName>
        <description>PTS Avoidance Subscale Raw Score
9-36</description>
        <label>BPTSAV_R</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSAV_T2__c</fullName>
        <description>PTS Avoidance Subscale T Score
30-140</description>
        <label>BPTSAV_T2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSAV_T__c</fullName>
        <description>PTS Avoidance Subscale T Score
30-140</description>
        <label>BPTSAV_T</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSI_R2__c</fullName>
        <description>PTS Intrusion Subscale Raw Score
9-36</description>
        <label>BPTSI_R2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSI_R__c</fullName>
        <description>PTS Intrusion Subscale Raw Score
9-36</description>
        <label>BPTSI_R</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSI_T2__c</fullName>
        <description>PTS Intrusion Subscale T Score
30-140</description>
        <label>BPTSI_T2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSI_T__c</fullName>
        <description>PTS Intrusion Subscale T Score
30-140</description>
        <label>BPTSI_T</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSTOT_R2__c</fullName>
        <description>PTS Total Scale Raw Score 27-108</description>
        <label>BPTSTOT_R2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSTOT_R__c</fullName>
        <description>PTS Total Scale Raw Score 27-108</description>
        <label>BPTSTOT_R</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSTOT_T2__c</fullName>
        <description>PTS Total Scale T Score 30-140</description>
        <label>BPTSTOT_T2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BPTSTOT_T__c</fullName>
        <description>PTS Total Scale T Score 30-140</description>
        <label>BPTSTOT_T</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BRL_R2__c</fullName>
        <description>Underresponsive Scale Raw Score
0-9</description>
        <label>BRL_R2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BRL_R__c</fullName>
        <description>Underresponsive Scale Raw Score
0-9</description>
        <label>BRL_R</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BRL_T2__c</fullName>
        <description>Underresponsive Scale T Score
30-140</description>
        <label>BRL_T2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BRL_T__c</fullName>
        <description>Underresponsive Scale T Score
30-140</description>
        <label>BRL_T</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSC_R2__c</fullName>
        <description>Sexual Concerns Scale Raw Score
9-36</description>
        <label>BSC_R2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSC_R__c</fullName>
        <description>Sexual Concerns Scale Raw Score
9-36</description>
        <label>BSC_R</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSC_T2__c</fullName>
        <description>Sexual Concerns Scale T Score
30-140</description>
        <label>BSC_T2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSC_T__c</fullName>
        <description>Sexual Concerns Scale T Score
30-140</description>
        <label>BSC_T</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BTSCAXN2__c</fullName>
        <description>Briere: Anxiety - Num
Raw: 0-27</description>
        <label>BTSCAXN2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BTSCAXN__c</fullName>
        <description>Briere: Anxiety - Num
Raw: 0-27</description>
        <label>BTSCAXN</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BTSCAXTN2__c</fullName>
        <description>Briere: Anxiety T Score- Num
30-140</description>
        <label>BTSCAXTN2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BTSCAXTN__c</fullName>
        <description>Briere: Anxiety T Score- Num
30-140</description>
        <label>BTSCAXTN</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BTSCDPN2__c</fullName>
        <description>Briere: Depression - Num
Raw: 0-27</description>
        <label>BTSCDPN2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BTSCDPN__c</fullName>
        <description>Briere: Depression - Num
Raw: 0-27</description>
        <label>BTSCDPN</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS TSCC TSCYC B</relationshipLabel>
        <relationshipName>DS_TSCC_TSCYC_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>DS TSCC TSCYC B</label>
    <nameField>
        <label>DS TSCC TSCYC B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS TSCC TSCYC B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Cimi Production KW/src/classes/TestClass_DS_TSCC_TSCYC_B.cls
/****
*@description This test provides code coverage for DS_TSCC_TSCYC_B
*includes
*Trigger 
*Controllers:
    *TSCC_A, TSCC_A_Report, TSCYC, TSCYC_Report
*Bulkified testing
*Asserted Variables
*
*@author Kelsey Willett
*@date 1/27/2016
*@modified date
*Tscc/YC coverage
*
*@date 2/8/16
*@modified date
*Purpose: TSCC/YC assert
*
*@date 3/2/16
*@modified date
*@author KW
*Purpose: update bulk insert,asserts
*
*@modified    4/19/17    KW    test.starttest() & test.stoptest()
*
*@group Test Script 
*@group-content /ApexDocContent/Test/DS_TSCC_TSCYC_B.htm
****/

@isTest (SeeAllData=false)
private class TestClass_DS_TSCC_TSCYC_B {

    /****
    *@description Initialize reference to TestClass_A_Utility
    ****/
    public static TestClass_A_Utility test_ut = new TestClass_A_Utility();
    
    /****
    *@description Initialize reference to Utility
    ****/
    public static Utility ut = new Utility();
    
    /****
    *@description Load required data from TestClassData
    ****/
    @testSetup 
    static void setup() {
        TestClassData_DS_DATA importData = new TestClassData_DS_DATA();   
        importData.variable();       
    }
    
    /****
    *@description method to test a bulk creation of object
    ****/
    static TestMethod void bulkifyObj(){
    
        //init client
        Client__c client = test_ut.createClient();
        
        //init list of object
        List<DS_TSCC_TSCYC_B__c> bulkObj = new List<DS_TSCC_TSCYC_B__c>();
        
        ///begin bulk insert     
        for (Integer i=0;i<200;i++){          
            bulkObj.add(new DS_TSCC_TSCYC_B__c(client__c = client.id,                                                           //client
                                                SECTION__c = '0',                                                               //section
                                                BDOATSCYC__c = System.today(), BDOATSCC__c = System.today(),                    //dates                                             
                                                BPTSTOT_R__c= 30,  BPTSTOT_R2__c = 30,  BPTSTOT_T__c= 71, BPTSTOT_T2__c= 71,    //YC tot
                                                BANX_R__c   = 10,  BANX_R2__c    = 10,  BANX_T__c   = 71, BANX_T2__c   = 71,    //YC anx
                                                BDEP_R__c   = 10,  BDEP_R2__c    = 10,  BDEP_T__c   = 71, BDEP_T2__c   = 71,    //YC dep
                                                BANG_R__c   = 10,  BANG_R2__c    = 10,  BANG_T__c   = 71, BANG_T2__c   = 71,    //YC ang
                                                BSC_R__c    = 10,  BSC_R2__c     = 10,  BSC_T__c    = 71, BSC_T2__c    = 71,    //YC sc
                                                BDIS_R__c   = 10,  BDIS_R2__c    = 10,  BDIS_T__c   = 71, BDIS_T2__c   = 71,    //YC dis
                                                BPTSI_R__c  = 10,  BPTSI_R2__c   = 10,  BPTSI_T__c  = 71, BPTSI_T2__c  = 71,    //YC pts i 
                                                BPTSAV_R__c = 10,  BPTSAV_R2__c  = 10,  BPTSAV_T__c = 71, BPTSAV_T2__c = 71,    //YC pts av
                                                BPTSAR_R__c = 10,  BPTSAR_R2__c  = 10,  BPTSAR_T__c = 71, BPTSAR_T2__c = 71,    //YC pts ar
                                                BRL_R__c    = 2,   BRL_R2__c     = 2,   BRL_T__c    = 71, BRL_T2__c    = 71,    //YC rl
                                                BATR_R__c   = 10,  BATR_R2__c    = 10,  BATR_T__c   = 71, BATR_T2__c   = 71,    //YC atr
                                                
                                                BTSCAXN__c  = 15,  BTSCAXN2__c   = 15,  BTSCAXTN__c = 67, BTSCAXTN2__c = 67,    //A anx
                                                BTSCDPN__c  = 15,  BTSCDPN2__c   = 15,  BTSCDPTN__c = 67, BTSCDPTN2__c = 67,    //A dep
                                                BTSCAGG__c  = 15,  BTSCAGG2__c   = 15,  BTSCAGTN__c = 67, BTSCAGTN2__c = 67,    //A ang
                                                BTSCPTN__c  = 15,  BTSCPTN2__c   = 15,  BTSCPTTN__c = 67, BTSCPTTN2__c = 67,    //A pts
                                                BTSCDSN__c  = 15,  BTSCDSN2__c   = 15,  BTSCDSTN__c = 67, BTSCDSTN2__c = 67,    //A dis
                                                BTSCODN__c  = 15,  BTSCODN2__c   = 15,  BTSCODTN__c = 67, BTSCODTN2__c = 67,    //A dis o
                                                BTSCFNN__c  = 2,   BTSCFNN2__c   =  2,  BTSCFNTN__c = 67, BTSCFNTN2__c = 67,    //A dis f
                                                BTSCUNN__c  = 8,   BTSCUNN2__c   =  8,  BTSCNTN__c  = 71, BTSCNTN2__c  = 71,    //A und
                                                BTSCHYN__c  = 4,   BTSCHYN2__c   =  4,  BTSCHYTN__c = 91, BTSCHYTN2__c = 91     //A hyp
                                                ));         
        }
        
        //add list of records to object
        insert bulkObj;  
    }
    
    /****
    *@description method to test controllers associated with object
    *TSCYC 
    ****/
    static TestMethod void assertControllerTSCYC() {    
    
        //create test client 
        Client__c client = test_ut.createClient();     
        
        DS_DATA__c dataPage = [SELECT id FROM DS_DATA__c 
                                WHERE Page__c = 'DS_TSCYC'
                                AND File_name__c = 'BASELINE'
                                AND Category__c = 'Assessment'];
        
        String dpID = String.valueOf(dataPage.id);                      
        
        Client_Summary__c summary = new Client_Summary__c(Client__c = client.id,
                                                            SECTION__c = '0',
                                                            Page__c = dpID,
                                                            FORM_TYPE__c = 'Baseline',
                                                            STATUS__c = 'Complete');
        
        insert summary;  
        
        // Get summaryId for Url
        String summaryId = test_ut.getClientSummaryId(client.id, 'DS_TSCYC', '0');
        
        //encoded parameters        
        String cimi= ut.urlEncode('c='+client.id+'&summary='+summaryId);
        ApexPages.currentPage().getParameters().put('cimi',cimi);   
        
        //init list of object
        List<DS_TSCC_TSCYC_B__c> ObjList = new List<DS_TSCC_TSCYC_B__c>();
        
        //init object w/ required vals
        DS_TSCC_TSCYC_B__c obj = new DS_TSCC_TSCYC_B__c(client__c = client.id,                                                              //client
                                                        SECTION__c = '0',                                                               //section
                                                        BDOATSCYC__c = System.today(),                                                  //date                                              
                                                        BPTSTOT_R__c= 70,  BPTSTOT_R2__c = 70,  BPTSTOT_T__c= 67, BPTSTOT_T2__c= 67,    //YC tot
                                                        BANX_R__c   = 30,  BANX_R2__c    = 30,  BANX_T__c   = 67, BANX_T2__c   = 67,    //YC anx
                                                        BDEP_R__c   = 30,  BDEP_R2__c    = 30,  BDEP_T__c   = 67, BDEP_T2__c   = 67,    //YC dep
                                                        BANG_R__c   = 30,  BANG_R2__c    = 30,  BANG_T__c   = 67, BANG_T2__c   = 67,    //YC ang
                                                        BSC_R__c    = 30,  BSC_R2__c     = 30,  BSC_T__c    = 67, BSC_T2__c    = 67,    //YC sc
                                                        BDIS_R__c   = 30,  BDIS_R2__c    = 30,  BDIS_T__c   = 67, BDIS_T2__c   = 67,    //YC dis
                                                        BPTSI_R__c  = 30,  BPTSI_R2__c   = 30,  BPTSI_T__c  = 67, BPTSI_T2__c  = 67,    //YC pts i 
                                                        BPTSAV_R__c = 30,  BPTSAV_R2__c  = 30,  BPTSAV_T__c = 67, BPTSAV_T2__c = 67,    //YC pts av
                                                        BPTSAR_R__c = 30,  BPTSAR_R2__c  = 30,  BPTSAR_T__c = 67, BPTSAR_T2__c = 67,    //YC pts ar
                                                        BRL_R__c    = 6,   BRL_R2__c     = 6,   BRL_T__c    = 67, BRL_T2__c    = 67,    //YC rl
                                                        BATR_R__c   = 30,  BATR_R2__c    = 30,  BATR_T__c   = 67, BATR_T2__c   = 67     //YC atr
                                                        );  
                
        //set form's status 
        obj.STATUS_TSCYC__c = 'Complete';        
        
        test.startTest();  
        //insert object
        insert obj;
        test.stopTest();
                
        //add obj to obj list
        ObjList.add(obj);
        
        //init controller for pages
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);  
          
        //controllers
        DS_TSCYC_Controller controller = new DS_TSCYC_Controller(sc);    
        DS_TSCYC_Report_Controller RC = new DS_TSCYC_Report_Controller(sc);       
        
        //save/cancel
        controller.save();
        controller.cancel();
        controller.saveview();
        
        RC.init();
        RC.editRecord();
        
        DS_TSCC_TSCYC_B__c tsc = [SELECT BDEP_R__c, BPTSAV_T2__c, SECTION__c
                                    FROM DS_TSCC_TSCYC_B__c
                                    WHERE id =: obj.id];
        
        // assert statements 
        System.assertEquals(tsc.BDEP_R__c, 30,'Incorrect Depression raw score.');
        System.assertEquals(tsc.BPTSAV_T2__c, 67,'Incorrect Avoidance T-score double entry.');
        System.assertEquals(tsc.SECTION__c, '0','Section incorrect: baseline.');
        }
    
    /****
    *@description method to test controllers associated with object
    *TSCC 
    ****/
    static TestMethod void assertControllerTSCC() {   
    
        //create test client 
        Client__c client = test_ut.createClient();     
        
        DS_DATA__c dataPage = [SELECT id FROM DS_DATA__c 
                                WHERE Page__c = 'DS_TSCC_A'
                                AND File_name__c = 'BASELINE'
                                AND Category__c = 'Assessment'];
        
        String dpID = String.valueOf(dataPage.id);                      
        
        Client_Summary__c summary = new Client_Summary__c(Client__c = client.id,
                                                            SECTION__c = '0',
                                                            Page__c = dpID,
                                                            FORM_TYPE__c = 'Baseline',
                                                            STATUS__c = 'Complete');
        
        insert summary;  
        
        // Get summaryId for Url
        String summaryId = test_ut.getClientSummaryId(client.id, 'DS_TSCC_A', '0');
        
        //encoded parameters        
        String cimi= ut.urlEncode('c='+client.id+'&summary='+summaryId);
        ApexPages.currentPage().getParameters().put('cimi',cimi);   
        
        //init list of object
        List<DS_TSCC_TSCYC_B__c> ObjList = new List<DS_TSCC_TSCYC_B__c>(); 
        
        //init object w/ required vals
        DS_TSCC_TSCYC_B__c obj = new DS_TSCC_TSCYC_B__c(client__c = client.id,                                                          //client
                                                        SECTION__c = '0',                                                               //section     
                                                        BDOATSCC__c = System.today(),                                                   //date    
                                                        BTSCAXN__c  = 20,  BTSCAXN2__c   = 20,  BTSCAXTN__c = 62, BTSCAXTN2__c = 62,    //A anx
                                                        BTSCDPN__c  = 20,  BTSCDPN2__c   = 20,  BTSCDPTN__c = 62, BTSCDPTN2__c = 62,    //A dep
                                                        BTSCAGG__c  = 20,  BTSCAGG2__c   = 20,  BTSCAGTN__c = 62, BTSCAGTN2__c = 62,    //A ang
                                                        BTSCPTN__c  = 20,  BTSCPTN2__c   = 20,  BTSCPTTN__c = 62, BTSCPTTN2__c = 62,    //A pts
                                                        BTSCDSN__c  = 20,  BTSCDSN2__c   = 20,  BTSCDSTN__c = 62, BTSCDSTN2__c = 62,    //A dis
                                                        BTSCODN__c  = 20,  BTSCODN2__c   = 20,  BTSCODTN__c = 62, BTSCODTN2__c = 62,    //A dis o
                                                        BTSCFNN__c  = 7,   BTSCFNN2__c   =  7,  BTSCFNTN__c = 62, BTSCFNTN2__c = 62,    //A dis f
                                                        BTSCUNN__c  = 3,   BTSCUNN2__c   =  3,  BTSCNTN__c  = 67, BTSCNTN2__c  = 67,    //A und
                                                        BTSCHYN__c  = 5,   BTSCHYN2__c   =  5,  BTSCHYTN__c = 90, BTSCHYTN2__c = 90     //A hyp
                                                        );  
                
        //set form's status 
        obj.STATUS_TSCC_A__c = 'Complete';        
        
        test.startTest();  
        //insert object
        insert obj;
        test.stopTest();
        
        //add obj to obj list
        ObjList.add(obj);
        
        //init controller for pages
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);  
          
        //controllers
        DS_TSCC_A_Controller controller = new DS_TSCC_A_Controller(sc);    
        DS_TSCC_A_Report_Controller RC = new DS_TSCC_A_Report_Controller(sc);       
        
        //save/cancel
        controller.save();
        controller.cancel();
        controller.saveview();
        
        RC.init();
        RC.editRecord();
        
        DS_TSCC_TSCYC_B__c tsc = [SELECT BTSCAXN__c, BTSCAGTN2__c, SECTION__c
                                    FROM DS_TSCC_TSCYC_B__c
                                    WHERE id =: obj.id];
        
        // assert statements 
        System.assertEquals(tsc.BTSCAXN__c, 20,'Incorrect Anxiety raw score.');
        System.assertEquals(tsc.BTSCAGTN2__c, 62,'Incorrect Anger T-score double entry.');
        System.assertEquals(tsc.SECTION__c, '0','Section incorrect: baseline.');
    }
}