src/objects/Audit_Trail__c.object
<CustomObject>
    <fields>
        <fullName>ACTION__c</fullName>
        <label>Action</label>
        <length>233</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Audit Trail</relationshipLabel>
        <relationshipName>Audit_Trail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DATE__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FORM_ID__c</fullName>
        <label>Form ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FORM__c</fullName>
        <label>Form</label>
        <length>233</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NUMBER__c</fullName>
        <label>Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRIOR_VALUE__c</fullName>
        <label>Prior Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>QUESTION__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <label>Section</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIME__c</fullName>
        <label>Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UPDATED_VALUE__c</fullName>
        <label>Updated Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>USER_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User ID</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audit_Trail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>USER_INITIAL__c</fullName>
        <label>User Initial</label>
        <length>233</length>
        <type>Text</type>
    </fields>
    <label>Audit Trail</label>
    <nameField>
        <displayFormat>AT-{0000000000}</displayFormat>
        <label>Audit Trail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>AGE__c</fullName>
        <description>Client&apos;s age as entered in the System Screening</description>
        <label>Age</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Clinician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinician ID</label>
        <referenceTo>Clinician__c</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOB1__c</fullName>
        <label>Date of birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GENDER__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t know/ Information not available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>INIT__c</fullName>
        <label>INITIALS</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Clinician__c.object
<CustomObject>
    <label>Clinician</label>
    <nameField>
        <label>Clinician ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinicians</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DS_DATA__c.object
<CustomObject>
    <fields>
        <fullName>CODELIST__c</fullName>
        <label>Codelist</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CODE__c</fullName>
        <label>CODE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data_Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FILE_NAME__c</fullName>
        <label>File_name</label>
        <picklist>
            <picklistValues>
                <fullName>BASELINE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRAUMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOLLOWUP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <picklist>
            <picklistValues>
                <fullName>DS_BIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_BSLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CANSTR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CLINEVAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DEMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FAPGAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FOLLOWUPINFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INSDOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_MILITARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NCTSNTREAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_POST_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_REFIMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_04_10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_S_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SERVREC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_YCINDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRABUSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRACCIDENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRBEREAVE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Boy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Girl</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LONGLABEL__c</fullName>
        <label>LONGLABEL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LONG_DESCRIPTION__c</fullName>
        <label>Long_Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOURCE_FORM__c</fullName>
        <label>Source_form</label>
        <picklist>
            <picklistValues>
                <fullName>BIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANSTR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBCL_SCORES_OLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBCL_SCORES_YOUNG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLINEVAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAPGAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAPGAR_SCORES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOLLOWUPINFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INSDOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MILITARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCTSNTREAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PTSD_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PTSD_SCORES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REFIMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDQ_P_04_10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDQ_P_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDQ_PARENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDQ_S_11_17</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Section</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VARIABLE_LABEL__c</fullName>
        <label>Variable_label</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>VARIABLE_NAME__c</fullName>
        <label>Variable_name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VARIABLE_NUMBER__c</fullName>
        <label>Variable_number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VARIABLE_TYPE__c</fullName>
        <label>Variable_type</label>
        <picklist>
            <picklistValues>
                <fullName>NUMBER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DATE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHAR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VARIABLE_VALUE__c</fullName>
        <label>Variable_value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>DS DATA</label>
    <nameField>
        <displayFormat>DS DATA - {000000}</displayFormat>
        <label>DS DATA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS DATA</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AuditTrail.cls
public class AuditTrail {

  Utility ut = new Utility();

  Map<String, String> codeList = new Map<String, String>();

  Set<String> forms = new Set<String>();

  Set<String> formsWithDS = new Set<String>();

  Set<String> clients = new Set<String>();

  Map<String, DS_DATA__c> formList = new Map<String, DS_DATA__c>();

  Map<String, client__c> clientList = new Map<String, client__c>();

  Map<String, List<DS_DATA__c>> dataDictionaryForm = new Map<String, List<DS_DATA__c>>();
  Map<String, DS_DATA__c> dataDictionaryField = new Map<String, DS_DATA__c>();

  public Set<String> hasInitialEntry;

  String creator = String.valueOf(UserInfo.getUserId());

  User user = [SELECT CommunityNickname FROM User WHERE id=: creator];


  public AuditTrail(List<SObject> newObj, List<SObject> oldObj) { 

    //Set<String> forms2 = new Set<String>();

    //Set<String> formsWithDS2 = new Set<String>();

    for(SObject obj : newObj) { 

      forms.addAll(getActivateForm(obj));

      String clientID = String.valueOf(obj.get('client__c'));
      
      clients.add(clientID);

    }

    for(String form : forms) formsWithDS.add('DS_'+form);
    
    List<DS_DATA__c> formInfo = [SELECT Content__c, Page__c
                                   FROM DS_DATA__c
                                  WHERE Data_Type__c = 'DS_Form_Info'
                                    AND Page__c IN : formsWithDS];

    for(DS_DATA__c f : formInfo)
      formList.put(f.Page__c, f);

    List<client__c> clientInfo = [SELECT id, AGE__c, DOB1__c, GENDER__c, 
                                         INIT__c, Clinician__c
                                    FROM Client__c
                                   WHERE id IN : clients];

    for(Client__c c : clientInfo) 
      clientList.put(c.id, c);

    List<DS_DATA__c> variables = [SELECT CODELIST__c, FILE_NAME__c, 
                                         SOURCE_FORM__c, VARIABLE_NUMBER__c,
                                         LONG_DESCRIPTION__c, VARIABLE_LABEL__c,
                                         VARIABLE_NAME__c, VARIABLE_TYPE__c,
                                         VARIABLE_VALUE__c
                                    FROM DS_DATA__c 
                                   WHERE Data_Type__c = 'DS_VARIABLE'
                                     AND SOURCE_FORM__c IN :forms];
        
    for(DS_DATA__c var : variables) {

      String formID = var.SOURCE_FORM__c;
      List<DS_DATA__c> data = new List<DS_DATA__c>(); 

      if(dataDictionaryForm.containsKey(formID)) 
        data = dataDictionaryForm.get(formID);

      data.add(var); 

      dataDictionaryForm.put(formID, data);

      dataDictionaryField.put(var.VARIABLE_NAME__c, var);

    }

    List<DS_Data__c> codeListDB = [SELECT LONGLABEL__c, CODE__c, CODELIST__c
                                     FROM DS_DATA__c
                                    WHERE Data_Type__c = 'DS_CODELIST'];

    for(DS_DATA__c code : codeListDB) 
      codeList.put(code.CODELIST__c+'-'+code.CODE__c, code.LONGLABEL__c);

    hasInitialEntry = checkInitialEntry();
    
  }

  public Set<String> getActivateForm(Sobject obj) {

    Set<String> actforms = new Set<String>();

    String objectType = String.valueOf(obj.getsObjectType());

    String objName = objectType.substringBefore('__c');

    List<String> statusFields = ut.getFieldSetFields('STATUS', objectType);

    for(String statusField : statusFields) {

      // If status is not null, it means there is some data for that form
      // Add the form and run the auditrail. 
      if(obj.get(statusField) != null) {
      
        Pattern p = Pattern.compile('STATUS_(.*?)__c');
        Matcher pm = p.matcher(statusField);

        if( pm.matches() ) {

          actforms.add(pm.group(1));

        }

      }

    }

    return actforms;

  }

  public Set<String> checkInitialEntry() {

    Set<String> hasInitialEntry = new Set<String>();

    List<Audit_Trail__c> existData = [SELECT CLIENT__c, FORM__c, FORM_ID__c, 
                                             SECTION__c
                                        FROM Audit_Trail__c
                                       WHERE FORM_ID__c IN : forms
                                         AND CLIENT__c IN : clients];

    for(Audit_Trail__c audit : existData)
      hasInitialEntry.add(audit.FORM_ID__c+'-'+audit.CLIENT__c+'-'+audit.SECTION__c);
    
    return hasInitialEntry;

  }

  public void generateLog(List<SObject> newObj, List<SObject> oldObj) {

    Map<String, SObject> oldObjs = new Map<String, SObject>();

    if(oldObj != null)
      for(Sobject oObj : oldObj)
        oldObjs.put(String.valueOf(oObj.get('id')), oObj);

    List<Audit_Trail__c> auditTrialList = new List<Audit_Trail__c>();

    for(Sobject obj : newObj) {

      Set<String> formIDs = getActivateForm(obj);

      String section = String.valueOf(obj.get('SECTION__c'));
      String clientID = String.valueOf(obj.get('client__c'));

      for(String fID : formIDs) {

        if(!hasInitialEntry.contains(fID+'-'+clientID+'-'+section))
          auditTrialList.addAll(initialEntry(fID, clientID, section));
        else 
          auditTrialList.addAll(updateEntry(fID, obj, oldObjs.get(String.valueOf(obj.get('id')))));

      }

    }

    insert auditTrialList;

  }

  public List<Audit_Trail__c> initialEntry(String formID, String clientID, String section) {

    DateTime currentTime = System.now();

    List<Audit_Trail__c> auditTrialList = new List<Audit_Trail__c>();

    Client__c client = clientList.get(clientID);

    DS_DATA__c form = formList.get('DS_'+formID);

    System.debug(formList);
    System.debug(formID);

    Audit_Trail__c log = new Audit_Trail__c();
 
    log.Action__c = 'Initial Entry';
    log.Client__c = client.id;
    log.Date__c = currentTime.date();
    log.Time__c = currentTime.format('HH:mm:ss');
    log.Form__c = form.Content__c;
    log.FORM_ID__c = formID;
    log.User_Initial__c = user.CommunityNickname;
    log.User_ID__c = creator;
    log.SECTION__c = section;

    auditTrialList.add(log);

    return auditTrialList;

  }

  public List<Audit_Trail__c> updateEntry(String formID, SObject newObj, SObject oldObj) {

    List<Audit_Trail__c> auditTrialList = new List<Audit_Trail__c>();

    if(oldObj == null) return auditTrialList;


    List<DS_DATA__c> fields = dataDictionaryForm.get(formID);

    Client__c client = clientList.get(String.valueOf(newObj.get('Client__c')));

    DS_DATA__c form = formList.get('DS_'+formID);

    DateTime currentTime = System.now();

    List<Audit_Trail__c> logList = new List<Audit_Trail__c>();

    if(fields != null) {

      for(DS_DATA__c f : fields) {

        // If the field of DD doesn't exist in force, skip this field and move to the next one. 
        //if(ut.hasSObjectField(f.VARIABLE_NAME__c+'__c', oldObj)) continue;

        String priorRawValue = String.valueOf(oldObj.get(f.VARIABLE_NAME__c+'__c'));

        String updateRawValue = String.valueOf(newObj.get(f.VARIABLE_NAME__c+'__c'));

        if(priorRawValue != updateRawValue) {

          String priorValue = (f.CODELIST__c == '<None>' || f.CODELIST__c == '<DATE>') ? 
                              String.valueOf(oldObj.get(f.VARIABLE_NAME__c+'__c')) : 
                              codeList.get(f.CODELIST__c+'-'+String.valueOf(oldObj.get(f.VARIABLE_NAME__c+'__c')));

          String updateValue = (f.CODELIST__c == '<None>' || f.CODELIST__c == '<DATE>') ? 
                               String.valueOf(newObj.get(f.VARIABLE_NAME__c+'__c')) : 
                               codeList.get(f.CODELIST__c+'-'+String.valueOf(newObj.get(f.VARIABLE_NAME__c+'__c')));

          Audit_Trail__c log = new Audit_Trail__c();

          log.Action__c = 'Update';
          log.Client__c = client.id;
          log.Date__c = currentTime.date();
          log.Time__c = currentTime.format('HH:mm:ss');
          log.Form__c = form.Content__c;
          log.FORM_ID__c = formID;
          log.Number__c = f.VARIABLE_NUMBER__c;
          log.SECTION__c = String.valueOf(newObj.get('SECTION__c'));
          log.Prior_Value__c = priorValue;
          log.Updated_Value__c = updateValue;
          log.Question__c = f.LONG_DESCRIPTION__c;
          log.User_Initial__c = user.CommunityNickname;
          log.User_ID__c = creator;

          auditTrialList.add(log);

          System.debug(log);

      	}

    	}

		}

  	return auditTrialList;

  }
}