src/objects/Center__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Main</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Center</label>
    <nameField>
        <label>Center ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Clinician__c.object
<CustomObject>
    <fields>
        <fullName>Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Center</label>
        <referenceTo>Center__c</referenceTo>
        <relationshipLabel>Clinicians</relationshipLabel>
        <relationshipName>Clinicians</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Clinician</label>
    <nameField>
        <label>Clinician ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinicians</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Counter__c.object
<CustomObject>
    <fields>
        <fullName>Counter__c</fullName>
        <defaultValue>1</defaultValue>
        <description>To count sub-center</description>
        <label>Counter (Sub-center)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>0: Main
1: Sub
2: Clinician</description>
        <label>Type</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Counter</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClinicianController.cls
/*Page Description:
 *  Controller Class for Clinician
 * Last Updated on:
 *  7/17/2014
 * Update Purpose:
 *      
 * Programmer:
 *  
 */
public with sharing class ClinicianController {
    
  String ID = Apexpages.currentPage().getParameters().get('id');
  
  public Clinician__c clinician {get;set;}
  
  public Integer edit {get; set;}
  
  public String title {get; set;}
  public String subtitle {get; set;}
  
  public Integer roleType {get; set;}

  public RoleController roleManager = new RoleController();
  
  public ClinicianController(ApexPages.StandardController controller) {

    title = 'Create Clinician';
    subtitle = 'Clinician';
    edit = 0;
    roleType = 0;
    
    Counter__c roleInfo = roleManager.RoleType(UserInfo.getUserRoleId());
    
    roleType = Integer.valueof(roleInfo.Type__c);
    
    if(ID != null) {
        
      clinician = [SELECT Center__c, Name, Name__c
                     FROM Clinician__c 
                    WHERE id = :ID];
  
      edit = 1;
      title = 'Clinician Edit';
      subtitle = '(' + clinician.Name + ') ' + clinician.Name__c;
        
    }
    
  }

}