src/objects/Center__c.object
<CustomObject>
    <fields>
        <fullName>Input_ID__c</fullName>
        <label>Input ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Main_center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Center</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Center__c.Type__c</field>
                <operation>equals</operation>
                <value>Main</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Center__c</referenceTo>
        <relationshipLabel>Sub-Centers</relationshipLabel>
        <relationshipName>Subcenters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Main</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Center</label>
    <nameField>
        <label>Center ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Counter__c.object
<CustomObject>
    <fields>
        <fullName>Counter__c</fullName>
        <defaultValue>1</defaultValue>
        <description>To count sub-center</description>
        <label>Counter (Sub-center)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role_ID__c</fullName>
        <label>Role ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>0: Main
1: Sub
2: Clinician</description>
        <label>Type</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Counter</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CenterController.cls
/*Page Description:
 *  Controller Class for Centers
 * Last Updated on:
 *  7/17/2014
 * Update Purpose:
 *      
 * Programmer:
 *  
 */
 public with sharing class CenterController {

    String ID = Apexpages.currentPage().getParameters().get('id');
    
    public Boolean createSub {get; set;}
    
    public Integer mainSub {get; set;}
    public Boolean isAdmin {get; set;}
    public Boolean newEdit {get; set;}
    
    public Center__c center {get;set;}
    
    public String title {get; set;}
    public String subtitle {get; set;}

    public RoleController roleManager = new RoleController();

    public CenterController(ApexPages.StandardController controller) {
    
        mainSub = 0;
        newEdit = TRUE;
            
        createSub = (Apexpages.currentPage().getParameters().get('CF00Ni000000Bk39L') != null) ? TRUE : FALSE;
        
        title = 'Create Center';
        subtitle = 'Center';
        
        //String userRole = UserInfo.getUserRoleId();
        
        /*Counter__c counter = [SELECT Type__c 
                                FROM Counter__c 
                               WHERE Role_ID__c = :UserInfo.getUserRoleId()];*/
        
        //System.debug(UserInfo.getUserRoleId());
        
        Counter__c roleInfo = roleManager.RoleType(UserInfo.getUserRoleId());
        
        isAdmin = (roleInfo.Type__c == 0) ? TRUE : FALSE;
        
        //if(createSub) mainSub = 1;
    
        if(ID != null) {
            
            newEdit = FALSE;
        
            center = [SELECT Main_center__c, Name, CreatedDate, IsDeleted, 
                             Input_ID__c, Name__c, OwnerId, Type__c 
                        FROM Center__c
                       WHERE id = :Apexpages.currentPage().getParameters().get('id')
                         AND IsDeleted = false]; 
        
            mainSub = (center.Type__c == 'Main') ? 1 : 2;
            
            //if(isAdmin == TRUE) mainSub = 0;
            
            title = 'Cetner Edit';
            subtitle = '(' + center.Name + ') ' + center.Name__c;
            
        }
    }
    
    
       
    public List<SelectOption> getItems() {
    
        List<SelectOption> options = new List<SelectOption>(); 
        
        options.add(new SelectOption('Main','Main Center')); 
        options.add(new SelectOption('Sub','Sub-center')); 
                
        return options; 
    }
    
    
    
    
}