src/objects/Center__c.object
<CustomObject>
    <fields>
        <fullName>Input_ID__c</fullName>
        <label>Input ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Main_center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Center</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Center__c.Type__c</field>
                <operation>equals</operation>
                <value>Main</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Center__c</referenceTo>
        <relationshipLabel>Sub-Centers</relationshipLabel>
        <relationshipName>Subcenters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Main</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Center</label>
    <nameField>
        <label>Center ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Clinician__c.object
<CustomObject>
    <fields>
        <fullName>Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Center</label>
        <referenceTo>Center__c</referenceTo>
        <relationshipLabel>Clinicians</relationshipLabel>
        <relationshipName>Clinicians</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Clinician</label>
    <nameField>
        <label>Clinician ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinicians</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CenterDeletion.cls
/*Page Description:
 *  Class to delete Center Information
 * Last Updated on:
 *  7/17/2014
 * Update Purpose:
 *      
 * Programmer:
 *  
 */
public with sharing class CenterDeletion {
    
    String ID = Apexpages.currentPage().getParameters().get('id');
    
    Center__c center {get;set;}
    
    public String subtitle {get; set;}
    
    private ApexPages.StandardController standardController;
    
    public Integer subcenter {get; set;}

    public Integer clinician {get; set;}
    
    public Integer total {get; set;}

    public CenterDeletion(ApexPages.StandardController controller) {
    
        total = 0;
    
        center = [
                    SELECT Name, 
                         CreatedDate, 
                         IsDeleted, 
                         Input_ID__c, 
                         Name__c, 
                         OwnerId, 
                         Type__c 
                    FROM Center__c
                   WHERE id = :Apexpages.currentPage().getParameters().get('id')
                                                                                ]; 
                   
        subtitle = '(' + 
                         center.Name 
                                     + ') ' + 
                                                center.Name__c; 
        

        if(!Test.isRunningTest()) {

            controller.addFields(new List<String> { 'Subcenters__r' }); 
            controller.addFields(new List<String> { 'Clinicians__r' });

        }
        
        subcenter = ((Center__c) controller.getRecord()).Subcenters__r.size(); 
        clinician = ((Center__c) controller.getRecord()).Clinicians__r.size(); 

        total = subcenter + clinician;
       
    
    }
    
    public PageReference checkDeletion() {
        
        if(total > 0) {  
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.info,'Your attempt to delete the center could not be completed because Sub-center(s) or Clinician(s) is currently assigned to this center. Please delete the following items first.'));
        }
        else { 
            delete center; 
            PageReference pageRef = new PageReference('/a00/o'); 
            return pageRef; 
        } 

        return null;
        
        
    }

}