src/objects/Center__c.object
<CustomObject>
    <fields>
        <fullName>Main_center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Center</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Center__c.Type__c</field>
                <operation>equals</operation>
                <value>Main</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Center__c</referenceTo>
        <relationshipLabel>Sub-Centers</relationshipLabel>
        <relationshipName>Subcenters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Center</label>
    <nameField>
        <label>Center ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestClass_RecordSharing.cls
@isTest (SeeAllData=false)
public Class TestClass_RecordSharing {

	static TestMethod void Test_Utility() {

		TestClass_Utility test_ut = new TestClass_Utility();

		Center__c subCenter = test_ut.createSubCenter();

		RoleController roleManager = new RoleController();

		RecordSharing roleShare = new RecordSharing();

		//RecordSharing.manualShare('Center__Share', subCenter.id, Id userOrGroupId, String acclevel)

		roleShare.sharingLoop(subCenter.Main_center__c, subCenter.id, 'Center__Share', roleManager);
	}

}