src/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DS_Functioning_Forms_B__c.object
<CustomObject>
    <fields>
        <fullName>BNADMINOSP__c</fullName>
        <description>2. Indicate who administered question 1 above: other specified</description>
        <label>BNADMINOSP</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BNDAILYL__c</fullName>
        <description>1a. I am handling daily life</description>
        <label>BNDAILYL</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>96</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>97</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Functioning Forms B</relationshipLabel>
        <relationshipName>DS_Functioning_Forms_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS Functioning Forms B</label>
    <nameField>
        <label>DS Functioning Forms B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Functioning Forms B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestClass_DS_NOMS.cls
@istest(SeeAllData=false)
public class TestClass_DS_NOMS{

static TestMethod void Test_DS_NOMS_Controller() {

        Utility ut = new Utility();
        TestClass_Utility test_ut = new TestClass_Utility();
        
        Client__c client = test_ut.createClientSummary();
    String cimi = ut.urlEncode('c='+client.id+'&s=0');
ApexPages.currentPage().getParameters().put('cimi',cimi);

    DS_Functioning_Forms_B__c obj = new DS_Functioning_Forms_B__c();    
        //obj.STATUS__c = 'Complete';
        obj.client__c = client.id;      
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        DS_NOMS_Controller controller = new DS_NOMS_Controller(sc);
        
        List<SelectOption> admin = controller.getAdminItems();

        controller.save();
        controller.cancel();
        
        // Update record
        obj = [SELECT id FROM DS_Functioning_Forms_B__c WHERE client__c =: client.id];
        sc = new ApexPages.StandardController(obj);
        controller = new DS_NOMS_Controller(sc);
        ApexPages.currentPage().getParameters().put('cimi', cimi);
        controller.save();    
    }
    
  static TestMethod void Test_samlpeAsserts(){  
  
    Utility ut = new Utility();
    TestClass_Utility test_ut = new TestClass_Utility();
    
//create test client 
    Client__c client = test_ut.createClientSummary();
String cimi= ut.urlEncode('c='+client.id);
ApexPages.currentPage().getParameters().put('cimi',cimi);

    DS_Functioning_Forms_B__c obj = new DS_Functioning_Forms_B__c();
      obj.client__c = client.id;
      
    ApexPages.StandardController sc = new ApexPages.StandardController(obj);
    
    //    controllers
 DS_NOMS_Controller nomsController = new DS_NOMS_Controller(sc);
 
String BNDAILYL='1';
String BNADMINOSP= 'null'; 

 insert obj;
 
 //asserts
  System.assertNotEquals(obj.BNDAILYL__c, BNDAILYL, 'I [my child] do[es] NOT strongly disagree that the child is handling dsily life.');
  System.assertNotEquals(obj.BNADMINOSP__c,BNADMINOSP , 'Form was administered by '+obj.BNADMINOSP__c+'.');
  
 //save/cancels
   nomsController.save();
   nomsController.cancel();
  }
}