src/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FORM_TYPE__c</fullName>
        <label>FORM_TYPE</label>
        <picklist>
            <picklistValues>
                <fullName>Baseline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DS DATA Page</label>
        <referenceTo>DS_DATA__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REQUIRED__c</fullName>
        <defaultValue>false</defaultValue>
        <label>REQUIRED</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STATUS__c</fullName>
        <label>STATUS</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Client Summary</label>
    <nameField>
        <displayFormat>summary-{000000}</displayFormat>
        <label>Client Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DS_DATA__c.object
<CustomObject>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Section</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Variable__c</fullName>
        <label>Variable</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DS DATA</label>
    <nameField>
        <displayFormat>DS DATA - {000000}</displayFormat>
        <label>DS DATA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS DATA</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SkipLogic.cls
/*Page Description:
 *  Class to Control Skip Logic
 * Last Updated on:
 *  7/17/2014
 * Update Purpose:
 *      
 * Programmer:
 *  
 */
public class SkipLogic {

  Utility ut = new Utility();
   
  public Map<String, Map<String, SkipElement>> skipList {get; set;}
  public Map<String, Boolean> skipAction {get; set;}

  Object emptyTextNumber = null;
  Object emptyCheck = FALSE;
  Object emptyNumber = 0;
   
  public class SkipElement {
        
    public String source { get;set; }
    public String triggerValue { get;set; }
    public Boolean rendered { get;set; }
    public String fieldType { get;set; }
    public String targetValue { get; set; }

    public SkipElement(Boolean rendered, String triggerValue, String fieldType) {
      this.triggerValue = triggerValue;
      this.rendered = rendered;
      this.fieldType = fieldType;
    }

    public void addTargetValue(String targetValue) {
      this.targetValue = targetValue;
    }


  } 

  public SkipLogic() {

    skipList = new Map<String, Map<String, SkipElement>>();
    skipAction = new Map<String, Boolean>();

  }

  public void skipLibrary(String triggerField, String display, String triggerValue, Map<String, String> target) {

    Map<String, SkipElement> elements = new Map<String, SkipElement>();

    Boolean show = (display == 'show') ? TRUE : FALSE;

    for(String key : target.keySet()) 
      elements.put(key, new SkipElement(show, triggerValue, target.get(key)));
    
    skipList.put(triggerField, elements);

  }
  
  public void runSkipLogic(String source, String value, Sobject ob) {
      
    Boolean action = TRUE;
    String fieldType = '';

    Map<String, SkipElement> element = skipList.get(source);

    for(String key : element.keySet()) { 

      if(value == element.get(key).triggerValue) 
        action = element.get(key).rendered; 
      else { 
        action = !element.get(key).rendered;
        fieldType = element.get(key).fieldType;

        if(fieldType == 'text' || fieldType == 'number') ob.put(key+'__c', emptyTextNumber);
        else if(fieldType == 'checkbox') ob.put(key+'__c', emptyCheck);
      }

      //system.debug(key + ' ' + action);
      
      skipAction.put(key, action);

    } 

    //return ob;
  }
  

  public String formRedirct(ID clientID, String section, String forceRedirect) {

    String url;
    String formType;

    String urlClientIDF;

    System.debug(clientID + '-' + section + '-' + forceRedirect);

    if(forceRedirect == '1') {

      if (section == '0')       formType = 'Baseline'; 
      else if(section == '-1')  formType = 'TD';
      else                      formType = 'FollowUp';

      // Old structure
      /*List<Client_Summary__c> nextForm = Database.query('SELECT FORM_ID__r.Variable__c, FORM_ID__r.Page__c' + 
                                                        '  FROM Client_Summary__c ' +
                                                        ' WHERE Client__c = \'' + clientID + '\'' +
                                                        '   AND SECTION__c = \'' + section + '\''+
                                                        '   AND REQUIRED__c = TRUE ' +
                                                        '   AND FORM_TYPE__c = \'' + formType + '\'' +
                                                        '   AND STATUS__c = null ' +
                                                      'ORDER BY FORM_TYPE__c, FORM_ID__r.weight__c');*/


      List<Client_Summary__c> nextForm = 
          Database.query('SELECT Page__r.Variable__c, Page__r.Page__c' + 
                         '  FROM Client_Summary__c ' +
                         ' WHERE Client__c = \'' + clientID + '\'' +
                         '   AND SECTION__c = \'' + section + '\''+
                         '   AND REQUIRED__c = TRUE ' +
                         '   AND FORM_TYPE__c = \'' + formType + '\'' +
                         '   AND STATUS__c = null ' +
                       'ORDER BY FORM_TYPE__c, Page__r.weight__c');
        
      System.debug('SELECT Page__r.Variable__c, Page__r.Page__c' + 
                         '  FROM Client_Summary__c ' +
                         ' WHERE Client__c = \'' + clientID + '\'' +
                         '   AND SECTION__c = \'' + section + '\''+
                         '   AND REQUIRED__c = TRUE ' +
                         '   AND FORM_TYPE__c = \'' + formType + '\'' +
                         '   AND STATUS__c = null ' +
                       'ORDER BY FORM_TYPE__c, Page__r.weight__c');

      url = 'ClientSummary?s='+section+'&id='+clientID+'&f=1';


      if(section != '-1') {
        //urlClientIDF = ;
        url = (nextForm.size() > 0) ?  
          nextForm.get(0).Page__r.Page__c + 
          '?cimi=' + ut.urlEncode('c='+clientID+'&f=1&summary='+nextForm.get(0).id) : url;

      }
      // Trauma detail forms
      else {
        //urlClientIDF = ;
        url = (nextForm.size() > 0) ? 
          'DS_TDETAIL?cimi=' + 
          ut.urlEncode('c='+clientID+'&f=1&TDF='+nextForm.get(0).Page__r.Page__c.substringAfter('DS_')+'&summary='+nextForm.get(0).id) : url;
      }

    }
    else {
      url = 'ClientSummary?s='+section+'&id='+clientID;
    }

    return '/apex/' + url;

  }
}