src/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DS_SDQ_PSI_CDI_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOASDYP__c</fullName>
        <description>Parent 4-10: Date of Administration</description>
        <label>BDOASDYP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BMETSDYP__c</fullName>
        <description>Parent 4-10 method of administration</description>
        <label>BMETSDYP</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS SDQ PSI CDI B</relationshipLabel>
        <relationshipName>DS_SDQ_PSI_CDI_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>SECTION</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>DS SDQ PSI CDI B</label>
    <nameField>
        <label>DS SDQ PSI CDI B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS SDQ PSI CDI B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DS_SDQ_PSI_CDI_F__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS SDQ PSI CDI F</relationshipLabel>
        <relationshipName>DS_SDQ_PSI_CDI_F</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;1&apos;</defaultValue>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>DS SDQ PSI CDI F</label>
    <nameField>
        <label>DS SDQ PSI CDI F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS SDQ PSI CDI F</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_SDQ_PSI_CDI_F__c.object
    <fields>
        <fullName>FDOASDYP__c</fullName>
        <description>1. Parent 4-10: Date of Administration</description>
        <label>FDOASDYP</label>
        <type>Date</type>
    </fields>

Kelsey Development Sandbox/src/objects/DS_SDQ_PSI_CDI_F__c.object
    <fields>
        <fullName>FMETSDYP__c</fullName>
        <description>2. Parent 4-10: How was this form administered?</description>
        <label>FMETSDYP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/classes/TestClass_DS_SDQ_P_04_10_Report.cls
@isTest (SeeAllData=false)
private class TestClass_DS_SDQ_P_04_10_Report {
    
    public static TestClass_A_Utility test_ut = new TestClass_A_Utility();
    
    public static Utility ut = new Utility();
    
    @testSetup 
    static void setup() {
        // Load DS_DATA into system
        TestClassData_DS_DATA importData = new TestClassData_DS_DATA();      
    }
    
    static TestMethod void Test_Controller() {
        
        Client__c client = test_ut.createClient(test_ut.getClient('Female', 6));
        
        // Add Baseline record
        DS_SDQ_PSI_CDI_B__c objBaseline = new DS_SDQ_PSI_CDI_B__c();
        
        objBaseline.client__c = client.id;
        objBaseline.BDOASDYP__c = System.today();
        objBaseline.BMETSDYP__c = '1';
        
        insert objBaseline;
        
        // add a new follow-up visit
        String section = test_ut.addNewFollowupVisit(client);
        String summaryId = test_ut.getClientSummaryId(client.id, 'DS_SDQ_P_04_10', section);
        
        // Add Follow-up record
        DS_SDQ_PSI_CDI_F__c objFollow = new DS_SDQ_PSI_CDI_F__c();
        
        objFollow.client__c = client.id;
        objFollow.FMETSDYP__c = '1';
        objFollow.FDOASDYP__c = System.today();
        objFollow.SECTION__c = section;
        
        insert objFollow;       
        
        String cimi = ut.urlEncode('c='+client.id+'&summary='+summaryId);
        
        ApexPages.currentPage().getParameters().put('cimi', cimi);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(objFollow);  
        DS_SDQ_P_04_10_Report_Controller controller = new DS_SDQ_P_04_10_Report_Controller(sc); 
        
        controller.init();
        controller.editRecord();
        
    }    
    
}