src/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DS_Background_Family_Info_B__c.object
<CustomObject>
    <fields>
        <fullName>BCAMPMO__c</fullName>
        <description>Months in refugee/detention camp</description>
        <label>BCAMPMO</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BPSTNONE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>6. Parents&apos; status None</description>
        <label>BPSTNONE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BPUSBORN__c</fullName>
        <description>Parent born in US</description>
        <label>BPUSBORN</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BREFCAMP__c</fullName>
        <description>Did the child ever live in a refugee or detention camp?</description>
        <label>BREFCAMP</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BUSBORN__c</fullName>
        <description>Child born in the US</description>
        <label>BUSBORN</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Background Family Info B</relationshipLabel>
        <relationshipName>DS_Background_Family_Info_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RWHITE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is White</description>
        <label>RWHITE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STATUS_REFIMM__c</fullName>
        <label>STATUS REFIMM</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DS Background Family Info B</label>
    <nameField>
        <label>DS Background Family Info B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Background Family Info B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestClass_DS_REFIMM.cls
@istest(SeeAllData=false)
public class TestClass_DS_REFIMM {
    
    public static TestClass_A_Utility test_ut = new TestClass_A_Utility();
    
    public static Utility ut = new Utility();
    
    @testSetup 
    static void setup() {
        // Load DS_DATA into system
        TestClassData_DS_DATA importData = new TestClassData_DS_DATA();      
    }
    
    // Test baseline controller 
    static TestMethod void Test_Baseline_Controller() {
        
        Client__c client = test_ut.createClient();
        
        DS_Background_Family_Info_B__c obj = new DS_Background_Family_Info_B__c();          
        
        obj.Client__c = client.id;
        obj.BUSBORN__c = '0';        
        obj.BPUSBORN__c  = '0';
        obj.RWHITE__c = true;
        obj.SECTION__c = '0';
                   
        insert obj;    
        
        // Get summaryId for Url
        String summaryId = test_ut.getClientSummaryId(client.id, 'DS_REFIMM', '0');
        
        String cimi = ut.urlEncode('c='+client.id+'&summary='+summaryId);
        
        ApexPages.currentPage().getParameters().put('cimi',cimi);
        
        obj = new DS_Background_Family_Info_B__c();    
        obj.STATUS_REFIMM__c = 'Complete';
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);    
        DS_REFIMM_Controller controller = new DS_REFIMM_Controller(sc);        
        
        List<SelectOption> EngWell= controller.getEngWellItems();
        List<SelectOption> CTDECT= controller.getCTDECT();
        
        controller.save();
        controller.cancel();
     
    }
    
    static TestMethod void Test_samlpeAsserts(){    
        
        //create test client 
        Client__c client = test_ut.createClient();
        
        DS_Background_Family_Info_B__c obj = new DS_Background_Family_Info_B__c();
        obj.RWHITE__c=true;
        obj.client__c = client.id;
        
        //Refimm 
        String BREFCAMP= '1';
        Boolean BPSTNONE  = true;
        String BCAMPMO= 'null'; 
        
        insert obj;
        
        //asserts 
        //Refimm   
        System.assertNotEquals(obj.BREFCAMP__c,BREFCAMP,'Child has NOT lived in refugee/detention camp.');
        System.assertNotEquals(obj.BPSTNONE__c,BPSTNONE,'Child has had Refugee, Asylee, or Immigrant status, or status is unknown.');
        System.assertNotEquals(obj.BCAMPMO__c,BCAMPMO,'Child lived '+obj.BCAMPMO__c+' months in a detention/refugee camp.');
        
    }
}