src/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DS_Functioning_Forms_B__c.object
<CustomObject>
    <fields>
        <fullName>BLTCOGB__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Cognitive behavioral therapy Lifetime</description>
        <label>BLTCOGB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BOSMEN__c</fullName>
        <description>Mentor 30 days</description>
        <label>BOSMEN</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BOSOSP__c</fullName>
        <description>Other Service 30 days specified</description>
        <label>BOSOSP</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Functioning Forms B</relationshipLabel>
        <relationshipName>DS_Functioning_Forms_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>STATUS_SERVREC__c</fullName>
        <label>STATUS SERVREC</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DS Functioning Forms B</label>
    <nameField>
        <label>DS Functioning Forms B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Functioning Forms B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DS_Functioning_Forms_F__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Functioning Forms F</relationshipLabel>
        <relationshipName>DS_Functioning_Forms_F</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>STATUS_SERVREC__c</fullName>
        <label>STATUS SERVREC</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DS Functioning Forms F</label>
    <nameField>
        <label>DS Functioning Forms F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Functioning Forms F</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestClass_DS_SERVREC.cls
@istest(SeeAllData=false)
public class TestClass_DS_SERVREC {
    
    public static TestClass_A_Utility test_ut = new TestClass_A_Utility();
    
    public static Utility ut = new Utility();
    
    @testSetup 
    static void setup() {
        // Load DS_DATA into system
        TestClassData_DS_DATA importData = new TestClassData_DS_DATA();      
    }
    
    // Test baseline controller 
    static TestMethod void Test_Baseline_Controller() {
        
        Client__c client = test_ut.createClient();
        
        // Get summaryId for Url
        String summaryId = test_ut.getClientSummaryId(client.id, 'DS_SERVREC', '0');
        
        String cimi = ut.urlEncode('c='+client.id+'&summary='+summaryId);
        
        ApexPages.currentPage().getParameters().put('cimi',cimi);
        
        DS_Functioning_Forms_B__c obj = new DS_Functioning_Forms_B__c();    
        obj.STATUS_SERVREC__c = 'Complete';
        obj.client__c = client.id;        
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);    
        DS_SERVREC_Controller controller = new DS_SERVREC_Controller(sc);        
                
        controller.save();
        controller.cancel();
     
    }
    
    // Test follow-up controller 
    static TestMethod void Test_Followup_Controller() {
        
        Client__c client = test_ut.createClient();
        
        // add a new follow-up visit
        String section = test_ut.addNewFollowupVisit(client);
        
        String summaryId = test_ut.getClientSummaryId(client.id, 'DS_SERVREC', section);
        
        String cimi = ut.urlEncode('c='+client.id+'&summary='+summaryId);
        ApexPages.currentPage().getParameters().put('cimi',cimi);
        
        DS_Functioning_Forms_F__c obj = new DS_Functioning_Forms_F__c();    
        obj.STATUS_SERVREC__c = 'Complete';
        obj.client__c = client.id;        
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);    
        DS_SERVREC_Controller controller = new DS_SERVREC_Controller(sc);        
                
        controller.save();
        controller.cancel();
        
    }
    
    static TestMethod void Test_samlpeAsserts(){         
        
      //  Utility ut = new Utility();
      //  TestClass_A_Utility test_ut = new TestClass_A_Utility();
        
        //create test client 
        Client__c client = test_ut.createClientSummary();
        String cimi= ut.urlEncode('c='+client.id);
        ApexPages.currentPage().getParameters().put('cimi',cimi);
        
        DS_Functioning_Forms_B__c obj = new DS_Functioning_Forms_B__c();
        obj.client__c = client.id;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        
        //    controllers
       // DS_SERVREC_Controller servrecController = new DS_SERVREC_Controller(sc);
        
        String BOSMEN='99';
        Boolean BLTCOGB = true;
        String BOSOSP= 'null';  
        
        insert obj;
        
        //asserts
        System.assertNotEquals(obj.BOSMEN__c,BOSMEN , 'It is known if the child has recieved mentor services or not within the last 30 days.'); 
        System.assertNotEquals(obj.BLTCOGB__c,BLTCOGB , 'Child has NOT recieved cognitive behavioral therapy in lifetime.');
        System.assertNotEquals(obj.BOSOSP__c,BOSOSP , 'Other service is specified as'+obj.BOSOSP__c+'.');
        
        //save/cancels
     //   servrecController.save();
       // servrecController.cancel();
    }
}