src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>INIT__c</fullName>
        <label>INITIALS</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Client Summary</label>
    <nameField>
        <displayFormat>summary-{000000}</displayFormat>
        <label>Client Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DS_DATA__c.object
<CustomObject>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data_Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <picklist>
            <picklistValues>
                <fullName>DS_BIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_BSLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CANSTR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CLINEVAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DEMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FAPGAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FOLLOWUPINFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INSDOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_MILITARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NCTSNTREAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_POST_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_REFIMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_04_10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_S_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SERVREC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_YCINDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRABUSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRACCIDENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRBEREAVE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Section</label>
        <type>Checkbox</type>
    </fields>
    <label>DS DATA</label>
    <nameField>
        <displayFormat>DS DATA - {000000}</displayFormat>
        <label>DS DATA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS DATA</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DS_SDQ_PSI_CDI_B__c.object
<CustomObject>
    <fields>
        <fullName>BSDSEBCD__c</fullName>
        <description>Self 11-17: Overall, do you think that you have difficulties in any of the following areas: emotions, concentration, behavior or being able to get on with other people?</description>
        <label>BSDSEBCD</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS SDQ PSI CDI B</relationshipLabel>
        <relationshipName>DS_SDQ_PSI_CDI_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FORM__c</fullName>
        <label>FORM</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>SECTION</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STATUS_SDQ_S_11_17__c</fullName>
        <label>STATUS SDQ S 11 17</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DS SDQ PSI CDI B</label>
    <nameField>
        <label>DS SDQ PSI CDI B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS SDQ PSI CDI B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DS_SDQ_S_B_Controller.cls
public with sharing class DS_SDQ_S_B_Controller {

        Utility ut = new Utility();
        
Map<String, String> parameter = ut.urlDecode(Apexpages.currentPage().getParameters().get('cimi'));


   
   //      public DS_SDQ_PSI_CDI_B__c SDQobj { get; set; }//
         
         public SObject obj {get; set;}
         
   String cID;// { get; set; }
   
   public Client_Summary__c summary;///////
  
  String summaryID;
  
  public String forceRedirect { get; set; } 
  
  Boolean edit = FALSE;
  
  public String subtitle {get; set;} 
  
  public Client__c client { get; set; }
  
  public Client_Summary__c summaryInfo { get; set; }  
    
  public SkipLogic skip {get;set;}
  
  public String skipElementToJson { get; set; }
  
  public Map<String, String> bfVariableMap { get; set; }
  
  public String triggerValue {get; set;}
  public String skipTrigger {get; set;}
  public Boolean difficultAction {get; set;}  
  
  public String difficultModuleStatus { get; set; }
  
 // public String BorF { get; set; }
  
  
  

  
  
  
  
  
  
  
    public DS_SDQ_S_B_Controller(ApexPages.StandardController controller) {
  
    parameter = ut.urlDecode(Apexpages.currentPage().getParameters().get('cimi'));
    
        cID = parameter.get('c');
        
    summaryID = parameter.get('summary');
    
        forceRedirect = (parameter.containsKey('f')) ? parameter.get('f') : '';
        
        skip = new SkipLogic();  
        
        client = [SELECT Name, INIT__c FROM Client__c WHERE id =: cID];  
        
            summary = [SELECT SECTION__c FROM Client_Summary__c WHERE ID =:summaryID];
            
    String BorF = (Integer.valueOf(summary.SECTION__c) > 0) ? 'F' : 'B';
                    
    subtitle = '(' + client.Name + ') ' + client.INIT__c;            
    
    String getDEMOFields =  ut.getFields('DS_SDQ_PSI_CDI_'+BorF+'__c');      
    ////////////////////////////////////////////////////////////   
    List<DS_SDQ_PSI_CDI_B__c> record = 
    Database.query('SELECT ' + getDEMOFields + ', ' +
                             ' Client__r.Name, Client__r.INIT__c' +  
                             '  FROM DS_SDQ_PSI_CDI_'+BorF+'__c'+                          
                             ' WHERE CLIENT__c = \''+ cID + '\'' 
                             //  +  '   AND FORM__c = \'DS_SDQ_S_11_17_B\''
                              );         
                              
         if(record.size() == 0) { // New record    
        Schema.SObjectType objType = Schema.getGlobalDescribe().get('DS_SDQ_PSI_CDI_'+BorF+'__c');    
        obj = objType.newSObject();
        obj.put('CLIENT__c', cID); 
        obj.put('FORM__c', 'DS_SDQ_S_11_17');
    }                  
    else {   // Update oldRec      
        obj = record.get(0);
        edit = TRUE;   

        obj.put('FORM__c', 'DS_SDQ_S_11_17');
    }
    
        List<DS_DATA__c> formInfo = 
      Database.query('SELECT ' + ut.getFields('DS_DATA__c') +   
                     '  FROM DS_DATA__c ' +
                     ' WHERE Data_Type__c = \'DS_Form_Info\'' +
                  ' ORDER BY Number__c');
                  
                  
                  
    difficultModuleStatus = String.valueOf(obj.get('BSDSEBCD__c'));
    
    
    
    skipElementToJson = JSON.serialize(skip.skipList);
    
    bfVariableMap = new Map<String, String>();    
    
    List<String> bfVariable =
        new List<String>{'DOASDOP','DOASDOS','METSDOP','METSDOS','METSDYP',
        'SDSAFRA','SDSATTE','SDSBEH','SDSBTYP','SDSBULL','SDSCARI',
'SDSCLIN','SDSCOMM','SDSCONS','SDSDCL','SDSDIST','SDSEBCD','SDSEBDD','SDSEMO',
'SDSETYP','SDSFAM','SDSFIDG','SDSFIGH','SDSFRIE','SDSHELP','SDSHELPFL','SDSHTYP',
'SDSHYP','SDSIMPC','SDSIMPF','SDSIMPH','SDSIMPL','SDSITYP','SDSKHB','SDSKIND',
'SDSKTYP','SDSLIES','SDSLONE','SDSOBEY','SDSOLDB','SDSOTC','SDSOTYP','SDSPOPU',
'SDSPROB','SDSREFL','SDSREST','SDSSHAR','SDSSOMA','SDSSTEA','SDSTANT','SDSTIME',
'SDSTOT','SDSTYP','SDSUNHA','SDSUPSET','SDSWORR'};     


  for(String var : bfVariable)
      bfVariableMap.put(var, BorF+var+'__c');
      
       bfVariableMap.put('STATUS', 'STATUS_SDQ_S_11_17__c');      
    /////////////////////////
    
}

  public String getClientInfo() { return ut.clientSection(cID,SummaryID);} 
  
   public List<SelectOption> getOverallItems() {
   
    List<SelectOption> options = new List<SelectOption>();
     
    options.add(new SelectOption('0','No')); 
    options.add(new SelectOption('1','Yes- minor difficulties')); 
    options.add(new SelectOption('2','Yes- definite difficulties')); 
    options.add(new SelectOption('3','Yes- severe difficulties'));
    
    return options; 
    
  }
  
   public List<SelectOption> getHowLongItems() {
   
    List<SelectOption> options = new List<SelectOption>(); 
    
    options.add(new SelectOption('0','Less than a month')); 
    options.add(new SelectOption('1','1-5 months')); 
    options.add(new SelectOption('2','6-12 months')); 
    options.add(new SelectOption('3','Over a year'));
    
    return options;
     
  }      
   public List<SelectOption> getUpsetItems() {
   
    List<SelectOption> options = new List<SelectOption>(); 
    
    options.add(new SelectOption('0','Not at all')); 
    options.add(new SelectOption('1','Only a little')); 
    options.add(new SelectOption('2','A medium amount')); 
    options.add(new SelectOption('3','A great deal'));
    
    return options; 
    
  }     
   public List<SelectOption> getDifficultItems() {
   
    List<SelectOption> options = new List<SelectOption>(); 
    
    options.add(new SelectOption('0','Not at all')); 
    options.add(new SelectOption('1','Only a little')); 
    options.add(new SelectOption('2','A medium amount')); 
    options.add(new SelectOption('3','A great deal'));
    
    return options;     
  }

  public List<SelectOption> getBMETItems() {
    
    List<SelectOption> options = new List<SelectOption>(); 
    
    options.add(new SelectOption('','')); 
    options.add(new SelectOption('0','Pen and paper only')); 
    options.add(new SelectOption('1','Electronic only')); 
    
    return options; 
        
  }
  
    public PageReference cancel() {
    
    PageReference summaryPage = new PageReference('/apex/ClientSummary?s=0&id=' + cID);
    summaryPage.setRedirect(true);
    
    return summaryPage;
    
  }
  public PageReference save() {
  
    PageReference nextPage;
    
    try {
      if(edit == FALSE) insert obj;
      else update obj;
      nextPage = new PageReference(skip.formRedirct(cID, '0', forceRedirect));
      nextPage.setRedirect(true);
    }
    catch(DMLException e) { nextPage = null; }
    
    return nextPage;    
         
        }
        
    ///////////////////////////////////////////////////
    
  public PageReference saveview() {
  
    PageReference nextPage = new PageReference('/apex/DS_SDQ_S_11_17_Report?cimi=' + Apexpages.currentPage().getParameters().get('cimi'));
    nextPage.setRedirect(true);
    
    try {
      if(edit == FALSE) insert obj;
      else update obj;
    }
    catch(DMLException e) { nextPage = null; }
    
    return nextPage;    
        
        }        
      }