src/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DS_Functioning_Forms_B__c.object
<CustomObject>
    <fields>
        <fullName>BISPACAD__c</fullName>
        <description>Academic problems</description>
        <label>BISPACAD</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BISPCRSP__c</fullName>
        <description>In the past 30 days, how many times have you been arrested? Specified</description>
        <inlineHelpText>Can not be more than 30</inlineHelpText>
        <label>BISPCRSP</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BSUITALK__c</fullName>
        <description>Child ever talked about committing suicide</description>
        <label>BSUITALK</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Functioning Forms B</relationshipLabel>
        <relationshipName>DS_Functioning_Forms_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS Functioning Forms B</label>
    <nameField>
        <label>DS Functioning Forms B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Functioning Forms B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestClass_DS_INDSEV.cls
@istest(SeeAllData=false)
public class TestClass_DS_INDSEV{

static TestMethod void Test_DS_INDSEV_Controller() {

    Utility ut = new Utility();
    TestClass_Utility test_ut = new TestClass_Utility();

    Client__c client = test_ut.createClientSummary();
    String cimi = ut.urlEncode('c='+client.id+'&s=0');
ApexPages.currentPage().getParameters().put('cimi',cimi);

    DS_Functioning_Forms_B__c obj = new DS_Functioning_Forms_B__c();
    //obj.STATUS__c = 'Complete';
    obj.client__c = client.id;      
    ApexPages.StandardController sc = new ApexPages.StandardController(obj);    
    DS_INDSEV_Controller controller = new DS_INDSEV_Controller(sc);
    
    List<SelectOption> nsvu = controller.getNSVUItems();
    List<SelectOption> nyu = controller.getNYUItems();
    List<SelectOption> refunk = controller.getRefUnkItems();
    List<SelectOption> bnyui = controller.getBNYUItems();
    
    controller.save();
    controller.cancel();

    // Update record
    obj = [SELECT id FROM DS_Functioning_Forms_B__c WHERE client__c =: client.id];
    sc = new ApexPages.StandardController(obj);    
    controller = new DS_INDSEV_Controller(sc);
    ApexPages.currentPage().getParameters().put('cimi', cimi);
    controller.save();    
  }
  
  static TestMethod void Test_samlpeAsserts(){  
  
    Utility ut = new Utility();
    TestClass_Utility test_ut = new TestClass_Utility();
    
//create test client 
    Client__c client = test_ut.createClientSummary();
String cimi= ut.urlEncode('c='+client.id);
ApexPages.currentPage().getParameters().put('cimi',cimi);

    DS_Functioning_Forms_B__c obj = new DS_Functioning_Forms_B__c();
      obj.client__c = client.id;
      
    ApexPages.StandardController sc = new ApexPages.StandardController(obj);
    
    //    controllers
 DS_INDSEV_Controller indsevController = new DS_INDSEV_Controller(sc);
 
String BISPACAD='0';
String BSUITALK = '0';//
String BISPCRSP= 'null'; 
 
 insert obj;
 
 //asserts
  System.assertNotEquals(obj.BISPACAD__c,BISPACAD , 'Child has academic problems.');
  System.assertNotEquals(obj.BSUITALK__c,BSUITALK , 'Child has NOT talked about suicide.');
  System.assertNotEquals(obj.BISPCRSP__c,BISPCRSP , 'Child has been arrested '+obj.BISPCRSP__c+' time(s) in the past 30 days');

 //save/cancels
   indsevController.save();
   indsevController.cancel();
  }
}