src/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DS_Functioning_Forms_B__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Functioning Forms B</relationshipLabel>
        <relationshipName>DS_Functioning_Forms_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>STATUS_YCINDSEV__c</fullName>
        <label>STATUS YCINDSEV</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DS Functioning Forms B</label>
    <nameField>
        <label>DS Functioning Forms B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Functioning Forms B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DS_Functioning_Forms_F__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Functioning Forms F</relationshipLabel>
        <relationshipName>DS_Functioning_Forms_F</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>STATUS_YCINDSEV__c</fullName>
        <label>STATUS YCINDSEV</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DS Functioning Forms F</label>
    <nameField>
        <label>DS Functioning Forms F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Functioning Forms F</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestClass_DS_YCINDSEV.cls
@istest(SeeAllData=false)
private class TestClass_DS_YCINDSEV {
    
    public static TestClass_A_Utility test_ut = new TestClass_A_Utility();
    
    public static Utility ut = new Utility();
    
    @testSetup 
    static void setup() {
        // Load DS_DATA into system
        TestClassData_DS_DATA importData = new TestClassData_DS_DATA();      
    }
    
    // Test baseline controller 
    static TestMethod void Test_Baseline_Controller() {
        
        Client__c client = test_ut.createClient();
        
        // Get summaryId for Url
        String summaryId = test_ut.getClientSummaryId(client.id, 'DS_YCINDSEV', '0');
        
        String cimi = ut.urlEncode('c='+client.id+'&summary='+summaryId);
        
        ApexPages.currentPage().getParameters().put('cimi',cimi);
        
        DS_Functioning_Forms_B__c obj = new DS_Functioning_Forms_B__c();    
        obj.STATUS_YCINDSEV__c = 'Complete';
        obj.client__c = client.id;        
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);    
        DS_YCINDSEV_Controller controller = new DS_YCINDSEV_Controller(sc);        
        
        List<SelectOption> NSVUItems        =   controller.getNSVUItems();
        List<SelectOption> NYUItems         =   controller.getNYUItems();
        List<SelectOption> FeedItems        =   controller.getFeedItems();
        List<SelectOption> SleepItems       =   controller.getSleepItems();
        List<SelectOption> PlayItems        =   controller.getPlayItems();
        List<SelectOption> PreCareItems     =   controller.getPreCareItems();
        List<SelectOption> SocialItems      =   controller.getSocialItems();
        List<SelectOption> AggressiveItems  =   controller.getAggressiveItems();
        List<SelectOption> SexualizedItems  =   controller.getSexualizedItems();
        List<SelectOption> AttachmentItems  =   controller.getAttachmentItems();
        List<SelectOption> AtypicalItems    =   controller.getAtypicalItems();
        List<SelectOption> DevItems         =   controller.getDevItems();
        
        controller.save();
        controller.cancel();
     
    }
    
    // Test follow-up controller 
    static TestMethod void Test_Followup_Controller() {
        
        Client__c client = test_ut.createClient();
        
        // add a new follow-up visit
        String section = test_ut.addNewFollowupVisit(client);
        
        String summaryId = test_ut.getClientSummaryId(client.id, 'DS_YCINDSEV', section);
        
        String cimi = ut.urlEncode('c='+client.id+'&summary='+summaryId);
        ApexPages.currentPage().getParameters().put('cimi',cimi);
        
        DS_Functioning_Forms_F__c obj = new DS_Functioning_Forms_F__c();    
        obj.STATUS_YCINDSEV__c = 'Complete';
        obj.client__c = client.id;        
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);    
        DS_YCINDSEV_Controller controller = new DS_YCINDSEV_Controller(sc);        
        
        List<SelectOption> NSVUItems        =   controller.getNSVUItems();
        List<SelectOption> NYUItems         =   controller.getNYUItems();
        List<SelectOption> FeedItems        =   controller.getFeedItems();
        List<SelectOption> SleepItems       =   controller.getSleepItems();
        List<SelectOption> PlayItems        =   controller.getPlayItems();
        List<SelectOption> PreCareItems     =   controller.getPreCareItems();
        List<SelectOption> SocialItems      =   controller.getSocialItems();
        List<SelectOption> AggressiveItems  =   controller.getAggressiveItems();
        List<SelectOption> SexualizedItems  =   controller.getSexualizedItems();
        List<SelectOption> AttachmentItems  =   controller.getAttachmentItems();
        List<SelectOption> AtypicalItems    =   controller.getAtypicalItems();
        List<SelectOption> DevItems         =   controller.getDevItems();
        
        controller.save();
        controller.cancel();
        
    }
    
}