src/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DS_Background_Family_Info_B__c.object
<CustomObject>
    <fields>
        <fullName>BGUARDSP__c</fullName>
        <description>Guardian is Other, Specified</description>
        <label>BGUARDSP</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BGUARD__c</fullName>
        <description>Currently legal guardian for this child</description>
        <label>BGUARD</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>98</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BINFOSP__c</fullName>
        <description>Information from Other Specified</description>
        <label>BINFOSP</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BINFOTHR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Information from Other</description>
        <label>BINFOTHR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BPROSPNW__c</fullName>
        <description>Other healthcare provider Specified</description>
        <label>BPROSPNW</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BPROTHNW__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Other healthcare provider</description>
        <label>BPROTHNW</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BPUSBORNSP__c</fullName>
        <description>If no, In what country was the parent/caregiver born?</description>
        <label>BPUSBORNSP</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BPUSBORN__c</fullName>
        <description>Parent born in US</description>
        <label>BPUSBORN</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BREFSOSP__c</fullName>
        <description>Referral source is Other Specify</description>
        <label>BREFSOSP</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BREFSRO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Referral source is Other</description>
        <label>BREFSRO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BRHCOSP__c</fullName>
        <label>BRHCOSP</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BRHCO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BRHCO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BSIBLING__c</fullName>
        <description>Sibling in Core Data Set</description>
        <label>BSIBLING</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSIBNUM__c</fullName>
        <description>Number of Siblings in Core Data Set</description>
        <label>BSIBNUM</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BTREATOSP__c</fullName>
        <description>Primary Services indended Other Specified</description>
        <label>BTREATOSP</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BTREATO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Primary Services intended Other</description>
        <label>BTREATO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BUSBORN__c</fullName>
        <description>Child born in the US</description>
        <label>BUSBORN</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CTYBORN__c</fullName>
        <description>Country child born</description>
        <label>CTYBORN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CUREPI__c</fullName>
        <description>Child&apos;s 1st visit at center for curr epi</description>
        <label>CUREPI</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CUREPVS__c</fullName>
        <label>CUREPVS</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Background Family Info B</relationshipLabel>
        <relationshipName>DS_Background_Family_Info_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RREF__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Refused to Answer</description>
        <label>RREF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RWHITE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is White</description>
        <label>RWHITE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>STATUS_DEMO__c</fullName>
        <label>STATUS DEMO</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DS Background Family Info B</label>
    <nameField>
        <label>DS Background Family Info B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Background Family Info B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestClass_DS_DEMO.cls
@istest(SeeAllData=false)
public class TestClass_DS_DEMO {
    
    public static TestClass_A_Utility test_ut = new TestClass_A_Utility();
    
    public static Utility ut = new Utility();
    
    @testSetup 
    static void setup() {
        // Load DS_DATA into system
        TestClassData_DS_DATA importData = new TestClassData_DS_DATA();      
    }
    
    // Test baseline controller 
    static TestMethod void Test_Baseline_Controller() {
        
        Client__c client = test_ut.createClient();
        
        // Get summaryId for Url
        String summaryId = test_ut.getClientSummaryId(client.id, 'DS_DEMO', '0');
        
        String cimi = ut.urlEncode('c='+client.id+'&summary='+summaryId);
        
        ApexPages.currentPage().getParameters().put('cimi',cimi);
        
        DS_Background_Family_Info_B__c obj = new DS_Background_Family_Info_B__c();    
        obj.STATUS_DEMO__c = 'Complete';
        obj.client__c = client.id;  
        obj.RREF__c= true;
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);    
        DS_DEMO_Controller controller = new DS_DEMO_Controller(sc);        
        
        List<SelectOption> q4 = controller.getQ4Items();
        List<SelectOption> hisplat = controller.getHispLatItems();
        List<SelectOption> q14 = controller.getQ14Items();
        List<SelectOption> milself = controller.getMilSelfItems();
        List<SelectOption> milfam = controller.getMilFamItems();
        List<SelectOption> overall = controller.getOverAllItems();
        List<SelectOption> geniden = controller.getGenIdenItems();
        List<SelectOption> orient = controller.getOrientItems();
        
        controller.save();
        controller.cancel();
     
    }
    
    static TestMethod void skipTest() {
    
        //create test client 
        Client__c client = test_ut.createClientSummary();
        String cimi= ut.urlEncode('c='+client.id);
        ApexPages.currentPage().getParameters().put('cimi',cimi);       
        
        DS_Background_Family_Info_B__c obj = new DS_Background_Family_Info_B__c();
        
        obj.client__c = client.id; 
        
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        
        obj.RWHITE__c=true;
        
        //skipLogic determining values
        
        String CUREPI='0'; 
        Boolean BINFOTHR=true;
        String BGUARD='98';
        Boolean BREFSRO=true;
        String BETHNIC='1';
        Boolean BETHNICHO=true; 
        String BUSBORN='0'; 
        String BPUSBORN='0'; 
        String BSIBLING='1'; 
        Boolean BTREATO=true;
        Boolean BPROTHNW=true; 
        String BTRT='1'; 
        Boolean BTRTOTHR=true; 
        String BHSR='1';
        String BDEVCON='1';
        Boolean BDEVOTHR=true; 
        String BDVTR='1';
        Boolean BDVTROTR=true; 
        String BDVSR='1'; 
        Boolean BRHCO=true; 
        
        insert obj;
        
        //assert not equals. if test object value does not equal the test condition variable, skiplogic is not triggered, opposite message displayed
        System.assertNotEquals(obj.CUREPI__c, CUREPI, 'This is the first visit.');//3
        System.assertNotEquals(obj.BINFOTHR__c,BINFOTHR,'Information NOT collected from other source.');//4
        System.assertNotEquals(obj.BGUARD__c,BGUARD ,'Standard legal guardian.');//5
        System.assertNotEquals(obj.BREFSRO__c,BREFSRO ,'Not referred by other means.');//6
        System.assertNotEquals(obj.BTREATO__c,BTREATO ,'Standard services intended');//7
        //  System.assertNotEquals(obj.BETHNIC__c,BETHNIC ,'Child is not Hispanic');//1
        //  System.assertNotEquals(obj.BETHNICHO__c,BETHNICHO  ,'Standard Hispanic or Latino ethnic group.');//1a
        System.assertNotEquals(obj.BUSBORN__c,BUSBORN  ,'Born in the US');//3
        System.assertNotEquals(obj.BPUSBORN__c,BPUSBORN ,'Parent born in the US');//4
        System.assertNotEquals(obj.BSIBLING__c,BSIBLING  ,'No siblings in data set');//5
        System.assertNotEquals(obj.BRHCO__c,BRHCO  ,'Standard regular health provider');//11
        System.assertNotEquals(obj.BPROTHNW__c,BPROTHNW ,'Standard current healthcare provider');//12
        
    }
    
    static TestMethod void specifyTest() {
    
        //create test client 
        Client__c client = test_ut.createClientSummary();
        String cimi= ut.urlEncode('c='+client.id);
        ApexPages.currentPage().getParameters().put('cimi',cimi);       
        
        DS_Background_Family_Info_B__c obj = new DS_Background_Family_Info_B__c();
        
        obj.client__c = client.id; 
        
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        
        String CUREPVS = 'null';
        String BINFOSP = 'null';
        String BGUARDSP = 'null';
        String BREFSOSP = 'null';
        String BTREATOSP = 'null';
        String CTYBORN = 'null';
        String BPUSBORNSP = 'null';
        Integer BSIBNUM = 0;
        String BRHCOSP = 'null';
        String BPROSPNW = 'null';
                
        System.assertNotEquals(obj.CUREPVS__c,CUREPVS , 'There have/has been' + obj.CUREPVS__c+' visits.');
        System.assertNotEquals(obj.BINFOSP__c,BINFOSP, 'Information source is'+obj.BINFOSP__c+'.');
        System.assertNotEquals(obj.BGUARDSP__c,BGUARDSP ,'The guardianship is specified as '+obj.BGUARDSP__c+'.');
        System.assertNotEquals(obj.BREFSOSP__c,BREFSOSP , 'Referred by'+obj.BREFSOSP__c+'.');
        System.assertNotEquals(obj.BTREATOSP__c,BTREATOSP , 'Service of '+obj.BTREATOSP__c+' intended.');
        System.assertNotEquals(obj.CTYBORN__c,CTYBORN , 'Child was born in '+ obj.CTYBORN__c+'.');
        System.assertNotEquals(obj.BPUSBORNSP__c,BPUSBORNSP , 'Parent was born in '+obj.BPUSBORNSP__c+'.');
        System.assertNotEquals(obj.BSIBNUM__c,BSIBNUM , 'There is/are '+obj.BSIBNUM__c+' sibling(s).');
        System.assertNotEquals(obj.BRHCOSP__c, BRHCOSP, 'Regular health provider is '+obj.BRHCOSP__c+'.');
        System.assertNotEquals(obj.BPROSPNW__c,BPROSPNW , 'Current health provider is'+obj.BPROSPNW__c+'.');
    }
    
}