src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>AGE__c</fullName>
        <description>Client&apos;s age as entered in the System Screening</description>
        <label>Age</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DOB1__c</fullName>
        <label>Date of birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DOB2__c</fullName>
        <label>DOB2</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GENDER__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t know/ Information not available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>INIT__c</fullName>
        <label>INITIALS</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DS DATA Page</label>
        <referenceTo>DS_DATA__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Client Summary</label>
    <nameField>
        <displayFormat>summary-{000000}</displayFormat>
        <label>Client Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DS_DATA__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <picklist>
            <picklistValues>
                <fullName>DS_BIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_BSLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CANSTR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CLINEVAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DEMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FAPGAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FOLLOWUPINFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INSDOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_MILITARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NCTSNTREAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_POST_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_REFIMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_04_10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_S_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SERVREC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_YCINDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRABUSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRACCIDENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRBEREAVE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Boy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Girl</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Section</label>
        <type>Checkbox</type>
    </fields>
    <label>DS DATA</label>
    <nameField>
        <displayFormat>DS DATA - {000000}</displayFormat>
        <label>DS DATA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS DATA</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DS_SDQ_PSI_CDI_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOASDOP__c</fullName>
        <description>Parent 11-17: Date of Administration</description>
        <label>BDOASDOP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BMETSDOP__c</fullName>
        <description>Parent 11-17 method of administration</description>
        <label>BMETSDOP</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPAFRA__c</fullName>
        <description>Parent 4-10: Many fears, easily scared</description>
        <label>BSDPAFRA</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPBEH__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Behavioral Difficulties Scoring, Parent4-10</description>
        <label>BSDPBEH</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSDPCLIN__c</fullName>
        <description>Parent 4-10: Nervous in new situations, easily loses confidence</description>
        <label>BSDPCLIN</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPEMO__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Emotional Distress Scoring, Parent 11-17</description>
        <label>BSDPEMO</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSDPFIGH__c</fullName>
        <description>Parent 11-17: Often fights with other children or bullies them</description>
        <label>BSDPFIGH</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPLIES__c</fullName>
        <description>Parent 4-10: Often lies or cheats</description>
        <label>BSDPLIES</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPOBEY__c</fullName>
        <description>Parent 4-10: Generally well behaved, usually does what adults request</description>
        <label>BSDPOBEY</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPSOMA__c</fullName>
        <description>Parent 4-10: Often complains of headaches, stomach-aches or sickness</description>
        <label>BSDPSOMA</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPSTEA__c</fullName>
        <description>Parent 4-10: Steals from home, school or elsewhere</description>
        <label>BSDPSTEA</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPTANT__c</fullName>
        <description>Parent 4-10: Often loses temper</description>
        <label>BSDPTANT</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPUNHA__c</fullName>
        <description>Parent 4-10: Often unhappy, depressed or tearful</description>
        <label>BSDPUNHA</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPWORR__c</fullName>
        <description>Parent 4-10: Many worries or often seems worried</description>
        <label>BSDPWORR</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS SDQ PSI CDI B</relationshipLabel>
        <relationshipName>DS_SDQ_PSI_CDI_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FORM__c</fullName>
        <label>FORM</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>SECTION</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>DS SDQ PSI CDI B</label>
    <nameField>
        <label>DS SDQ PSI CDI B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS SDQ PSI CDI B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestClass_DS_SDQ_P_O_B.cls
@istest(SeeAllData=false)
public class TestClass_DS_SDQ_P_O_B {
static TestMethod void controllerTest() {
    Utility ut = new Utility();
    TestClass_Utility test_ut = new TestClass_Utility();
    
        TestClassData_DS_SDQ_PSI_CDI_Form_Info formInfo = new TestClassData_DS_SDQ_PSI_CDI_Form_Info();

    Client__c client = new Client__c();
    
     Date dob = date.valueOf('2000-10-5 12:20:20');
    client.INIT__c = 'WFW';
    client.DOB1__c = dob;
    client.DOB2__c = dob;
    client.AGE__c = Integer.valueOf(dob.daysBetween(date.today())/365);
    client.GENDER__c = 'Male';
    
    client = test_ut.createCustomClientSummary(client);    
    
    List<Client_Summary__c> su = [Select id, section__c FROM Client_Summary__c WHERE client__c =: client.id];

    system.debug(su);
    
        Client_Summary__c summary = [SELECT id 
                                   FROM Client_Summary__c
                                  WHERE Page__r.Form__c = 'DS_SDQ_P_11_17'
                                    AND SECTION__c = '0'
                                    AND Client__c = : client.id]; 
                                   system.debug(summary);
String cimi= ut.urlEncode('c='+client.id+'&summary='+summary.id);
ApexPages.currentPage().getParameters().put('cimi',cimi);

DS_SDQ_PSI_CDI_B__c obj = new DS_SDQ_PSI_CDI_B__c();
obj.client__c = client.id;
    
    ApexPages.StandardController sc = new ApexPages.StandardController(obj); 
    DS_SDQ_P_O_B_Controller controller = new DS_SDQ_P_O_B_Controller(sc);  
      
    List<SelectOption> Overall= controller.getOverallItems();
    List<SelectOption> HowLong= controller.getHowLongItems();
    List<SelectOption> Upset= controller.getUpsetItems();
    List<SelectOption> Difficult= controller.getDifficultItems();
    List<SelectOption> BMET= controller.getBMETItems();
    
    String clientInfo = controller.getClientInfo();
    
 controller.saveviewOld();
     controller.save();
   controller.cancel();
    
  }
 static TestMethod Client__c testWvals(){ 
  
    TestClass_Utility test_ut = new TestClass_Utility();
    TestClassData_DS_SDQ_PSI_CDI_Form_Info formInfo = new TestClassData_DS_SDQ_PSI_CDI_Form_Info();  
    Client__c client = test_ut.createClientSummary();
    DS_SDQ_PSI_CDI_B__c obj = new DS_SDQ_PSI_CDI_B__c();
    obj.Client__c = client.id;
    obj.BMETSDOP__c = '1';
    obj.BDOASDOP__c=date.parse('10/30/2014');  
    obj.client__c = client.id;
    obj.Form__c = 'DS_SDQ_P_11_17';

    obj.BSDPSOMA__c= '1';
    obj.BSDPWORR__c= '1';
    obj.BSDPUNHA__c= '1';
    obj.BSDPCLIN__c= '1';
    obj.BSDPAFRA__c= '1';
    obj.BSDPEMO__c= 1;
    obj.BSDPTANT__c= '1';
    obj.BSDPOBEY__c= '1';
    obj.BSDPFIGH__c= '1';
    obj.BSDPLIES__c= '1';
    obj.BSDPSTEA__c= '1';
    obj.BSDPBEH__c= 1;
    obj.BSDPREST__c= '1';
    obj.BSDPFIDG__c= '1';
    obj.BSDPDIST__c= '1';
    obj.BSDPREFL__c= '1';
    obj.BSDPATTE__c= '1';
    obj.BSDPHYP__c= 1;
    obj.BSDPLONE__c= '1';
    obj.BSDPFRIE__c= '1';
    obj.BSDPPOPU__c= '1';
    obj.BSDPBULL__c= '1';
    obj.BSDPOLDB__c= '1';
    obj.BSDPOTC__c= 1;
    obj.BSDPCONS__c= '1';
    obj.BSDPSHAR__c= '1';
    obj.BSDPCARI__c= '1';
    obj.BSDPKIND__c= '1';
    obj.BSDPHELP__c= '1';
    obj.BSDPKHB__c= 1;
    obj.BSDPIMPF__c= '1';
    obj.BSDPIMPH__c= '1';
    obj.BSDPIMPC__c= '1';
    obj.BSDPUPSET__c= '1';
    obj.BSDPIMPL__c= '1';
    obj.BSDPDCL__c= 1;
    obj.BSDPTOT__c= 1; 
    insert obj;
    return client;
  } 
}