src/objects/Client_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DS DATA Page</label>
        <referenceTo>DS_DATA__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Client Summary</label>
    <nameField>
        <displayFormat>summary-{000000}</displayFormat>
        <label>Client Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DS_DATA__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <picklist>
            <picklistValues>
                <fullName>DS_BIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_BSLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CANSTR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CLINEVAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DEMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FAPGAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FOLLOWUPINFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INSDOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_MILITARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NCTSNTREAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_POST_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_REFIMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_04_10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_S_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SERVREC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_YCINDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRABUSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRACCIDENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRBEREAVE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Section</label>
        <type>Checkbox</type>
    </fields>
    <label>DS DATA</label>
    <nameField>
        <displayFormat>DS DATA - {000000}</displayFormat>
        <label>DS DATA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS DATA</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DS_PTSD_CA_B__c.object
<CustomObject>
    <fields>
        <fullName>BMETPTSD__c</fullName>
        <label>BMETPTSD</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPTSV10__c</fullName>
        <label>BPTSV10</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPTSV11__c</fullName>
        <label>BPTSV11</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPTSV12__c</fullName>
        <label>BPTSV12</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPTSV13__c</fullName>
        <label>BPTSV13</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPTSV1__c</fullName>
        <label>BPTSV1</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPTSV2__c</fullName>
        <label>BPTSV2</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPTSV3__c</fullName>
        <label>BPTSV3</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPTSV4__c</fullName>
        <label>BPTSV4</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPTSV6__c</fullName>
        <label>BPTSV6</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPTSV7__c</fullName>
        <label>BPTSV7</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPTSV8__c</fullName>
        <label>BPTSV8</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPTSV9__c</fullName>
        <label>BPTSV9</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS PTSD CA B</relationshipLabel>
        <relationshipName>DS_PTSD_CA_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>SECTION</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STATUS_PTSD_CA__c</fullName>
        <label>STATUS PTSD CA</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DS PTSD CA B</label>
    <nameField>
        <label>DS PTSD CA B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS PTSD CA B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestClass_DS_PTSD_CA.cls
@isTest (SeeAllData=false)
private class TestClass_DS_PTSD_CA {

  static TestMethod void controllerBaselineTest() {
  
    Utility ut = new Utility();

    TestClass_Utility test_ut = new TestClass_Utility();
    
    TestClassData_DS_PTSD_Form_Info formInfo = new TestClassData_DS_PTSD_Form_Info();
    
    Client__c client = test_ut.createClientSummary();

    List<Client_Summary__c> su = [Select id, section__c FROM Client_Summary__c];

    Client_Summary__c summary = [SELECT id 
                                   FROM Client_Summary__c
                                  WHERE Page__r.Form__c = 'DS_PTSD_CA'
                                    AND SECTION__c = '0'
                                    AND Client__c = : client.id]; 
    
    String cimi = ut.urlEncode('c='+client.id+'&summary='+summary.id);
    
    ApexPages.currentPage().getParameters().put('cimi', cimi);
    
    DS_PTSD_CA_B__c ptsd = new DS_PTSD_CA_B__c();
    
    ptsd.client__c = client.id;
    ptsd.BMETPTSD__c = '1';
   // ptsd.BPTSDATE__c = System.today();//Date.today();
    
    ApexPages.StandardController sc = new ApexPages.StandardController(ptsd);  
    DS_PTSD_CA_Controller controller = new DS_PTSD_CA_Controller(sc); 

    List<SelectOption> radio = controller.getRadioItems();
    List<SelectOption> radioNYU = controller.getNYUItems();
    List<SelectOption> radioYesNo = controller.getRadioYesNo();
    List<SelectOption> met = controller.getBMETItems();

    String clientInfo = controller.getClientInfo();

    controller.save();
    controller.saveViewReport();
    controller.cancel();
  
    // Update record

    /*ptsd = [SELECT id FROM DS_PTSD_CA_B__c WHERE client__c =: client.id];
    sc = new ApexPages.StandardController(ptsd);
    controller = new DS_PTSD_CA_Controller(sc);
    ApexPages.currentPage().getParameters().put('cimi', cimi);
    //controller.save();
    
    ptsd.STATUS_PTSD_CA__c = 'Complete'; 
   
    controller.save();*/

    
  }

  static TestMethod Client__c Test0_BaselineTestInsertWithMoreeThan3Blank() {

    TestClass_Utility test_ut = new TestClass_Utility();

    TestClassData_DS_PTSD_Form_Info formInfo = new TestClassData_DS_PTSD_Form_Info();

    Client__c client = test_ut.createClientSummary();

    DS_PTSD_CA_B__c obj = new DS_PTSD_CA_B__c();

    obj.client__c = client.id;

    obj.BMETPTSD__c = '1';
    obj.FORM__c = 'DS_PTSD_CA';

    obj.BPTSV1__c  = obj.BPTSV2__c  = obj.BPTSV3__c  = obj.BPTSV4__c  = '1';
    obj.BPTSV6__c  = obj.BPTSV7__c  = obj.BPTSV8__c  = obj.BPTSV9__c  = obj.BPTSV10__c = '4';
    obj.BPTSV11__c = obj.BPTSV12__c = obj.BPTSV13__c = obj.BPTSV14__c = obj.BPTSV15__c = '4';
    obj.BPTSV16__c = obj.BPTSV17__c = obj.BPTSV18__c = obj.BPTSV19__c = obj.BPTSV20__c = '2';
    obj.BPTSV21__c = obj.BPTSV22__c = obj.BPTSV23__c = obj.BPTSV24__c = obj.BPTSV25__c = '3';
    obj.BPTSV26__c = obj.BPTSV27__c = obj.BPTSV28__c = obj.BPTSV29__c = obj.BPTSV30__c = '1';

    insert obj;

    return client;

  }

  static TestMethod Client__c Test1_BaselineTestInsertWith2Blank() {

    TestClass_Utility test_ut = new TestClass_Utility();

    TestClassData_DS_PTSD_Form_Info formInfo = new TestClassData_DS_PTSD_Form_Info();

    Client__c client = test_ut.createClientSummary();

    DS_PTSD_CA_B__c obj = new DS_PTSD_CA_B__c();

    obj.client__c = client.id;

    obj.BMETPTSD__c = '1';
    obj.FORM__c = 'DS_PTSD_CA';

    obj.BPTSV1__c  = obj.BPTSV2__c  = obj.BPTSV3__c  = obj.BPTSV4__c  = obj.BPTSV5__c  = '2';
    obj.BPTSV6__c  = obj.BPTSV7__c  = obj.BPTSV8__c  = obj.BPTSV9__c  = obj.BPTSV10__c = '4';
    obj.BPTSV11__c = obj.BPTSV12__c = obj.BPTSV13__c = obj.BPTSV14__c = obj.BPTSV15__c = '4';
    obj.BPTSV16__c = obj.BPTSV17__c = obj.BPTSV18__c = obj.BPTSV19__c = obj.BPTSV20__c = '2';
    obj.BPTSV21__c = obj.BPTSV22__c = obj.BPTSV23__c = obj.BPTSV24__c = obj.BPTSV25__c = '3';
    obj.BPTSV26__c = obj.BPTSV27__c = obj.BPTSV28__c = obj.BPTSV29__c = obj.BPTSV30__c = '2';

    insert obj;

    return client;

  }

}