src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>AGE__c</fullName>
        <description>Client&apos;s age as entered in the System Screening</description>
        <label>Age</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BENRCDS__c</fullName>
        <label>BENRCDS</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPREVCA__c</fullName>
        <label>BPREVCA</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BPREVEPI__c</fullName>
        <label>BPREVEPI</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Clinician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinician ID</label>
        <referenceTo>Clinician__c</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOB1__c</fullName>
        <label>Date of birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DOB2__c</fullName>
        <label>DOB2</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GENDER__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t know/ Information not available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>INIT__c</fullName>
        <label>INITIALS</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SITEID__c</fullName>
        <label>SITEID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Clinician__c.object
<CustomObject>
    <label>Clinician</label>
    <nameField>
        <label>Clinician ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinicians</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Counter__c.object
<CustomObject>
    <fields>
        <fullName>Counter__c</fullName>
        <defaultValue>1</defaultValue>
        <description>To count sub-center</description>
        <label>Counter (Sub-center)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>0: Main
1: Sub
2: Clinician</description>
        <label>Type</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Counter</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClientController.cls
/*Page Description:
 *  Controller Class for Clients
 * Last Updated on:
 *  7/17/2014
 * Update Purpose:
 *      
 * Programmer:
 *  
 */
public with sharing class ClientController {
    
    String ID = Apexpages.currentPage().getParameters().get('id');
    
    public Integer roleType {get; set;}
    
    public Boolean isNotClinician {get; set;}
    
    public String title {get; set;}
    public String subtitle {get; set;}
    
    public Client__c client {get; set;}

    public RoleController roleManager = new RoleController();
    
    public ClientController(ApexPages.StandardController controller) {
        
        title = 'Create Client';
        subtitle = 'Client';
        
        Counter__c roleInfo = roleManager.RoleType(UserInfo.getUserRoleId());
        
        roleType = Integer.valueof(roleInfo.Type__c);
        
        if(roleType != 3) isNotClinician = True;
    
        if(ID != null) {
         
            client = [SELECT AGE__c, BENRCDS__c, BPREVCA__c, BPREVEPI__c, Name, 
                             Clinician__c, CreatedById, CreatedDate, DOB1__c, DOB2__c, 
                             IsDeleted, GENDER__c, INIT__c, Id, SITEID__c 
                        FROM Client__c 
                       WHERE id = :Apexpages.currentPage().getParameters().get('id')]; 
                       
            title = 'Client Edit';
            subtitle = '(' + client.Name + ') ' + client.INIT__c;
                       
        }
        
    }
    
    
    
    /*public Boolean getisClient() {
        
        Integer count = findRoleAdmin(UserInfo.getUserRoleId(), 0);
        
        System.debug(count);
        
        if(count < 3) return True;
        else return False;
    }
    
    public Integer findRoleAdmin(ID roleID, Integer count) {
        
        UserRole role = [SELECT Name, ParentRoleId FROM UserRole WHERE Id = :roleID];
        
        if(role.ParentRoleId == null) return count;
        else {
            count++;
            return findRoleAdmin(role.ParentRoleId, count);
        }
    }*/
    
    /*public PageReference save() {
        if(ID == null) {
            insert client;
        }
        else {
            update client;
        }
        
        PageReference acctPage = new ApexPages.StandardController(client).view();
        acctPage.setRedirect(true);
        return acctPage;
        
    }*/

    
    
}