src/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DS_GTRAUMA__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS GTRAUMA</relationshipLabel>
        <relationshipName>DS_General_Traumas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GT10R__c</fullName>
        <label>GT10R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT11R__c</fullName>
        <label>GT11R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT12R__c</fullName>
        <label>GT12R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT13R__c</fullName>
        <label>GT13R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT14R__c</fullName>
        <label>GT14R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT15R__c</fullName>
        <label>GT15R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT16R__c</fullName>
        <label>GT16R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT17R__c</fullName>
        <label>GT17R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT18R__c</fullName>
        <label>GT18R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT19R__c</fullName>
        <label>GT19R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT1R__c</fullName>
        <label>GT1R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT20RA0__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GT20RA0</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GT20RA1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GT20RA1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GT20R__c</fullName>
        <label>GT20R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT21R__c</fullName>
        <description>Has the child experienced School Violence (not reported elsewhere)?</description>
        <label>GT21R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT22R__c</fullName>
        <description>Bullying</description>
        <label>GT22R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT23R__c</fullName>
        <description>Other Trauma</description>
        <label>GT23R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT2R__c</fullName>
        <label>GT2R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT3R__c</fullName>
        <label>GT3R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT4R__c</fullName>
        <label>GT4R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT5R__c</fullName>
        <label>GT5R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT6R__c</fullName>
        <label>GT6R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT7R__c</fullName>
        <label>GT7R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT8RA0__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GT8RA0</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GT8RA1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GT8RA1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GT8RAU__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GT8RAU</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GT8R__c</fullName>
        <label>GT8R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GT9R__c</fullName>
        <label>GT9R</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DS GTRAUMA</label>
    <nameField>
        <displayFormat>GTRA-{YYYY}{MM}-{0}</displayFormat>
        <label>General Trauma Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS GTRAUMA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestClass_DS_GTRAUMA.cls
@isTest (SeeAllData=false)
private class TestClass_DS_GTRAUMA {

  static TestMethod void controllerTest() {

    Utility ut = new Utility();
    TestClass_Utility test_ut = new TestClass_Utility();

    Client__c client = test_ut.createClientSummary();
    String cimi = ut.urlEncode('c='+client.id);//+'&summary='+summary.id);
    ApexPages.currentPage().getParameters().put('cimi', cimi);
    
    DS_GTRAUMA__c obj = new DS_GTRAUMA__c();    
    obj.client__c = client.id;
    obj.GT1R__c = '1';
    obj.GT2R__c = '1';
    obj.GT3R__c = '1';
    obj.GT4R__c = '1';
    obj.GT5R__c = '1';
    obj.GT6R__c = '1';
    obj.GT7R__c = '1';
    obj.GT8R__c = '1';
    obj.GT9R__c = '1';
    obj.GT10R__c = '1';
    obj.GT11R__c = '1';
    obj.GT12R__c = '1';
    obj.GT13R__c = '1';
    obj.GT14R__c = '1';
    obj.GT15R__c = '1';
    obj.GT16R__c = '1';
    obj.GT17R__c = '1';
    obj.GT18R__c = '1';
    obj.GT19R__c = '1';
    obj.GT20R__c = '1';
    obj.GT21R__c = '1';
    obj.GT22R__c = '1';
    obj.GT23R__c = '1';
    obj.GT8RA0__c = true;
    obj.GT20RA0__c = false;
    ApexPages.StandardController sc = new ApexPages.StandardController(obj);
    DS_GTRAUMA_Controller controller = new DS_GTRAUMA_Controller(sc);
    
    List<SelectOption> radio = controller.getTraumaType();
    List<SelectOption> radioYesNo = controller.getPrimaryType();
    //String clientInfo = controller.getClientInfo();
    
    
    System.assertEquals(obj.client__c, client.id, 'There is a problem with the clieni id.');
    System.assertEquals(obj.GT8R__c, '1', 'There is a problem with the variable GT8R.');
    System.assertEquals(obj.GT20R__c, '1', 'There is a problem with the variable GT20R.');
    System.assertEquals(obj.GT8RA0__c, true, 'There is a problem with the variable GT8RA0.');
    System.assertEquals(obj.GT20RA0__c, false, 'There is a problem with the variable GT20RA0.');
    
    controller.rowList();



    controller.save();
    controller.cancel();

    insert obj;
    // Update general trauma
        obj = [SELECT id FROM DS_GTRAUMA__c WHERE client__c =: client.id Limit 1];
   /* obj.client__c = client.id;//?
    obj.GT8R__c = '1';
    obj.GT20R__c = '1';
    obj.GT8RA0__c = true;*/
    obj.GT20RA0__c = true;
    sc = new ApexPages.StandardController(obj);
    controller = new DS_GTRAUMA_Controller(sc);    
    ApexPages.currentPage().getParameters().put('cimi', cimi);


    controller.save();
    //String nextPage = controller.save().getUrl();
    
  }

  static TestMethod DS_GTRAUMA__c Test0_insertUpdateGeneralTrauma() {

    TestClass_Utility test_ut = new TestClass_Utility();

    Client__c client = test_ut.createClientSummary();

    DS_GTRAUMA__c obj = new DS_GTRAUMA__c();

    obj.client__c = client.id;
    
    obj.GT1R__c = '1';
    obj.GT2R__c = '1';
    obj.GT3R__c = '1';
    obj.GT4R__c = '1';
    obj.GT5R__c = '1';
    obj.GT6R__c = '1';
    obj.GT7R__c = '1';
    obj.GT8R__c = '1';
    obj.GT9R__c = '1';
    obj.GT10R__c = '1';
    obj.GT11R__c = '1';
    obj.GT12R__c = '1';
    obj.GT13R__c = '1';
    obj.GT14R__c = '1';
    obj.GT15R__c = '1';
    obj.GT16R__c = '1';
    obj.GT17R__c = '1';
    obj.GT18R__c = '1';
    obj.GT19R__c = '1';
    obj.GT20R__c = '0';
    obj.GT21R__c = '1';
    obj.GT22R__c = '1';
    obj.GT23R__c = '1';

    obj.GT8RA0__c = true;
    obj.GT20RA0__c = true;

    obj.GT8RA1__c = false;

    obj.GT8RAU__c = false;

    insert obj;

    return obj;
  }

  static TestMethod void Test1_updateGeneralTrauma() {

    DS_GTRAUMA__c obj = Test0_insertUpdateGeneralTrauma();

    obj.GT1R__c = '1';
    obj.GT2R__c = '1';
    obj.GT3R__c = '1';
    obj.GT4R__c = '1';
    obj.GT5R__c = '1';
    obj.GT6R__c = '1';
    obj.GT7R__c = '1';
    obj.GT8R__c = '1';
    obj.GT9R__c = '1';
    obj.GT10R__c = '1';
    obj.GT11R__c = '1';
    obj.GT12R__c = '1';
    obj.GT13R__c = '1';
    obj.GT14R__c = '1';
    obj.GT15R__c = '1';
    obj.GT16R__c = '1';
    obj.GT17R__c = '1';
    obj.GT18R__c = '1';
    obj.GT19R__c = '1';
    obj.GT20R__c = '0';
    obj.GT21R__c = '1';
    obj.GT22R__c = '1';
    obj.GT23R__c = '1';

    obj.GT8RA0__c = true;
    obj.GT20RA0__c = true;

    obj.GT8RA1__c = true;
    obj.GT20RA1__c = true;

    obj.GT8RAU__c = true;

    update obj;

  }

  static TestMethod List<DS_GTRAUMA__c> Test3_bulkInsertGeneralTrauma() {

    TestClass_Utility test_ut = new TestClass_Utility();

    Client__c client = test_ut.createClientSummary();

    ///begin bulk insert
    System.debug('Inserting 200 records... (bulk validation)');

    List<DS_GTRAUMA__c> bulkObj = new List<DS_GTRAUMA__c>();

    for (Integer i=0;i<200;i++) {

      bulkObj.add(new DS_GTRAUMA__c(client__c = client.id,
                  
    GT1R__c = '1',GT2R__c = '1',GT3R__c = '1',GT4R__c = '1',
    GT5R__c = '1',GT6R__c = '1',GT7R__c = '1',GT8R__c = '1',
    GT9R__c = '1',GT10R__c = '1',GT11R__c = '1',GT12R__c = '1',
    GT13R__c = '1',GT14R__c = '1',GT15R__c = '1',GT16R__c = '1',
    GT17R__c = '1',GT18R__c = '1',GT19R__c = '1',GT20R__c = '1',
    GT21R__c = '1',GT22R__c = '1',GT23R__c = '1'
      
      ));

    }

    insert bulkObj;

    return bulkobj;

  }

  static TestMethod void Test4_bulkUpdateGeneralTrauma() {

    List<DS_GTRAUMA__c> bulkObj = Test3_bulkInsertGeneralTrauma();

    List<DS_GTRAUMA__c> updateBulkObj = new List<DS_GTRAUMA__c>();

    for(DS_GTRAUMA__c obj : bulkobj) {

    obj.GT1R__c = '1';
    obj.GT2R__c = '1';
    obj.GT3R__c = '1';
    obj.GT4R__c = '1';
    obj.GT5R__c = '1';
    obj.GT6R__c = '1';
    obj.GT7R__c = '1';
    obj.GT8R__c = '1';
    obj.GT9R__c = '1';
    obj.GT10R__c = '1';
    obj.GT11R__c = '1';
    obj.GT12R__c = '1';
    obj.GT13R__c = '1';
    obj.GT14R__c = '1';
    obj.GT15R__c = '1';
    obj.GT16R__c = '1';
    obj.GT17R__c = '1';
    obj.GT18R__c = '1';
    obj.GT19R__c = '1';
    obj.GT20R__c = '0';
    obj.GT21R__c = '1';
    obj.GT22R__c = '1';
    obj.GT23R__c = '1';

      obj.GT8RA0__c = true;
      obj.GT20RA0__c = true;

      obj.GT8RA1__c = true;
      obj.GT20RA1__c = true;

      obj.GT8RAU__c = true;

      updateBulkObj.add(obj);

    }

    update updateBulkObj;

  }
  


}