src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>AGE__c</fullName>
        <description>Client&apos;s age as entered in the System Screening</description>
        <label>Age</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DOB1__c</fullName>
        <label>Date of birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>INIT__c</fullName>
        <label>INITIALS</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Client Summary</label>
    <nameField>
        <displayFormat>summary-{000000}</displayFormat>
        <label>Client Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DS_DATA__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data_Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <picklist>
            <picklistValues>
                <fullName>DS_BIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_BSLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CANSTR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CLINEVAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DEMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FAPGAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FOLLOWUPINFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INSDOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_MILITARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NCTSNTREAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_POST_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_REFIMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_04_10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_S_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SERVREC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_YCINDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRABUSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRACCIDENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRBEREAVE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DS DATA</label>
    <nameField>
        <displayFormat>DS DATA - {000000}</displayFormat>
        <label>DS DATA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS DATA</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DS_GTRAUMA__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS GTRAUMA</relationshipLabel>
        <relationshipName>DS_General_Traumas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS GTRAUMA</label>
    <nameField>
        <displayFormat>GTRA-{YYYY}{MM}-{0}</displayFormat>
        <label>General Trauma Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS GTRAUMA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DS_GTRAUMA_Controller.cls
/*Page Description:
 *  Controller for VisualForce page GTRAUMA
 * Last Updated on:
 *  7/17/2014
 * Update Purpose:
 *      
 * Programmer:
 *  
 */
public with sharing class DS_GTRAUMA_Controller {

  Utility ut = new Utility();

  Map<String, String> parameter = ut.urlDecode(Apexpages.currentPage().getParameters().get('cimi'));

  public List<Item> rows {get; set;}
  public List<String> ageTitle {  get; set; }

  public List<String> ageNum { get; set; } 

  public DS_GTRAUMA__c GTRAUMA { get; set; }

  public Client__c client { get; set; }

  public Client_Summary__c summaryInfo { get; set; }

  public Integer clientCurrentAge { get; set; } 
  
  String cID;
  
  String summaryID;
  
  Boolean edit = FALSE;
  
  public String subtitle {get; set;}

  public SkipLogic skip = new SkipLogic();
      
  public class Item {
      
    public String num { get; set; }
    public String trauma { get; set; }
    public String subtitle { get; set; }
    public String exp { get; set; }
    public List<String> ages { get; set; }
    
    
    public Item(String num, String trauma, String exp, List<String> ages, String subtitle) {
      this.num = num;
      this.trauma = trauma;
      this.exp = exp;
      this.ages = ages;
      this.subtitle = subtitle;
      
    }
  
  }
    
  public DS_GTRAUMA_Controller(ApexPages.StandardController controller) {
      
    cID = parameter.get('c');

    summaryID = parameter.get('summary');

    ageNum = new List<String>{'0','1','2','3','4','5','6','7','8','9','10',
                              '11','12','13','14','15','16','17','18'};
    
    String gtFields = ut.getFields('DS_GTRAUMA__c');
    
    List<DS_GTRAUMA__c> GT = 
      Database.query('SELECT ' + gtFields + ', Client__r.Name, Client__r.INIT__c' +  
                     '  FROM DS_GTRAUMA__c ' +
                     ' WHERE Client__c = \''+ cID + '\'');
    
    client = [SELECT Name, INIT__c, AGE__c, DOB1__c FROM Client__c WHERE id =: cID];
    
    clientCurrentAge = Integer.valueOf(date.valueof(client.DOB1__c).daysBetween(Date.today()) / 365);

    subtitle = '(' + client.Name + ') ' + client.INIT__c;
    
                                                                                    
    if(GT.size() == 0){
      GTRAUMA = new DS_GTRAUMA__c(client__c = cID);
      GTRAUMA.FORM__c = 'DS_GTRAUMA';
    }
    else { 
      GTRAUMA = GT.get(0);
      GTRAUMA.FORM__c = 'DS_GTRAUMA';
      edit = TRUE;
    }           

    rows = new List<Item>();
    
    ageTitle = new List<String>();
    
    for(Integer i = 0; i<19; i++)
      ageTitle.add(String.valueof(i));
    
    agetitle.add('Unknown'); 
    
    this.rowList();
  }

  public String getClientInfo() { return ut.clientSection(cID,SummaryID); }  
    
  public List<SelectOption> getTraumaType() {
    List<SelectOption> options = new List<SelectOption>();
    options.add(new SelectOption('0','No'));
    options.add(new SelectOption('1','Yes'));
    options.add(new SelectOption('2','Suspected'));
    options.add(new SelectOption('99','Unknown'));
    return options;
  }
    
  public List<SelectOption> getPrimaryType() {
      
    List<SelectOption> options = new List<SelectOption>();
    
    options.add(new SelectOption('','--None--'));
    
    for(Item i : rows)
      options.add(new SelectOption(i.num,i.trauma));
    
    return options;
      
  }
  
  public void rowList() {
      
    List<DS_DATA__c> info = [SELECT Content__c, Note__c, Weight__c 
                                    FROM DS_DATA__c 
                                   WHERE Category__c = 'TD'
                                     AND Data_Type__c = 'DS_Form_Info' 
                                ORDER BY weight__c];

    for(DS_DATA__c i : info) {
    
      String count = string.valueof(i.Weight__c);
      
      String subtitle = (i.Note__c == null) ? '' : '<small>' + i.Note__c + '</small>'; 
                  
      String trauma = i.Content__c;
      
      List<String> ages = new List<String>();
      
      for(Integer j = 0; j<19; j++) 
          ages.add('GT'+count+'RA'+j+'__c');
      
      ages.add('GT'+count+'RAU__c');
          
      rows.add(new Item(count, trauma, 'GT'+count+'R__c', ages, subtitle));
        
    }
      
  }    

  public PageReference cancel() {

    PageReference summaryPage = new PageReference('/apex/ClientSummary?s=Trauma&id=' + client.id);
    summaryPage.setRedirect(true);
    
    return summaryPage;

  }
  
  public PageReference save() {

    PageReference nextPage;
      
    try {
      if(edit == FALSE)
        insert GTRAUMA;
      else
        update GTRAUMA;

      nextPage = new PageReference(skip.formRedirct(cID, '-1', '1'));
      nextPage.setRedirect(true);
    }
    catch(DMLException e) { nextPage = null; }

    /*PageReference summaryPage = new PageReference('/apex/ClientSummary?s=Trauma&id=' + client.id);
    summaryPage.setRedirect(true);
      return summaryPage;
    */

    /*PageReference nextPage = new PageReference(skip.formRedirct(cID, '-1', '1'));
    system.debug(nextPage);
    nextPage.setRedirect(true);*/
    
    return nextPage;
    //return null;
      
  }

}