src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>AGE__c</fullName>
        <description>Client&apos;s age as entered in the System Screening</description>
        <label>Age</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GENDER__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t know/ Information not available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FORM_TYPE__c</fullName>
        <label>FORM_TYPE</label>
        <picklist>
            <picklistValues>
                <fullName>Baseline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DS DATA Page</label>
        <referenceTo>DS_DATA__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REQUIRED__c</fullName>
        <defaultValue>false</defaultValue>
        <label>REQUIRED</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Client Summary</label>
    <nameField>
        <displayFormat>summary-{000000}</displayFormat>
        <label>Client Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DS_Background_Family_Info_F__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Background Family Info F</relationshipLabel>
        <relationshipName>DS_Background_Family_Info_F</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;1&apos;</defaultValue>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>DS Background Family Info F</label>
    <nameField>
        <label>DS Background Family Info F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Background Family Info F</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DS_DATA__c.object
<CustomObject>
    <fields>
        <fullName>Age_Range__c</fullName>
        <label>Age_Range</label>
        <picklist>
            <picklistValues>
                <fullName>0_5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.5_5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3_21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4_10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6_18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6_21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7_18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7_21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12_18</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data_Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FILE_NAME__c</fullName>
        <label>File_name</label>
        <picklist>
            <picklistValues>
                <fullName>BASELINE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRAUMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOLLOWUP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <picklist>
            <picklistValues>
                <fullName>DS_BIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_BSLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CANSTR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CLINEVAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DEMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FAPGAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FOLLOWUPINFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INSDOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_MILITARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NCTSNTREAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_POST_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_REFIMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_04_10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_S_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SERVREC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_YCINDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRABUSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRACCIDENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRBEREAVE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Boy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Girl</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Section</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Variable__c</fullName>
        <label>Variable</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DS DATA</label>
    <nameField>
        <displayFormat>DS DATA - {000000}</displayFormat>
        <label>DS DATA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS DATA</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/FormBuilder.cls
public class FormBuilder {

    /////start newSummary method ////////
  public static Client_Summary__c newSummary(String clientID, ID formID, String formCategory, String sectionNum, Boolean required) {

    Client_Summary__c newSummary = 
      new Client_Summary__c(client__c = clientID, Page__c = formID, 
                            FORM_TYPE__c = formCategory, REQUIRED__c = required,
                            SECTION__c = sectionNum);

    return newSummary;
  }
    //////////end newSummary method////////////////
                                        
  ////////////start baseline method//////////////// 
  public static void baseline(Set<String> clients) {

    List<Client_Summary__c> newSummaryList = new List<Client_Summary__c>();
    
    List<DS_Data__c> formInfo = [SELECT Category__c, Content__c, Variable__c,  
                                        Age_Range__c, Form__c
                                   FROM DS_Data__c 
                                  WHERE (Category__c = 'Baseline' 
                                     OR Category__c = 'Assessment'
                                     OR Category__c = 'GT')
                                    AND Data_Type__c = 'DS_Form_Info'
                                    AND FILE_NAME__c = 'Baseline'
                               ORDER BY Category__c, weight__c];

    System.debug(formInfo);
                                        
    Map<Id, Client__c> clientInfo = 
      new Map<Id, Client__c>([SELECT id, age__c, gender__c
                                FROM Client__c
                               WHERE id IN : clients]); 

    // For display logic. Don't add Military, REFIMM, and Health in client summary object. 
    Set<String> skippedForm = new Set<String>();
    skippedForm.add('DS_MILITARY');
    skippedForm.add('DS_REFIMM');
    skippedForm.add('DS_HEALTH');

    for(DS_Data__c f : formInfo) {

      String sectionNum = (f.Category__c == 'GT') ? '-1' : '0';

      // Skip and jump to next form
      if(skippedForm.contains(f.Form__c)) continue;
  
      for(String c : clients) {
      
        if(f.Age_Range__c == null) {
          newSummaryList.add(newSummary(c, f.id, f.Category__c, sectionNum, true));
        }
        else {

          List<String> range = f.Age_Range__c.split('-', 0); 

          if((Double.valueOf(range.get(0)) <= Double.valueOf(clientInfo.get(c).AGE__c)) && (Double.valueOF(range.get(1)) >= Double.valueOf(clientInfo.get(c).AGE__c)))           
            newSummaryList.add(newSummary(c, f.id, f.Category__c, sectionNum, true));

        }

      }
        
    }

    insert newSummaryList;
  
  }
    ///////////////end baseline method/////////////////////      
    
          ////////////start follow-up method//////////////// 
  public static void followup(Set<String> clients) {
  
  DS_Background_Family_Info_F__c background = new DS_Background_Family_Info_F__c();
  
  List<DS_Background_Family_Info_F__c> backgroundList= new List<DS_Background_Family_Info_F__c>();
                       
  //for query
  Client_Summary__c summary = new Client_Summary__c();
  
  //new visit
    List<Client_Summary__c> newSummaryList = new List<Client_Summary__c>();
        
    //forms for visit
    List<DS_Data__c> followformInfo = [SELECT Category__c, Content__c, Variable__c,  
                                        Age_Range__c, Form__c
                                   FROM DS_Data__c 
                                  WHERE (Category__c = 'FollowUp' 
                                    OR Category__c = 'Assessment')
                                    AND Data_Type__c = 'DS_Form_Info'
                                    AND FILE_NAME__c = 'FOLLOWUP'
                               ORDER BY Category__c, weight__c];


    system.debug(followformInfo);
                               
    //client
    Map<Id, Client__c> clientInfo = 
      new Map<Id, Client__c>
          ([SELECT id, age__c, gender__c
                                FROM Client__c
                               WHERE id IN : clients]); 
      
    //check to see if skipped rules apply
Set<String> skippedForm = new Set<String>();                        
        
        String sectionNum;        
        String client_id;

    for(DS_Data__c f : followformInfo) {
        List<aggregateResult> sections= [SELECT Max (Section__c) section,client__c  FROM Client_summary__c WHERE client__c IN: clients GROUP BY client__c ];//String.valueOf([SELECT Max (Section__c) FROM Client_summary__c WHERE client__c IN: clients GROUP BY client__c ]);
        System.debug(sections);
        
        for (AggregateResult ar : sections)  {
        System.debug(ar.get('client__c'));
        client_id= String.valueOf(ar.get('client__c'));
        
          System.debug(ar.get('section'));
        sectionNum = String.valueOf(ar.get('section'));
        System.debug(sectionNum);

        }        
        
        System.debug(client_id);
    
        System.debug(sectionNum);
        
        
        Map<String, Integer> Section_Num = new Map<string, Integer>();
    Section_Num.put(client_id,Integer.valueOf(sectionNum));
    
    System.debug(Section_Num);
    
  //  Section_Num.put(2, integer.valueOf(sectionNum));//Max(section__c));
      //  String -> clientID
      //  int -> Max(section__c)

    //  for(Client__c c : clients) {

        //age range check

        sectionNum=String.valueOf(Integer.valueOf(sectionNum)+1);

        newSummaryList.add(newSummary(client_id, f.id, f.Category__c, sectionNum, true)); 
System.debug(newSummaryList);

        System.debug(sectionNum);
     // }

    }

        System.debug(sectionNum);
    insert newSummaryList;

        System.debug(sectionNum);
  }
      ///////////////end follow-up method///////////////////// 
    
  public static void MilitaryRefugeHealthDisplayLogic(List<SObject> obj) {  

    String section = String.valueOf(obj.get(0).get('SECTION__c'));

    String BorF = (Integer.valueOf(section) > 0) ? 'F' : 'B';

    String category = (Integer.valueOf(section) > 0) ? 'FollowUp' : 'Baseline';

    List<String> forms = new List<String>{'DS_HEALTH', 'DS_MILITARY', 'DS_REFIMM'};
    
    List<DS_Data__c> formInfo = [SELECT Content__c, Variable__c,  
                                        Form__c, id
                                   FROM DS_Data__c 
                                  WHERE Category__c = : category 
                                    AND Data_Type__c = 'DS_Form_Info'
                                    AND Form__c IN : forms];

    Map<String, DS_DATA__c> formMap = new Map<String, DS_DATA__c>();                                    
    for(DS_Data__c info : formInfo) formMap.put(info.Form__c, info);

    List<String> clients = new List<String>();

    for(SObject b : obj) clients.add(String.valueOf(b.get('Client__c')));

    List<Client_Summary__c> clientSummary = [SELECT Page__c, Client__c
                                               FROM Client_Summary__c
                                              WHERE Client__c IN : clients
                                                AND Page__r.Form__c IN : forms
                                                AND SECTION__c = : section];

    Set<String> clientSummaryExisted = new Set<String>();

    for(Client_Summary__c cs : clientSummary)
      clientSummaryExisted.add(cs.Client__c+'-'+cs.Page__c);

    Map<Id, Client__c> clientInfo = 
      new Map<Id, Client__c>([SELECT id, age__c, gender__c
                                FROM Client__c
                               WHERE id IN : clients]); 

    List<Client_Summary__c> insertClientSummary = new List<Client_Summary__c>();

    for(SObject b : obj) {

      String clientID = String.valueOf(b.get('Client__c'));
      String sectionNum = String.valueOf(b.get('SECTION__c'));

      if ((b.get(BorF+'USBORN__c') == '0' || b.get(BorF+'PUSBORN__c') == '0') && (!clientSummaryExisted.contains(clientID+'-'+formMap.get('DS_REFIMM').id)))        
        insertClientSummary.add(newSummary(clientID, formMap.get('DS_REFIMM').id, category, sectionNum, true));
      
      if ((b.get(BorF+'MILSELF__c') == '1' || b.get(BorF+'MILFAMILY__c') == '1' || b.get(BorF+'MILFAMILY__c') == '2') && (!clientSummaryExisted.contains(clientID+'-'+formMap.get('DS_MILITARY').id)))
        insertClientSummary.add(newSummary(clientID, formMap.get('DS_MILITARY').id, category, sectionNum, true));    
      
      if ((b.get(BorF+'HOVERALL__c') == '4' || b.get(BorF+'HOVERALL__c') == '5' || b.get(BorF+'HTHSTAT__c') == '1' || b.get(BorF+'HTHSTAT__c') == '2' || b.get(BorF+'HTHSTAT__c') == '3') && (!clientSummaryExisted.contains(clientID+'-'+formMap.get('DS_HEALTH').id)))
        insertClientSummary.add(newSummary(clientID, formMap.get('DS_HEALTH').id, category, sectionNum, true));       

    }           

    insert insertClientSummary;

  }
  

}