src/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DS_SDQ_PSI_CDI_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOASDOP__c</fullName>
        <description>Parent 11-17: Date of Administration</description>
        <label>BDOASDOP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BDOASDOS__c</fullName>
        <description>Self 11-17: Date of Administration</description>
        <label>BDOASDOS</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BDOASDYP__c</fullName>
        <description>Parent 4-10: Date of Administration</description>
        <label>BDOASDYP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BMETSDOP__c</fullName>
        <description>Parent 11-17 method of administration</description>
        <label>BMETSDOP</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BMETSDOS__c</fullName>
        <description>Self 11-17 method of administration</description>
        <label>BMETSDOS</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BMETSDYP__c</fullName>
        <description>Parent 4-10 method of administration</description>
        <label>BMETSDYP</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS SDQ PSI CDI B</relationshipLabel>
        <relationshipName>DS_SDQ_PSI_CDI_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FORM__c</fullName>
        <label>FORM</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>DS SDQ PSI CDI B</label>
    <nameField>
        <label>DS SDQ PSI CDI B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS SDQ PSI CDI B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestClass_DS_SDQ_PSI_CDI_B.cls
@isTest 
private class TestClass_DS_SDQ_PSI_CDI_B{
  static TestMethod void Test_TestInsertUpdateDelete() {
    TestClass_Utility test_ut = new TestClass_Utility(); 
    TestClassData_DS_SDQ_PSI_CDI_Form_Info formInfo = new TestClassData_DS_SDQ_PSI_CDI_Form_Info();
   

    Client__c client = test_ut.createClientSummary();
    ///begin bulk insert
    System.debug('Inserting 200 baseline records... (bulk validation)');   
    List<DS_SDQ_PSI_CDI_B__c> bulkObj = new List<DS_SDQ_PSI_CDI_B__c>();     
    for (Integer i=0;i<200;i++){
      bulkobj.add(new DS_SDQ_PSI_CDI_B__c(client__c = client.id,
                                          BDOASDYP__c =date.parse('10/30/2014'),
                                          BDOASDOP__c =date.parse('10/30/2014'),
                                          BDOASDOS__c =date.parse('10/30/2014'), 
                                          Form__c = 'DS_SDQ_P_04_10',
                                          BMETSDOP__c = '1', 
                                          BMETSDOS__c = '1', 
                                          BMETSDYP__c = '1' ));//,RREF__c= true?
      
    }
    insert bulkObj;

}
}