src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>AGE__c</fullName>
        <description>Client&apos;s age as entered in the System Screening</description>
        <label>Age</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Clinician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinician ID</label>
        <referenceTo>Clinician__c</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOB1__c</fullName>
        <label>Date of birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DOB2__c</fullName>
        <label>DOB2</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GENDER__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t know/ Information not available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>INIT__c</fullName>
        <label>INITIALS</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Clinician__c.object
<CustomObject>
    <label>Clinician</label>
    <nameField>
        <label>Clinician ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinicians</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kewbox/src/classes/TestClass_Client.cls
/****
*@description This test provides code coverage for Client
*includes
*Trigger 
*Bulkified testing
*
*@group Test Script 
*@group-content /ApexDocContent/Test/Client.htm
*
*@author Kelsey Willett
*@date 11/18/2015
*@modified date
****/

@isTest (SeeAllData=false)
private class TestClass_Client {
    
    /****
    *@description Initialize reference to TestClass_A_Utility
    ****/
    public static TestClass_A_Utility test_ut = new TestClass_A_Utility();
    
    /****
    *@description Initialize reference to Utility
    ****/
    public static Utility ut = new Utility();
    
    /****
    *@description method to test a bulk creation of object
    ****/
    static TestMethod void bulkifyObj(){
    
        Clinician__c clinician = test_ut.createClinician();
                
        List<Client__c> bulkObj = new List<Client__c>();
        
        for(Integer i=0;i<65;i++){
            test_ut.addAdminToCounter();
            bulkObj.add(new Client__c(Clinician__c= clinician.id, INIT__c= 'KEW',DOB1__c=date.today(), DOB2__c=date.today() , AGE__c=0 , GENDER__c='Female' ));
        }
        insert bulkObj;
    }
    
    /****
    *@description method to test creation of client record
    ****/
      static TestMethod void Test_ClientController_CreateClient() {

        test_ut.addAdminToCounter();

        Client__c client = new Client__c();

        PageReference pageRef = ApexPages.currentPage();
        Test.setCurrentPage(pageRef);

        ApexPages.StandardController sc = new ApexPages.StandardController(client);

        ClientController controller = new ClientController(sc);
            
      }

    /****
    *@description method to test editing a record
    ****/
      static TestMethod void Test_ClientController_EditClient() {

        Client__c client = Test0_TestClientInsert();

        PageReference pageRef = ApexPages.currentPage();
        pageRef.getParameters().put('id', client.id);
        Test.setCurrentPage(pageRef);

        ApexPages.StandardController sc = new ApexPages.StandardController(client);

        ClientController controller = new ClientController(sc);    

      }

    /****
    *@description method to test inserting a record
    ****/
      static TestMethod Client__c Test0_TestClientInsert() {

        Client__c client = test_ut.createClient();
        
        return client;

      }

    /****
    *@description method to test updating a record
    ****/
      static TestMethod void Test1_TestClientUpdate() {

        Client__c client = Test0_TestClientInsert();
        
        update client;

      }

}