src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>CURRENT_AGE__c</fullName>
        <description>Current age =( today&apos;s date - date of birth)/365 days</description>
        <formula>FLOOR((TODAY() - DOB1__c)/365.2425)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CURRENT_AGE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GENDER__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t know/ Information not available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>INIT__c</fullName>
        <label>INITIALS</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DS DATA Page</label>
        <referenceTo>DS_DATA__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Client Summary</label>
    <nameField>
        <displayFormat>summary-{000000}</displayFormat>
        <label>Client Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DS_DATA__c.object
<CustomObject>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Boy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Girl</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOURCE_FORM__c</fullName>
        <label>Source_form</label>
        <picklist>
            <picklistValues>
                <fullName>BIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANSTR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBCL_SCORES_OLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBCL_SCORES_YOUNG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLINEVAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAPGAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAPGAR_SCORES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOLLOWUPINFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INSDOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MILITARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCTSNTREAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PTSD_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PTSD_SCORES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REFIMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDQ_P_04_10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDQ_P_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDQ_PARENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDQ_S_11_17</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Section</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VARIABLE_NAME__c</fullName>
        <label>Variable_name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>DS DATA</label>
    <nameField>
        <displayFormat>DS DATA - {000000}</displayFormat>
        <label>DS DATA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS DATA</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Form.cls
global with sharing class Form {

    public Utility ut = new Utility();
    
    public String title { get; set; }
    
    public String subTitle { get; set; }
    
    public String cID { get; set; }
  
    public String summaryID { get; set; }
    
    public String forceRedirect { get; set; } 
    
    public Client__c client { get; set; }
    
    public Client_Summary__c summary { get; set; }
    
    public Sobject obj { get; set; }
    
    public String BorF { get; set; }

    public Boolean isBaseline { get; set; }

    public Boolean isFollowup { get; set; }
    
    public String objName { get; set; }
    
    public Boolean edit = FALSE;

    public String visitType { get; set; }
    
    public SkipLogic skip { get; set; }
    
    Map<String, String> parameter;
    
    
    public Form(String cimi) {
    
        parameter = ut.urlDecode(cimi);
    
        this.cID = parameter.get('c');
        this.summaryID = parameter.get('summary');
        this.forceRedirect = (parameter.containsKey('f')) ? parameter.get('f') : '';
                
        this.client = (cID != null) ? [SELECT Name, INIT__c, GENDER__c, CURRENT_AGE__c FROM Client__c WHERE id =: cID] : null;
        this.summary = (summaryID != null) ? [SELECT SECTION__c, Page__r.CONTENT__c FROM Client_Summary__c WHERE ID =:summaryID] : null;
          
        this.BorF = (Integer.valueOf(summary.SECTION__c) > 0) ? 'F' : 'B';

        this.isBaseline = (Integer.valueOf(summary.SECTION__c) > 0) ? false : true;
        this.isFollowup = (Integer.valueOf(summary.SECTION__c) > 0) ? true : false;

        this.visitType = (summary.SECTION__c == '-1') ? 'trauma' : ((Integer.valueOf(summary.SECTION__c) > 0) ? 'followup' : 'baseline');
        
        this.title = summary.Page__r.CONTENT__c;
        this.subTitle = '(' + client.Name + ') ' + client.INIT__c;
        
    }
    
    public void setObjName(String objName) {
        this.objName = objName;
    }
    
    public void setSkipLogic(SkipLogic skip) {
        this.skip = skip;
    }
    
    public String getClientInfo() { return ut.clientSection(cID, SummaryID); }
    
    public Map<String, String> getVariable(String sourceForm) {

        Map<String, String> bfVariableMap = new Map<String, String>();

        Set<String> vars = new Set<String>();

        List<DS_DATA__c> varFromData = [SELECT VARIABLE_NAME__c 
                                          FROM DS_DATA__c
                                         WHERE SOURCE_FORM__c = :sourceForm];

        for(DS_DATA__c var : varFromData) {
            if(var.VARIABLE_NAME__c != null) 
                vars.add(var.VARIABLE_NAME__c.substring(1, var.VARIABLE_NAME__c.length()));
        }

        for(String bfVar : vars)
          bfVariableMap.put(bfVar, this.BorF+bfVar+'__c');

        bfVariableMap.put('STATUS', 'STATUS_'+sourceForm+'__c');
        
        return bfVariableMap;

    }
    
    public void getObjRecord() {
    
        String objFields = ut.getFields(objName);
        
        List<SObject> record = 
          Database.query('SELECT ' + objFields + ',' +
                                 'Client__r.Name, Client__r.INIT__c' +  
                         '  FROM ' + objName +                          
                         ' WHERE Client__c = \''+ cID + '\'' +
                         '    AND SECTION__c = \'' + summary.SECTION__c + '\'');
    
        if(record.size() == 0) { // New record
          
          Schema.SObjectType objType = Schema.getGlobalDescribe().get(objName);
    
          obj = objType.newSObject();
    
          obj.put('Client__c', cID);
          obj.put('SECTION__c', summary.SECTION__c);
           
        }
        else {   // Update record
          
          obj = record.get(0);
          edit = TRUE;
          if(skip != null) {
            for(String lKey : skip.skipList.keySet()) 
                for(String sKey : skip.skipList.get(lKey).keySet()) {
                  skip.skipList.get(lKey).get(sKey).addTargetValue(String.valueOf(obj.get(BorF+lKey+'__c')));
                }
          }
          
        } 
    
    }

    public Boolean saveObjRecord() {

        try {
            upsert obj;
            system.debug(obj);
            return true;
        } 
        catch(DMLException e) { system.debug(e); }

        return false;

    }
    
   
    

}