src/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DS_Background_Family_Info_B__c.object
<CustomObject>
    <fields>
        <fullName>BTRTOTHR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Other Please specify</description>
        <label>BTRTOTHR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BTRTOTSP__c</fullName>
        <description>Other Specified</description>
        <label>BTRTOTSP</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BTRT__c</fullName>
        <description>2. Childs course of treatment</description>
        <label>BTRT</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Background Family Info B</relationshipLabel>
        <relationshipName>DS_Background_Family_Info_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RWHITE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is White</description>
        <label>RWHITE</label>
        <type>Checkbox</type>
    </fields>
    <label>DS Background Family Info B</label>
    <nameField>
        <label>DS Background Family Info B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Background Family Info B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestClass_DS_HEALTH.cls
@istest(SeeAllData=false)
public class TestClass_DS_HEALTH{

 static TestMethod void Test_DS_HEALTH_Controller(){
 
    Utility ut = new Utility();
    TestClass_Utility test_ut = new TestClass_Utility();
    
    Client__c client = test_ut.createClientSummary();
String cimi= ut.urlEncode('c='+client.id);
ApexPages.currentPage().getParameters().put('cimi',cimi);

    DS_Background_Family_Info_B__c obj = new DS_Background_Family_Info_B__c();
  //  obj.STATUS__c = 'Complete'; 
        obj.RWHITE__c=true;
    obj.client__c = client.id;
    ApexPages.StandardController sc = new ApexPages.StandardController(obj);
    DS_HEALTH_Controller controller = new DS_HEALTH_Controller(sc);
    
        List<SelectOption> nyu = controller.getNYUItems();
     
    controller.save();
    controller.cancel();
    
    // Update record
  /*  obj = [SELECT id FROM DS_Background_Family_Info_B__c WHERE client__c =: client.id];
    sc = new ApexPages.StandardController(obj);
    controller = new DS_HEALTH_Controller(sc);
 //   ApexPages.currentPage().getParameters().put('cimi', cimi);
    controller.save();   */
  }
  
      static TestMethod void Test_samlpeAsserts(){ 
  
    Utility ut = new Utility();
    TestClass_Utility test_ut = new TestClass_Utility();
    
//create test client 
    Client__c client = test_ut.createClientSummary();
String cimi= ut.urlEncode('c='+client.id);
ApexPages.currentPage().getParameters().put('cimi',cimi);

    DS_Background_Family_Info_B__c obj = new DS_Background_Family_Info_B__c();
        obj.RWHITE__c=true;
    obj.client__c = client.id;
    
    ApexPages.StandardController sc = new ApexPages.StandardController(obj);
    
    //    controllers   
 DS_HEALTH_Controller healthController = new DS_HEALTH_Controller(sc); //healthController
 
   //Health
//String BTRT= '1';
//Boolean BTRTOTHR= true;
String BTRTOTSP= 'null'; 

 insert obj;
 
 //asserts
   //Health
// System.assertNotEquals(obj.BTRT__c,BTRT,'Child does NOT have current course of treatment.');
 //System.assertNotEquals(obj.BTRTOTHR__c,BTRTOTHR,'Other condition NOT selected.');
 System.assertNotEquals(obj.BTRTOTSP__c,BTRTOTSP,'Condition is specified as '+obj.BTRTOTSP__c+'.');
 
 //save/cancels
    healthController.save();
   healthController.cancel();
      }
  }