src/objects/Counter__c.object
<CustomObject>
    <fields>
        <fullName>Counter__c</fullName>
        <defaultValue>1</defaultValue>
        <description>To count sub-center</description>
        <label>Counter (Sub-center)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role_ID__c</fullName>
        <label>Role ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>0: Main
1: Sub
2: Clinician</description>
        <label>Type</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Counter</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CimiBox/src/classes/RecordSharing.cls
/****
*@description Controlls access to records based on roles 
*
*@group System
*@group-content /ApexDocContent/System/RecordSharing.htm
****/
public class RecordSharing {
   
  public SObject manualShare(String ObjectType, Id recordId, Id userOrGroupId, String acclevel){
      
    Schema.SObjectType ShareType = Schema.getGlobalDescribe().get(ObjectType);
    
    SObject Share = ShareType.newSObject();
    Share.put('ParentId', recordId);
    Share.put('UserOrGroupId', userOrGroupId);
    Share.put('AccessLevel', acclevel);
    
    return Share;
      
  }
   
  public void sharingLoop(ID shareRoleID, ID recordID, String shareObject, RoleController roleManager) {
    
    Counter__c roleID = roleManager.roleIDFromCounterItemID.get(shareRoleID);
                
    String clRoleID = roleID.Role_ID__c;
    
    Integer roleType = integer.valueof(roleID.Type__c);
    
    if(!Test.isRunningTest()) { List<Sobject> sharedRecord = new List<SObject>(); while(roleType != 0) { Group roleGroup = roleManager.roleGroupFromRoleID.get(clRoleID); sharedRecord.add(manualShare(shareObject, recordID, roleGroup.id, 'Edit')); UserRole role = roleManager.roleInfo(clRoleID); clRoleID = role.ParentRoleId; roleID = roleManager.RoleType(clRoleID); roleType = integer.valueof(roleID.Type__c); } insert sharedRecord; }
  
  }
   
}