src/objects/Counter__c.object
<CustomObject>
    <fields>
        <fullName>Counter__c</fullName>
        <defaultValue>1</defaultValue>
        <description>To count sub-center</description>
        <label>Counter (Sub-center)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <label>Item ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_ID__c</fullName>
        <label>Role ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>0: Main
1: Sub
2: Clinician</description>
        <label>Type</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Counter</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoleControllerStatic.cls
public class RoleControllerStatic {
    
  public static void sleep(Integer sleepSeconds) {
  
      Long startTS = System.currentTimeMillis();
      HttpRequest req = new HttpRequest();
      req.setEndpoint('http://1.cuzillion.com/bin/resource.cgi?sleep=' + sleepSeconds);
      req.setMethod('GET');
      Http http = new Http();
      if(!Test.isRunningTest()) HTTPResponse res = http.send(req);
      Long duration = System.currentTimeMillis() - startTS;
      
  }
  
  @Future(callout=true)
  public static void insertRoleList(String roleName, String centerID, Integer type) {
              
      RoleControllerStatic.sleep(1); 

      RecordSharing roleShare = new RecordSharing();

      UserRole rInfo = [SELECT Id, name 
                          FROM UserRole
                         WHERE Name LIKE :roleName];

      Counter__c counter = new Counter__c(Item_ID__c = centerID, 
                                          Item_name__c = roleName, 
                                          Type__c = type, 
                                          Role_ID__c = rInfo.id); 

      insert counter;
              
      if(type == 1) { 
        Group roleGroup = [SELECT Id 
                             FROM Group 
                            WHERE RelatedId = :rInfo.id 
                              AND Type = 'Role']; 

        if(!Test.isRunningTest())
          roleShare.manualShare('Center__Share', centerID, roleGroup.id, 'Read'); 
      }
              
  }
  

  @future
  public static void CreateCenter(String name, ID parentRoleID) {
      
    UserRole crole = new UserRole(Name = name, ParentRoleID = parentRoleID);
    
    insert crole;
      
  }
  
  
  @future
  public static void DeleteRole(String roleID) {
    
    RoleController role = new RoleController();

    UserRole crole = [SELECT Id, name 
                        FROM UserRole
                       WHERE id = :roleID];
                       
    role.CleanUserRole(roleID);
      
    if(!Test.isRunningTest()) delete crole;

  }
  
  @future
  public static void UpdateCenter(String roleName, ID roleID) {
      
      
    UserRole crole = [SELECT Id, name 
                        FROM UserRole
                       WHERE Id = :roleID];
    
    crole.Name = roleName;
            
    //if(!Test.isRunningTest())
    update crole;
          
  }



}