src/objects/DS_DATA__c.object
<CustomObject>
    <fields>
        <fullName>Age_Range__c</fullName>
        <label>Age_Range</label>
        <picklist>
            <picklistValues>
                <fullName>0_5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.5_5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3_21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4_10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6_18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6_21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7_18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7_21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12_18</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data_Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FILE_NAME__c</fullName>
        <label>File_name</label>
        <picklist>
            <picklistValues>
                <fullName>BASELINE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRAUMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOLLOWUP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <picklist>
            <picklistValues>
                <fullName>DS_BIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_BSLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CANSTR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CLINEVAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DEMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_DOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FAPGAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_FOLLOWUPINFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_INSDOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_MILITARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NCTSNTREAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_POST_NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_PTSD_CA_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_REFIMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_04_10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_P_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SDQ_S_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_SERVREC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_YCINDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRABUSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRACCIDENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRBEREAVE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOURCE_FORM__c</fullName>
        <label>Source_form</label>
        <picklist>
            <picklistValues>
                <fullName>BIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANSTR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBCL_SCORES_OLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBCL_SCORES_YOUNG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLINEVAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_0_5_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS_CBCL_6_18_F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAPGAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAPGAR_SCORES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOLLOWUPINFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEALTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INDSEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INSDOMENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MILITARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCTSNTREAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PTSD_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PTSD_SCORES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REFIMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDQ_P_04_10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDQ_P_11_17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDQ_PARENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDQ_S_11_17</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Variable__c</fullName>
        <label>Variable</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DS DATA</label>
    <nameField>
        <displayFormat>DS DATA - {000000}</displayFormat>
        <label>DS DATA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS DATA</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestClassData_DS_SDQ_PSI_CDI_Form_Info.cls
@isTest
public class TestClassData_DS_SDQ_PSI_CDI_Form_Info{
public TestClassData_DS_SDQ_PSI_CDI_Form_Info(){
    
    List<List<String>> FormInfo = new List<List<String>>();
        
    //FormInfo.add(new List<String> {'Data_Type__c','Content__c','Object__c','Form__c','File_name__c','Age_Range__c','Source_form__c','Category__c','Page__c','Weight__c','Variable__c'});
    FormInfo.add(new List<String> {'DS_Form_Info','Strengths and Difficulties Questionnaire for Parents 4-10','DS_SDQ_PSI_CDI_B','DS_SDQ_P_04_10','BASELINE','4-10','DS_SDQ_P_04_10','Assessment','DS_SDQ_P_04_10','4','DS_SDQ_P_04_10'});
    FormInfo.add(new List<String> {'DS_Form_Info','Strengths and Difficulties Questionnaire for Parents 11-17','DS_SDQ_PSI_CDI_B','DS_SDQ_P_11_17','BASELINE','11-17','DS_SDQ_P_11_17','Assessment','DS_SDQ_P_11_17','5','DS_SDQ_P_11_17'});
    FormInfo.add(new List<String> {'DS_Form_Info','Strengths and Difficulties Questionnaire Self-Assessment 11-17','DS_SDQ_PSI_CDI_B','DS_SDQ_S_11_17','BASELINE','11-17','DS_SDQ_S_11_17','Assessment','DS_SDQ_S_11_17','6','DS_SDQ_S_11_17'});

  List<DS_DATA__c> infoBox = new List<DS_DATA__c>();

    for(List<String> f : FormInfo) {
    
        //FormInfo.add(new List<String> {'Data_Type__c','Content__c','Object__c','Form__c','File_name__c','Age_Range__c','Source_form__c','Category__c','Page__c','Weight__c','Variable__c'});

      DS_DATA__c info = new DS_DATA__c();   
      info.Data_Type__c = f.get(0);
      info.Content__c = f.get(1);
      info.Object__c = f.get(2);
      info.Form__c = f.get(3);
      info.File_name__c = f.get(4);
      info.Age_Range__c = f.get(5);
      info.Source_form__c = f.get(6);
      info.Category__c = f.get(7);
      info.Page__c = f.get(8);
      info.Weight__c = (f.get(9) != '') ? Integer.valueOf(f.get(9)) : null;
      info.Variable__c = f.get(10);


      infoBox.add(info);

    }

   List<DS_DATA__c> checkForm = [SELECT id FROM DS_DATA__c WHERE Data_type__c = 'DS_Form_Info' AND Object__c ='DS_SDQ_PSI_CDI_B'];
  
    if(checkForm.size() == 0) insert infoBox;

    //insert infoBox;

    System.debug(infoBox);

  }
    
}