src/objects/DS_SDQ_PSI_CDI_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOASDOP__c</fullName>
        <description>Parent 11-17: Date of Administration</description>
        <label>BDOASDOP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BMETSDOP__c</fullName>
        <description>Parent 11-17 method of administration</description>
        <label>BMETSDOP</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPAFRA__c</fullName>
        <description>Parent 4-10: Many fears, easily scared</description>
        <label>BSDPAFRA</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPATTE__c</fullName>
        <description>Parent 4-10: Good attention span, sees chores or homework through to the end</description>
        <label>BSDPATTE</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPBEH__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Behavioral Difficulties Scoring, Parent4-10</description>
        <label>BSDPBEH</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSDPBULL__c</fullName>
        <description>Parent 4-10: Picked on or bullied by other youth</description>
        <label>BSDPBULL</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPCLIN__c</fullName>
        <description>Parent 4-10: Nervous in new situations, easily loses confidence</description>
        <label>BSDPCLIN</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPDIST__c</fullName>
        <description>Parent 11-17: Easily distracted, concentration wanders</description>
        <label>BSDPDIST</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPEMO__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Emotional Distress Scoring, Parent 11-17</description>
        <label>BSDPEMO</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSDPFIDG__c</fullName>
        <description>Parent 11-17: Constantly fidgeting or squirming</description>
        <label>BSDPFIDG</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPFIGH__c</fullName>
        <description>Parent 11-17: Often fights with other children or bullies them</description>
        <label>BSDPFIGH</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPFRIE__c</fullName>
        <description>Parent 11-17: Has at least one good friend</description>
        <label>BSDPFRIE</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPHYP__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Hyperactivity and Attentional Difficulties Scoring, Parent4-10</description>
        <label>BSDPHYP</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSDPLIES__c</fullName>
        <description>Parent 4-10: Often lies or cheats</description>
        <label>BSDPLIES</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPLONE__c</fullName>
        <description>Parent 4-10: Would rather be alone than with other youth</description>
        <label>BSDPLONE</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPOBEY__c</fullName>
        <description>Parent 4-10: Generally well behaved, usually does what adults request</description>
        <label>BSDPOBEY</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPOLDB__c</fullName>
        <description>Parent 4-10: Gets along better with adults than with other youth</description>
        <label>BSDPOLDB</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPOTC__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Difficulties with Other Children Scoring, Parent4-10</description>
        <label>BSDPOTC</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSDPPOPU__c</fullName>
        <description>Parent 4-10: Generally liked by other youth</description>
        <label>BSDPPOPU</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPREFL__c</fullName>
        <description>Parent 4-10: Thinks things out before acting</description>
        <label>BSDPREFL</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPREST__c</fullName>
        <description>Parent 4-10: Restless, overactive, cannot stay still for long</description>
        <label>BSDPREST</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPSOMA__c</fullName>
        <description>Parent 4-10: Often complains of headaches, stomach-aches or sickness</description>
        <label>BSDPSOMA</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPSTEA__c</fullName>
        <description>Parent 4-10: Steals from home, school or elsewhere</description>
        <label>BSDPSTEA</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPTANT__c</fullName>
        <description>Parent 4-10: Often loses temper</description>
        <label>BSDPTANT</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPUNHA__c</fullName>
        <description>Parent 4-10: Often unhappy, depressed or tearful</description>
        <label>BSDPUNHA</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDPWORR__c</fullName>
        <description>Parent 4-10: Many worries or often seems worried</description>
        <label>BSDPWORR</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS SDQ PSI CDI B</relationshipLabel>
        <relationshipName>DS_SDQ_PSI_CDI_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>STATUS_SDQ_P_04_10__c</fullName>
        <label>STATUS SDQ P 04 10</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DS SDQ PSI CDI B</label>
    <nameField>
        <label>DS SDQ PSI CDI B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS SDQ PSI CDI B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_SDQ_PSI_CDI_B__c.object
    <fields>
        <fullName>BFORM__c</fullName>
        <label>BFORM</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/objects/DS_SDQ_PSI_CDI_F__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS SDQ PSI CDI F</relationshipLabel>
        <relationshipName>DS_SDQ_PSI_CDI_F</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS SDQ PSI CDI F</label>
    <nameField>
        <label>DS SDQ PSI CDI F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS SDQ PSI CDI F</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_SDQ_PSI_CDI_F__c.object
    <fields>
        <fullName>STATUS_SDQ_P_04_10__c</fullName>
        <label>STATUS SDQ P 04 10</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/classes/TestClass_DS_SDQ_P_04_10.cls
@istest(SeeAllData=false)
public class TestClass_DS_SDQ_P_04_10 {
    
    public static TestClass_A_Utility test_ut = new TestClass_A_Utility();
    
    public static Utility ut = new Utility();
    
    @testSetup 
    static void setup() {
        // Load DS_DATA into system
        TestClassData_DS_DATA importData = new TestClassData_DS_DATA();      
    }
    
    // Test baseline controller 
    static TestMethod void Test_Baseline_Controller() {
                
        Client__c client = test_ut.createClientSDQY();
        
        // Get summaryId for Url
        String summaryId = test_ut.getClientSummaryId(client.id, 'DS_SDQ_P_04_10', '0');
        
        String cimi = ut.urlEncode('c='+client.id+'&summary='+summaryId);
        
        ApexPages.currentPage().getParameters().put('cimi',cimi);
        
        DS_SDQ_PSI_CDI_B__c obj = new DS_SDQ_PSI_CDI_B__c();    
        obj.STATUS_SDQ_P_04_10__c = 'Complete';
        obj.client__c = client.id;        
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);    
        DS_SDQ_P_04_10_Controller controller = new DS_SDQ_P_04_10_Controller(sc);        
        
        List<SelectOption> Overall = controller.getOverallItems();
        List<SelectOption> HowLong = controller.getHowLongItems();
        List<SelectOption> Improve = controller.getImprovementItems();
        List<SelectOption> Difficult = controller.getDegreeItems();
        
        controller.save();
        controller.cancel();
        controller.saveview();
     
    }
    
    // Test follow-up controller 
    static TestMethod void Test_Followup_Controller() {
        
        Client__c client = test_ut.createClient(test_ut.getClient('Female', 6));
        
        // add a new follow-up visit
        String section = test_ut.addNewFollowupVisit(client);
        
        String summaryId = test_ut.getClientSummaryId(client.id, 'DS_SDQ_P_04_10', section);
        
        String cimi = ut.urlEncode('c='+client.id+'&summary='+summaryId);
        ApexPages.currentPage().getParameters().put('cimi',cimi);
        
        DS_SDQ_PSI_CDI_F__c obj = new DS_SDQ_PSI_CDI_F__c();    
        obj.STATUS_SDQ_P_04_10__c = 'Complete';
        obj.client__c = client.id;        
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);    
        DS_SDQ_P_04_10_Controller controller = new DS_SDQ_P_04_10_Controller(sc);        
        
        List<SelectOption> Overall = controller.getOverallItems();
        List<SelectOption> HowLong = controller.getHowLongItems();
        List<SelectOption> Improve = controller.getImprovementItems();
        List<SelectOption> Difficult = controller.getDegreeItems();
        
        controller.save();
        controller.cancel();
        controller.saveview();
        
    }
    
    static TestMethod Client__c testWvals(){ 
    
        Client__c client = test_ut.createClient();
        DS_SDQ_PSI_CDI_B__c obj = new DS_SDQ_PSI_CDI_B__c();
        
        obj.Client__c = client.id;
        obj.BMETSDOP__c = '1';
        obj.BDOASDOP__c=date.today(); 
        obj.client__c = client.id;
        obj.BForm__c = 'DS_SDQ_P_04_10';
        
        obj.BSDPSOMA__c= '1';
        obj.BSDPWORR__c= '1';
        obj.BSDPUNHA__c= '1';
        obj.BSDPCLIN__c= '1';
        obj.BSDPAFRA__c= '1';
        obj.BSDPEMO__c= 1;
        obj.BSDPTANT__c= '1';
        obj.BSDPOBEY__c= '1';
        obj.BSDPFIGH__c= '1';
        obj.BSDPLIES__c= '1';
        obj.BSDPSTEA__c= '1';
        obj.BSDPBEH__c= 1;
        obj.BSDPREST__c= '1';
        obj.BSDPFIDG__c= '1';
        obj.BSDPDIST__c= '1';
        obj.BSDPREFL__c= '1';
        obj.BSDPATTE__c= '1';
        obj.BSDPHYP__c= 1;
        obj.BSDPLONE__c= '1';
        obj.BSDPFRIE__c= '1';
        obj.BSDPPOPU__c= '1';
        obj.BSDPBULL__c= '1';
        obj.BSDPOLDB__c= '1';
        obj.BSDPOTC__c= 1;
        obj.BSDPCONS__c= '1';
        obj.BSDPSHAR__c= '1';
        obj.BSDPCARI__c= '1';
        obj.BSDPKIND__c= '1';
        obj.BSDPHELP__c= '1';
        obj.BSDPKHB__c= 1;
        obj.BSDPIMPF__c= '1';
        obj.BSDPIMPH__c= '1';
        obj.BSDPIMPC__c= '1';
        obj.BSDPUPSET__c= '1';
        obj.BSDPIMPL__c= '1';
        obj.BSDPDCL__c= 1;
        obj.BSDPTOT__c= 1; 
        insert obj;
        return null;
        return client;
    }   
}