src/objects/DS_SDQ_PSI_CDI_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOASDOP__c</fullName>
        <description>Parent 11-17: Date of Administration</description>
        <label>BDOASDOP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BMETSDOP__c</fullName>
        <description>Parent 11-17 method of administration</description>
        <label>BMETSDOP</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSAFRA__c</fullName>
        <description>Self 11-17: I have many fears, I am easily scared</description>
        <label>BSDSAFRA</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSATTE__c</fullName>
        <description>Self 11-17: I finish the work I&apos;m doing. My attention is good</description>
        <label>BSDSATTE</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSBEH__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Behavioral Difficulties Scoring, Self</description>
        <label>BSDSBEH</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSDSBULL__c</fullName>
        <description>Self 11-17: Other children or young people pick on me or bully me</description>
        <label>BSDSBULL</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSCLIN__c</fullName>
        <description>Self 11-17: I am nervous in new situations. I easily lose confidence</description>
        <label>BSDSCLIN</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSDIST__c</fullName>
        <description>Self 11-17: I am easily distracted, I find it difficult to concentrate</description>
        <label>BSDSDIST</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSEMO__c</fullName>
        <description>Emotional Distress Scoring, Self</description>
        <label>BSDSEMO</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSDSFIDG__c</fullName>
        <description>Self 11-17: I am constantly fidgeting or squirming</description>
        <label>BSDSFIDG</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSFIGH__c</fullName>
        <description>Self 11-17: I fight a lot. I can make other people do what I want</description>
        <label>BSDSFIGH</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSFRIE__c</fullName>
        <description>Self 11-17: I have one good friend or more</description>
        <label>BSDSFRIE</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSHYP__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Hyperactivity and Attentional Difficulties Scoring, Self</description>
        <label>BSDSHYP</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSDSLIES__c</fullName>
        <description>Self 11-17: I am often accused of lying or cheating</description>
        <label>BSDSLIES</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSLONE__c</fullName>
        <description>Self 11-17: I would rather be alone than with people of my age</description>
        <label>BSDSLONE</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSOBEY__c</fullName>
        <description>Self 11-17: I usually do as I am told</description>
        <label>BSDSOBEY</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSOLDB__c</fullName>
        <description>Self 11-17: I get along better with adults than with people my own age</description>
        <label>BSDSOLDB</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSOTC__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Difficulties with Other Children Scoring, Self</description>
        <label>BSDSOTC</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSDSPOPU__c</fullName>
        <description>Self 11-17: Other people my age generally like me</description>
        <label>BSDSPOPU</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSREFL__c</fullName>
        <description>Self 11-17: I think before I do things</description>
        <label>BSDSREFL</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSREST__c</fullName>
        <description>Self 11-17: I am restless, I cannot stay still for long</description>
        <label>BSDSREST</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSSOMA__c</fullName>
        <description>Self 11-17: I get a lot of headaches, stomach-aches or sickness</description>
        <label>BSDSSOMA</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSSTEA__c</fullName>
        <description>Self 11-17: I take things that are not mine from home, school or elsewhere</description>
        <label>BSDSSTEA</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSTANT__c</fullName>
        <description>Self 11-17: I get very angry and often lose my temper</description>
        <label>BSDSTANT</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSUNHA__c</fullName>
        <description>Self 11-17: I am often unhappy, depressed or tearful</description>
        <label>BSDSUNHA</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BSDSWORR__c</fullName>
        <description>Self 11-17: I worry a lot</description>
        <label>BSDSWORR</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS SDQ PSI CDI B</relationshipLabel>
        <relationshipName>DS_SDQ_PSI_CDI_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>STATUS_SDQ_S_11_17__c</fullName>
        <label>STATUS SDQ S 11 17</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DS SDQ PSI CDI B</label>
    <nameField>
        <label>DS SDQ PSI CDI B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS SDQ PSI CDI B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_SDQ_PSI_CDI_B__c.object
    <fields>
        <fullName>BFORM__c</fullName>
        <label>BFORM</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/objects/DS_SDQ_PSI_CDI_F__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS SDQ PSI CDI F</relationshipLabel>
        <relationshipName>DS_SDQ_PSI_CDI_F</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS SDQ PSI CDI F</label>
    <nameField>
        <label>DS SDQ PSI CDI F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS SDQ PSI CDI F</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_SDQ_PSI_CDI_F__c.object
    <fields>
        <fullName>STATUS_SDQ_S_11_17__c</fullName>
        <label>STATUS SDQ S 11 17</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/classes/TestClass_DS_SDQ_S_11_17.cls
@istest(SeeAllData=false)
public class TestClass_DS_SDQ_S_11_17 {
    
    public static TestClass_A_Utility test_ut = new TestClass_A_Utility();
    
    public static Utility ut = new Utility();
    
    @testSetup 
    static void setup() {
        // Load DS_DATA into system
        TestClassData_DS_DATA importData = new TestClassData_DS_DATA();      
    }
    
    // Test baseline controller 
    static TestMethod void Test_Baseline_Controller() {
        
        Client__c client = test_ut.createClientSDQO();
        
        // Get summaryId for Url
        String summaryId = test_ut.getClientSummaryId(client.id, 'DS_SDQ_S_11_17', '0');
        
        String cimi = ut.urlEncode('c='+client.id+'&summary='+summaryId);
        
        ApexPages.currentPage().getParameters().put('cimi',cimi);
        
        DS_SDQ_PSI_CDI_B__c obj = new DS_SDQ_PSI_CDI_B__c();    
        obj.STATUS_SDQ_S_11_17__c = 'Complete';
        obj.client__c = client.id;        
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);    
        DS_SDQ_S_11_17_Controller controller = new DS_SDQ_S_11_17_Controller(sc);        
        
        List<SelectOption> Overall = controller.getOverallItems();
        List<SelectOption> HowLong = controller.getHowLongItems();
        List<SelectOption> Improve = controller.getImprovementItems();
        List<SelectOption> Difficult = controller.getDegreeItems();
        
        controller.save();
        controller.cancel();
        controller.saveview();
     
    }
    
    // Test follow-up controller 
    static TestMethod void Test_Followup_Controller() {
        
        Client__c client = test_ut.createClient(test_ut.getClient('Female', 14));
        
        // add a new follow-up visit
        String section = test_ut.addNewFollowupVisit(client);
        
        String summaryId = test_ut.getClientSummaryId(client.id, 'DS_SDQ_S_11_17', section);
        
        String cimi = ut.urlEncode('c='+client.id+'&summary='+summaryId);
        ApexPages.currentPage().getParameters().put('cimi',cimi);
        
        DS_SDQ_PSI_CDI_F__c obj = new DS_SDQ_PSI_CDI_F__c();    
        obj.STATUS_SDQ_S_11_17__c = 'Complete';
        obj.client__c = client.id;        
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);    
        DS_SDQ_S_11_17_Controller controller = new DS_SDQ_S_11_17_Controller(sc);        
        
        List<SelectOption> Overall = controller.getOverallItems();
        List<SelectOption> HowLong = controller.getHowLongItems();
        List<SelectOption> Improve = controller.getImprovementItems();
        List<SelectOption> Difficult = controller.getDegreeItems();
        
        controller.save();
        controller.cancel();
        controller.saveview();
        
    }

    
    static TestMethod Client__c testWvals(){ 
        
        Client__c client = test_ut.createClient();
        DS_SDQ_PSI_CDI_B__c obj = new DS_SDQ_PSI_CDI_B__c();
        
        obj.Client__c = client.id;
        obj.BMETSDOP__c = '1';
        obj.BDOASDOP__c=date.today();  
        obj.client__c = client.id;
        obj.BForm__c = 'DS_SDQ_S_11_17';
        
        obj.BSDSSOMA__c= '1';
        obj.BSDSWORR__c= '1';
        obj.BSDSUNHA__c= '1';
        obj.BSDSCLIN__c= '1';
        obj.BSDSAFRA__c= '1';
        obj.BSDSEMO__c= 1;
        obj.BSDSTANT__c= '1';
        obj.BSDSOBEY__c= '1';
        obj.BSDSFIGH__c= '1';
        obj.BSDSLIES__c= '1';
        obj.BSDSSTEA__c= '1';
        obj.BSDSBEH__c= 1;
        obj.BSDSREST__c= '1';
        obj.BSDSFIDG__c= '1';
        obj.BSDSDIST__c= '1';
        obj.BSDSREFL__c= '1';
        obj.BSDSATTE__c= '1';
        obj.BSDSHYP__c= 1;
        obj.BSDSLONE__c= '1';
        obj.BSDSFRIE__c= '1';
        obj.BSDSPOPU__c= '1';
        obj.BSDSBULL__c= '1';
        obj.BSDSOLDB__c= '1';
        obj.BSDSOTC__c= 1;
        obj.BSDSCONS__c= '1';
        obj.BSDSSHAR__c= '1';
        obj.BSDSCARI__c= '1';
        obj.BSDSKIND__c= '1';
        obj.BSDSHELP__c= '1';
        obj.BSDSKHB__c= 1;
        obj.BSDSIMPF__c= '1';
        obj.BSDSIMPH__c= '1';
        obj.BSDSIMPC__c= '1';
        obj.BSDSUPSET__c= '1';
        obj.BSDSIMPL__c= '1';
        obj.BSDSDCL__c= 1;
        obj.BSDSTOT__c= 1; 
        insert obj;
        return client;
    }   
}