Kelsey Development Sandbox/src/objects/Center__c.object
<CustomObject>
    <label>Center</label>
    <nameField>
        <label>Center ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>AGE__c</fullName>
        <label>Age</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CENTER__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Center</label>
        <referenceTo>Center__c</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CURRENT_AGE__c</fullName>
        <description>Current age =( today&apos;s date - date of birth)/365 days</description>
        <formula>FLOOR((TODAY() - DOB1__c)/365.2425)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CURRENT_AGE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Clinician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinician ID</label>
        <referenceTo>Clinician__c</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/Clinician__c.object
<CustomObject>
    <fields>
        <fullName>Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Center</label>
        <referenceTo>Center__c</referenceTo>
        <relationshipLabel>Clinicians</relationshipLabel>
        <relationshipName>Clinicians</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Clinician</label>
    <nameField>
        <label>Clinician ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinicians</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/Strategic_Reports__c.object
<CustomObject>
    <fields>
        <fullName>Age_Current_Age__c</fullName>
        <formula>Client__r.CURRENT_AGE__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age Current Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Age_Group_0_4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Age Group 0 4</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Age_Group_10_12__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Age Group 10 12</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Age_Group_13_17__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Age Group 13 17</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Age_Group_18_21__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Age Group 18 21</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Age_Group_5_9__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Age Group 5 9</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Age_Group__c</fullName>
        <label>Age Group</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Center__c</fullName>
        <formula>Client__r.CENTER__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Center</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Strategic Reports</relationshipLabel>
        <relationshipName>Strategic_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Clinician__c</fullName>
        <formula>Client__r.Clinician__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Clinician</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateEnd__c</fullName>
        <label>DateEnd</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateStart__c</fullName>
        <label>DateStart</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnic_Group__c</fullName>
        <label>Ethnic Group</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ethnicity_Hispanic_or_Latino__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ethnicity Hispanic or Latino</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ethnicity_Missing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ethnicity Missing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ethnicity_Non_Hispanic__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ethnicity Non Hispanic</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ethnicity_Refused_or_Unknown__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ethnicity Refused or Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender_Female__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gender Female</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender_Identity__c</fullName>
        <label>Gender Identity</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender_Male__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gender Male</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender_Missing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gender Missing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender_Other__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gender Other</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender_Refused_or_Unknown__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gender Refused or Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender_Transgender__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gender Transgender</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Military_Associated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Military Associated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Military_Missing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Military Missing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Race_American_Indian_or_Alaskan_Native__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Race American Indian or Alaskan Native</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Race_Asian__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Race Asian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Race_Black_African_American__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Race Black African American</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Race_Multiracial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Race Multiracial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Race_Native_Hawaiian_or_Pacific_Islander__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Race Native Hawaiian or Pacific Islander</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Race_Refused_or_Unknown__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Race Refused or Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Race_White__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Race White</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treatment_Completed_as_Planned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Treatment Completed as Planned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Treatment_Ended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Treatment Ended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Treatment_Missing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Treatment Missing</label>
        <type>Checkbox</type>
    </fields>
    <label>Strategic Reports</label>
    <nameField>
        <label>Strategic Reports Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/classes/Report_Controller.cls
/****
*@description Controller for the Strategic Reporting page
*
*@date 10/13/16
*@author KW
*
*@modified    12/1-2/16    KW more building
*
*@modified    1/12/17-1/13    KW ?
*@modified    1/23/17    KW    date filter class-->CoCap_Report_Filter_Controller 
*
*@group StrategicReports
*@group-content /ApexDocContent/StrategicReports/Report_Controller.htm
****/
public with sharing class Report_Controller{
    
    public Date DateStart{get;set;}
    public Date DateEnd{get;set;}
    
    public Report_Controller(ApexPages.StandardController controller) {    
    
        String Role = String.valueOf(userrole.name);    
    
        //start queries
        List<Client__c> clients = [SELECT AGE__c, CURRENT_AGE__c, Center__c, Clinician__c 
                                    FROM Client__c];
                                    
        System.debug(clients);
                                    
        List<Strategic_Reports__c> reportRecords = [SELECT
                                                        Client__c,
                                                        //age info
                                                        Age_Current_Age__c,
                                                        Age_Group__c,
                                                        Age_Group_0_4__c, Age_Group_5_9__c, Age_Group_10_12__c, Age_Group_13_17__c, Age_Group_18_21__c,
                                                        //gender info
                                                        Gender_Identity__c,
                                                        Gender_Female__c, Gender_Male__c, Gender_Missing__c, Gender_Other__c, Gender_Refused_or_Unknown__c, Gender_Transgender__c,
                                                        //ethnicity info
                                                        Ethnic_Group__c,
                                                        Ethnicity_Hispanic_or_Latino__c, Ethnicity_Missing__c, Ethnicity_Non_Hispanic__c, Ethnicity_Refused_or_Unknown__c,
                                                        //race info
                                                        Race__c,
                                                        Race_American_Indian_or_Alaskan_Native__c, Race_Asian__c, Race_Black_African_American__c, Race_Multiracial__c, Race_Native_Hawaiian_or_Pacific_Islander__c, Race_Refused_or_Unknown__c, Race_White__c,
                                                        //military info
                                                        Military_Associated__c, 
                                                        //services info
                                                        Treatment_Completed_as_Planned__c, Treatment_Ended__c, Treatment_Missing__c 
                                                    FROM Strategic_Reports__c
                                                    WHERE Client__c IN:clients
                                                    ];                     
                                                    System.debug(reportRecords);
                                                    System.debug(reportRecords.size());
                          
        System.debug(reportRecords);
        Map<String,Boolean> tfMap = new Map<String,Boolean>();
                          
        for(Strategic_Reports__c r: reportRecords){
            tfMap.put('0-4', r.Age_Group_0_4__c);
            tfMap.put('5-9', r.Age_Group_5_9__c);
            tfMap.put('10-12', r.Age_Group_10_12__c);
            tfMap.put('13-17', r.Age_Group_13_17__c);
            tfMap.put('18-21', r.Age_Group_18_21__c);
            tfMap.put('female', r.Gender_Female__c);
            tfMap.put('male', r.Gender_Male__c);
            tfMap.put('gender missing', r.Gender_Missing__c);
            tfMap.put('gender other', r.Gender_Other__c);
            tfMap.put('gender refused', r.Gender_Refused_or_Unknown__c);
            tfMap.put('hispanic', r.Ethnicity_Hispanic_or_Latino__c);
            tfMap.put('non-hispanic', r.Ethnicity_Non_Hispanic__c);
            tfMap.put('ethnicity refused', r.Ethnicity_Refused_or_Unknown__c);
            tfMap.put('ethnicity missing', r.Ethnicity_Missing__c);
            tfMap.put('native', r.Race_American_Indian_or_Alaskan_Native__c);
            tfMap.put('asia', r.Race_Asian__c);
            tfMap.put('black', r.Race_Black_African_American__c);
            tfMap.put('island', r.Race_Native_Hawaiian_or_Pacific_Islander__c);
            tfMap.put('white', r.Race_White__c);
            tfMap.put('race refused', r.Race_Refused_or_Unknown__c);
            tfMap.put('multi', r.Race_Multiracial__c);
            tfMap.put('military', r.Military_Associated__c);
          //  tfMap.put('military missing', r.Military_Missing__c);
            tfMap.put('ended', r.Treatment_Ended__c);
            tfMap.put('as planned', r.Treatment_Completed_as_Planned__c);
            tfMap.put('treatment missing', r.Treatment_Missing__c);            
        }                                            
        System.debug(tfMap);
                                       
    }
    public pageReference enterStartDate(){
        DateStart = Date.valueOf(Strategic_Reports__c.DateStart__c);
        System.debug(DateStart);
        return null;
    }
    public pageReference enterEndDate(){
        DateEnd = Date.valueOf(Strategic_Reports__c.DateEnd__c);
        System.debug(DateEnd);
        return null;
    }
    public PageReference runCoCap(){
        enterStartDate();
        enterEndDate();
        return null;
    }

}