Kelsey Development Sandbox/src/objects/Center__c.object
<CustomObject>
    <label>Center</label>
    <nameField>
        <label>Center ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>AGE__c</fullName>
        <label>Age</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CENTER__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Center</label>
        <referenceTo>Center__c</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CURRENT_AGE__c</fullName>
        <description>Current age =( today&apos;s date - date of birth)/365 days</description>
        <formula>FLOOR((TODAY() - DOB1__c)/365.2425)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CURRENT_AGE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Clinician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinician ID</label>
        <referenceTo>Clinician__c</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>INIT__c</fullName>
        <label>INITIALS</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/Clinician__c.object
<CustomObject>
    <fields>
        <fullName>Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Center</label>
        <referenceTo>Center__c</referenceTo>
        <relationshipLabel>Clinicians</relationshipLabel>
        <relationshipName>Clinicians</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Clinician</label>
    <nameField>
        <label>Clinician ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinicians</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_Background_Family_Info_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BIDENT__c</fullName>
        <description>What is the child&apos;s current gender identity (for clients 5 or older)?</description>
        <label>BIDENT</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>98</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BMILFAMILY__c</fullName>
        <description>Is anyone in your child&apos;s family or someone close to you currently serving on active duty in or retired/separated from the Armed Forces, the Reserves or the National Guard</description>
        <label>BMILFAMILY</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BMILSELF__c</fullName>
        <description>Are you currently serving on active duty in the Armed Forces, the Reserves, or the National Guard</description>
        <label>BMILSELF</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Background Family Info B</relationshipLabel>
        <relationshipName>DS_Background_Family_Info_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ETHNIC__c</fullName>
        <description>Child&apos;s ethnicity</description>
        <label>ETHNIC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RAKNTV__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Alaska Native</description>
        <label>RAKNTV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RASIANIN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Asian Indian</description>
        <label>RASIANIN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RBLACK__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Black/African American</description>
        <label>RBLACK</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RCHINESE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Chinese</description>
        <label>RCHINESE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RFILIPINO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Filipino</description>
        <label>RFILIPINO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RGUAM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Guamanian or Chamorro</description>
        <label>RGUAM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RHAWAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Native Hawaiian</description>
        <label>RHAWAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RINDIAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is American Indian</description>
        <label>RINDIAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RJAPANESE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Japanese</description>
        <label>RJAPANESE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RKOREAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Korean</description>
        <label>RKOREAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ROASIAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Other Asian</description>
        <label>ROASIAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ROPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Other Pacific Islander</description>
        <label>ROPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RREF__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Refused to Answer</description>
        <label>RREF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSAMOA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Samoan</description>
        <label>RSAMOA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RUNK__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Unknown</description>
        <label>RUNK</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RVIETNAMESE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Vietnamese</description>
        <label>RVIETNAMESE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RWHITE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is White</description>
        <label>RWHITE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>DS Background Family Info B</label>
    <nameField>
        <label>DS Background Family Info B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Background Family Info B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_Background_Family_Info_F__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <formula>Baseline_ID__r.BDOV__c</formula>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Background Family Info F</relationshipLabel>
        <relationshipName>DS_Background_Family_Info_F</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;1&apos;</defaultValue>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>DS Background Family Info F</label>
    <nameField>
        <label>DS Background Family Info F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Background Family Info F</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_CBCL_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <formula>Background_ID__r.BDOV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS CBCL B</relationshipLabel>
        <relationshipName>DS_CBCL_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>SECTION</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>DS CBCL B</label>
    <nameField>
        <displayFormat>CBCL-B-{000000}</displayFormat>
        <label>DS CBCL B ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS CBCL B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/classes/Cocap_no5_Controller.cls
/****
*@description another cocap mockup
*
*@date    2/14/17
*@author    KW
****/
public with sharing class Cocap_no5_Controller {

    //start and end dates entered
    public Date StartDate{get;set;}
    public Date EndDate{get;set;}
        
   //all data queries
    public List<Client__c> clients{get;set;}
    public List<DS_Background_Family_Info_B__c> backgroundBs{get;set;}
    public List<DS_Background_Family_Info_F__c> backgroundFs{get;set;}
    public List<DS_CBCL_B__c> cbclBs {get;set;}
    
    //classses for subcategories
    public List<genderClass> genderRecs{get;set;}
    
    //counts
    //age
    public Integer countAge0_4{get;set;}
    public Integer countAge5_9{get;set;}
    public Integer countAge10_12{get;set;}
    public Integer countAge13_17{get;set;}
    public Integer countAge18_21{get;set;}
    //gender
    public Integer countGenMale{get;set;}
    public Integer countGenFemale{get;set;}
    public Integer countGenTrans{get;set;}
    public Integer countGenOther{get;set;}
    public Integer countGenRef_Unk{get;set;}
    public Integer countGenMissing{get;set;}
    //ethnic
    public Integer countEthHispanic{get;set;}
    public Integer countEthNon_Hisp{get;set;}
    public Integer countEthRef_Unk{get;set;}
    public Integer countEthMissing{get;set;}
    //race
    public Integer countRaceNat_Amer{get;set;}
    public Integer countRaceAsian{get;set;}
    public Integer countRaceBlack{get;set;}
    public Integer countRaceIsland{get;set;}
    public Integer countRaceWhite{get;set;}
    public Integer countRaceMulti{get;set;}
    public Integer countRaceRef_Unk{get;set;}
    //service-related
    public Integer countNew{get;set;}
    public Integer countService{get;set;}
    public Integer countClinical{get;set;}
    public Integer countEnded{get;set;}
    public Integer countEnded_Planned{get;set;}
    //military
    public Integer countMilYes{get;set;}
    public Integer countMilNo{get;set;}
    public Integer countMilMissing{get;set;}       
         
    public class genderClass{
      //  public String genderClassString{get;set;}
      
        public String cid{get;set;}
        
        public String genIdentity{get;set;}        
        
        public Boolean genMale{get;set;}
        public Boolean genFemale{get;set;} 
        public Boolean genTrans{get;set;}
        public Boolean genOther{get;set;} 
        public Boolean genUnknown{get;set;}
        public Boolean genMissing{get;set;}        
        
        
        public genderClass(String cliId, List<DS_Background_Family_Info_B__c> backgroundBs){//List<Client__c> clients, 
            
            System.debug(cliId);
            String cid;
            
            String genIdentity;
            genMale= FALSE;
            genFemale= FALSE;
            genTrans= FALSE;
            genOther= FALSE;
            genUnknown= FALSE;
            genMissing= FALSE;
                        
            System.debug(cid);
            System.debug(genIdentity);
            System.debug(genMale);
            System.debug(genFemale);
            System.debug(genTrans);
            System.debug(genOther);
            System.debug(genUnknown);
            System.debug(genMissing);
                
                for(DS_Background_Family_Info_B__c b: backgroundBs){                
                    
                    System.debug(cid);
                    System.debug(genIdentity);
                    System.debug(genMale);
                    System.debug(genFemale);
                    System.debug(genTrans);
                    System.debug(genOther);
                    System.debug(genUnknown);
                    System.debug(genMissing);
            
                    String bid = String.valueOf(b.Client__c);
                    System.debug(bid);
                  //      if(bid ==cid){ 
                            
                           Integer genId = Integer.valueOf(b.get('BIDENT__c'));
                               
                            if(genId == 1){
                                genIdentity = 'Male';
                                genMale = TRUE;
                            }
                            else if(genId == 2){
                                genIdentity = 'Female';
                                genFemale = TRUE;
                            }
                            else if((genId == 3) || (genId == 4)){
                                genIdentity = 'Transgender';
                                genTrans = TRUE;
                            }
                            else if(genId == 98){
                                genIdentity = 'Other';
                                genOther = TRUE;
                            }
                            else if((genId == 96) || (genId == 99)){
                                genIdentity = 'Unknown or declined to provide';
                                genUnknown = TRUE;
                            }
                            else{
                                genIdentity = 'Gender Identity is Missing';
                                genMissing = TRUE;
                            }
                    this.cid = bid;
                    this.genIdentity = genIdentity; 
                    this.genMale = genMale ; 
                    this.genFemale = genFemale ; 
                    this.genTrans = genTrans ; 
                    this.genOther = genOther ; 
                    this.genUnknown = genUnknown ; 
                    this.genMissing = genMissing ; 
                    
                    }       
        }
    }

    public PageReference getData(){
    
        Integer countGenMale =0;
        Integer countGenFemale =0;
        Integer countGenTrans =0;
        Integer countGenOther =0;
        Integer countGenRef_Unk =0 ;
        Integer countGenMissing=0;
    
        List<Client__c> clients = getClients();//get client
        Client__c client;
        String cliId;
        System.debug(StartDate);
        System.debug(EndDate);
        List<DS_Background_Family_Info_B__c> backgroundBs;//= getBackBs(cliId, StartDate, EndDate);     
       // List<DS_Background_Family_Info_F__c> backgroundFs= getBackFs(clients);
        //List<DS_CBCL_B__c> cbclBs=getCbclBs(clients);
        List<genderClass> genderRecs = new List<genderClass>();
        System.debug(clients);
        System.debug(StartDate);
        System.debug(EndDate);
        System.debug(clients);
        System.debug(backgroundBs);
    //    System.debug(backgroundFs);
     //   System.debug(cbclBs);
        
        for(Client__c c : clients){ 
            cliId = String.valueOf(c.id);
            backgroundBs= getBackBs(cliId, StartDate, EndDate);
            genderClass g = new genderClass(cliId, backgroundBs);//clients
            System.debug(g);
            genderRecs.add(g); 
        }
        System.debug(genderRecs);
        System.debug(genderRecs.size());
        
        for(genderClass g:genderRecs){
            if(g.genFemale == TRUE){
                countGenFemale = countGenFemale + 1;
            }
           // countGenFemale = countGenFemale +Integer.valueOf(g.genFemale);  
            System.debug(countGenFemale );
            System.debug(g.genFemale);
        }
        System.debug(countGenFemale );
//        countGenFemale = Apexpages.currentPage().getParameters().set('totFemale');
        PageReference getFemaleCount = new PageReference('countGenFemale') ;
        return getFemaleCount;
        return null;
    }
    public PageReference getFemaleCount(){
        System.debug(countGenFemale);
        return null;
    }
        

    public Cocap_no5_Controller(ApexPages.StandardController controller) {
    
        System.debug(StartDate);
        System.debug(genderRecs);
        getFemaleCount();
    }
    

    
    public List<Client__c> getClients(){
       // return getClients(); 
        List<Client__c> clients = [SELECT id, Clinician__c, Center__c, Age__c, CURRENT_AGE__c, INIT__c
                                    FROM Client__c];
        System.debug(clients);
        return clients;
    }
    
    public List<DS_Background_Family_Info_B__c> getBackBs(String cliId, Date StartDate, Date EndDate){
        System.debug(cliId);
        System.debug(StartDate);
        System.debug(EndDate);
        
        List<DS_Background_Family_Info_B__c>  backgroundBs = [SELECT name, Client__c, SECTION__c,BDOV__c,
                                                            BMILFAMILY__c, BMILSELF__c,
                                                            BIDENT__c, 
                                                            ETHNIC__c,
                                                            RINDIAN__c, RAKNTV__c, 
                                                            RASIANIN__c, RCHINESE__c, RFILIPINO__c, RJAPANESE__c, RKOREAN__c, RVIETNAMESE__c, ROASIAN__c,
                                                            RBLACK__c,
                                                            RHAWAN__c, RGUAM__c, RSAMOA__c, ROPI__c,
                                                            RWHITE__c,
                                                            RREF__c, RUNK__c  
                                                            FROM DS_Background_Family_Info_B__c  
                                                            WHERE Client__c  =:  cliId
                                                            AND BDOV__c >=: StartDate 
                                                            AND BDOV__c <=: EndDate];
        System.debug(backgroundBs);
        System.debug(backgroundBs.size());
        return(backgroundBs);
    }
}