Kelsey Development Sandbox/src/objects/Center__c.object
<CustomObject>
    <label>Center</label>
    <nameField>
        <label>Center ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>AGE__c</fullName>
        <label>Age</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CENTER__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Center</label>
        <referenceTo>Center__c</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CURRENT_AGE__c</fullName>
        <description>Current age =( today&apos;s date - date of birth)/365 days</description>
        <formula>FLOOR((TODAY() - DOB1__c)/365.2425)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CURRENT_AGE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Clinician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinician ID</label>
        <referenceTo>Clinician__c</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>INIT__c</fullName>
        <label>INITIALS</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/Clinician__c.object
<CustomObject>
    <fields>
        <fullName>Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Center</label>
        <referenceTo>Center__c</referenceTo>
        <relationshipLabel>Clinicians</relationshipLabel>
        <relationshipName>Clinicians</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Clinician</label>
    <nameField>
        <label>Clinician ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinicians</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_Background_Family_Info_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BIDENT__c</fullName>
        <description>What is the child&apos;s current gender identity (for clients 5 or older)?</description>
        <label>BIDENT</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>98</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BMILFAMILY__c</fullName>
        <description>Is anyone in your child&apos;s family or someone close to you currently serving on active duty in or retired/separated from the Armed Forces, the Reserves or the National Guard</description>
        <label>BMILFAMILY</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BMILSELF__c</fullName>
        <description>Are you currently serving on active duty in the Armed Forces, the Reserves, or the National Guard</description>
        <label>BMILSELF</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Background Family Info B</relationshipLabel>
        <relationshipName>DS_Background_Family_Info_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ETHNIC__c</fullName>
        <description>Child&apos;s ethnicity</description>
        <label>ETHNIC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RAKNTV__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Alaska Native</description>
        <label>RAKNTV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RASIANIN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Asian Indian</description>
        <label>RASIANIN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RBLACK__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Black/African American</description>
        <label>RBLACK</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RCHINESE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Chinese</description>
        <label>RCHINESE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RFILIPINO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Filipino</description>
        <label>RFILIPINO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RGUAM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Guamanian or Chamorro</description>
        <label>RGUAM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RHAWAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Native Hawaiian</description>
        <label>RHAWAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RINDIAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is American Indian</description>
        <label>RINDIAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RJAPANESE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Japanese</description>
        <label>RJAPANESE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RKOREAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Korean</description>
        <label>RKOREAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ROASIAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Other Asian</description>
        <label>ROASIAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ROPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Other Pacific Islander</description>
        <label>ROPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RREF__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Refused to Answer</description>
        <label>RREF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSAMOA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Samoan</description>
        <label>RSAMOA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RUNK__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Unknown</description>
        <label>RUNK</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RVIETNAMESE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Vietnamese</description>
        <label>RVIETNAMESE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RWHITE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is White</description>
        <label>RWHITE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>DS Background Family Info B</label>
    <nameField>
        <label>DS Background Family Info B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Background Family Info B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/classes/CoCap_v3_Controller.cls
/****
*@description mockup of cocap reporting page
*
*@date    1/23/17
*@author    KW
****/
public with sharing class CoCap_v3_Controller {

    public PageReference runQuery() {
        DisplayRecords();
        System.debug(backBs);
        System.debug(StartDate);
        System.debug(clients);
        
        return null;
    }

    public PageReference getDates(){
        System.debug(StartDate);//Date StartDate = Date.valueOf(Apexpages.currentPage().getParameters().get('StartDate'));
        System.debug(EndDate);//Date EndDate = Date.valueOf(Apexpages.currentPage().getParameters().get('EndDate'));
        
        COCAPRaw r = new COCAPRaw();
        COCAPParsed p = new COCAPParsed();
        
        List<COCAPParsed> parsedList = new List<COCAPParsed>();
           List<SObject> backBs = [SELECT name, Client__c, SECTION__c,
                            BDOV__c, 
                            BMILFAMILY__c, BMILSELF__c, 
                            BIDENT__c, 
                            ETHNIC__c,
                            RINDIAN__c, RAKNTV__c, 
                            RASIANIN__c, RCHINESE__c, RFILIPINO__c, RJAPANESE__c, RKOREAN__c, RVIETNAMESE__c, ROASIAN__c,
                            RBLACK__c,
                            RHAWAN__c, RGUAM__c, RSAMOA__c, ROPI__c,
                            RWHITE__c,
                            RREF__c, RUNK__c
                        FROM DS_Background_Family_Info_B__c
                        WHERE Client__c  IN :  clients
                        AND BDOV__c >=:StartDate];  
            System.debug(backBs);
            SObject backB;
        return null;
    }
   /* public PageReference getBackground(){
        getDates();
        return null;
    }*/
public Date StartDate{get;set;} //= Date.valueOf(Apexpages.currentPage().getParameters().get('StartDate'));
public Date EndDate{get;set;}// = Date.valueOf(Apexpages.currentPage().getParameters().get('EndDate'));

public List<Client__c> clients{get;set;}

public List<COCAPParsed> parsedList{get;set;}

public SObject backB{get;set;}
public List<SObject> backBs{get;set;}
public List<DS_Background_Family_Info_B__c> backgroundBList{get;set;}

public Integer totalMale{get;set;}
public Integer totalFemale{get;set;}
public Integer totalTrans{get;set;}
public Integer totalUnkGen{get;set;}
public Integer totalMissingGen{get;set;}

public Boolean genMale{get;set;}
public Boolean genFemale{get;set;}
public Boolean genTrans{get;set;}
public Boolean genOther{get;set;}
public Boolean genUnknown{get;set;}
public Boolean genMissing{get;set;}
public Integer genId{get;set;}
public String genIdentity{get;set;}
    //group dates?
    //group cocap raw info
    //group cocap final answers?
    
    public class COCAPDates{
        public String cocapDatesRecord{get;set;}
        
        public Date StartDate{get;set;}
        public Date EndDate{get;set;}
                
        public COCAPDates(){
            this.cocapDatesRecord = null;
        }
    }
    
    public class COCAPRaw{
        public String cocapRawRecord{get;set;}
        
        public List<SObject> backBs{get;set;}
        
        public COCAPRaw(){
            this.cocapRawRecord = null;
        }
    }
    
    public class COCAPParsed{
//        COCAPDates();
        String cocapParsedRecord{get;set;}
        
        public String client{get;set;}
        public String genIdentity{get;set;}
        
        public COCAPParsed(){
            this.cocapParsedRecord = null;
        }
    }
    
    public CoCap_v3_Controller(ApexPages.StandardController controller) {
            
        StartDate = StartDate;
        EndDate = EndDate;
        System.debug(StartDate);
        System.debug(EndDate);
       // InitData();
        
    }
        //public void InitData(){
        public PageReference InitData(){
                      
        COCAPDates c = new COCAPDates();
        COCAPRaw r = new COCAPRaw();
        COCAPParsed p = new COCAPParsed();
        List<COCAPParsed> parsedList = new List<COCAPParsed>();
        
        //clients info
        List<Client__c> clients = [SELECT id, Clinician__c, Center__c, Age__c, CURRENT_AGE__c, INIT__c
                                    FROM Client__c
                                    ];//where allowed by role
        System.debug(clients);
        
        List<SObject> backBs = [SELECT name, Client__c, SECTION__c,
                            BDOV__c, 
                            BMILFAMILY__c, BMILSELF__c, 
                            BIDENT__c, 
                            ETHNIC__c,
                            RINDIAN__c, RAKNTV__c, 
                            RASIANIN__c, RCHINESE__c, RFILIPINO__c, RJAPANESE__c, RKOREAN__c, RVIETNAMESE__c, ROASIAN__c,
                            RBLACK__c,
                            RHAWAN__c, RGUAM__c, RSAMOA__c, ROPI__c,
                            RWHITE__c,
                            RREF__c, RUNK__c
                        FROM DS_Background_Family_Info_B__c
                        WHERE Client__c  IN :  clients
                        AND BDOV__c >=:StartDate];   
                        
            System.debug(backBs);
                        
            for(SObject backB : backBs){
                System.debug(backB.get('Client__c'));
                findGender(backB);
                System.debug(genIdentity);
                p.client  = String.valueOf(backB.get('Client__c'));
                p.genIdentity = genIdentity;
                System.debug(p);
               // 
            }
//            parsedList.add(p);
  //          System.debug(parsedList);
    //        System.debug(parsedList.size());
            System.debug(p);
            r.backBs = backBs;
            System.debug(r);
            return null;
    }
    
    public void DisplayRecords(){
    
    COCAPDates c = new COCAPDates();
        
        System.debug(StartDate);
        System.debug(EndDate);
            
        //start    
        if(StartDate!=null){
            Boolean sumbitDates = true;
            c.StartDate=StartDate;
        }        
        else{
            Boolean submitDates=false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No start date'));
        }
        
        //end
        if(EndDate != null){    
            Boolean sumbitDates = true;
            c.EndDate= EndDate;
        }
        else{
            Boolean submitDates=false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No end date'));
        }
        
        System.debug(c);
       // runQuery();
        //getBackground();
        
        COCAPParsed p = new COCAPParsed();
        System.debug(p);
        System.debug(backB);
        
    }
        
    public void findGender(SObject backB){
    
        genMale = FALSE;
        genFemale = FALSE;
        genTrans = FALSE;
        genOther = FALSE;
        genUnknown = FALSE;
        genMissing = FALSE;
       Integer genId = Integer.valueOf(backB.get('BIDENT__c'));
       //if null? use gender?
       
        if(genId == 1){
            genIdentity = 'Male';
            genMale = TRUE;
        }
        else if(genId == 2){
            genIdentity = 'Female';
            genFemale = TRUE;
        }
        else if((genId == 3) || (genId == 4)){
            genIdentity = 'Transgender';
            genTrans = TRUE;
        }
        else if(genId == 98){
            genIdentity = 'Other';
            genOther = TRUE;
        }
        else if((genId == 96) || (genId == 99)){
            genIdentity = 'Unknown or declined to provide';
            genUnknown = TRUE;
        }
        else{
            genIdentity = 'Gender Identity is Missing';
            genMissing = TRUE;
        }
        System.debug(genIdentity);
    
    }
}