Kelsey Development Sandbox/src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>AGE__c</fullName>
        <label>Age</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CENTER__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Center</label>
        <referenceTo>Center__c</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CURRENT_AGE__c</fullName>
        <description>Current age =( today&apos;s date - date of birth)/365 days</description>
        <formula>FLOOR((TODAY() - DOB1__c)/365.2425)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CURRENT_AGE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Clinician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinician ID</label>
        <referenceTo>Clinician__c</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FDOV__c</fullName>
        <formula>Followup__r.FDOV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>INIT__c</fullName>
        <label>INITIALS</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/Clinician__c.object
<CustomObject>
    <fields>
        <fullName>Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Center</label>
        <referenceTo>Center__c</referenceTo>
        <relationshipLabel>Clinicians</relationshipLabel>
        <relationshipName>Clinicians</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Clinician</label>
    <nameField>
        <label>Clinician ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinicians</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_Background_Family_Info_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BIDENT__c</fullName>
        <description>What is the child&apos;s current gender identity (for clients 5 or older)?</description>
        <label>BIDENT</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>98</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BMILFAMILY__c</fullName>
        <description>Is anyone in your child&apos;s family or someone close to you currently serving on active duty in or retired/separated from the Armed Forces, the Reserves or the National Guard</description>
        <label>BMILFAMILY</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BMILSELF__c</fullName>
        <description>Are you currently serving on active duty in the Armed Forces, the Reserves, or the National Guard</description>
        <label>BMILSELF</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Background Family Info B</relationshipLabel>
        <relationshipName>DS_Background_Family_Info_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ETHNIC__c</fullName>
        <description>Child&apos;s ethnicity</description>
        <label>ETHNIC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RAKNTV__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Alaska Native</description>
        <label>RAKNTV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RASIANIN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Asian Indian</description>
        <label>RASIANIN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RBLACK__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Black/African American</description>
        <label>RBLACK</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RCHINESE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Chinese</description>
        <label>RCHINESE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RFILIPINO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Filipino</description>
        <label>RFILIPINO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RGUAM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Guamanian or Chamorro</description>
        <label>RGUAM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RHAWAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Native Hawaiian</description>
        <label>RHAWAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RINDIAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is American Indian</description>
        <label>RINDIAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RJAPANESE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Japanese</description>
        <label>RJAPANESE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RKOREAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Korean</description>
        <label>RKOREAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ROASIAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Other Asian</description>
        <label>ROASIAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ROPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Other Pacific Islander</description>
        <label>ROPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RREF__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Refused to Answer</description>
        <label>RREF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSAMOA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Samoan</description>
        <label>RSAMOA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RUNK__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Unknown</description>
        <label>RUNK</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RVIETNAMESE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Vietnamese</description>
        <label>RVIETNAMESE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RWHITE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is White</description>
        <label>RWHITE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>DS Background Family Info B</label>
    <nameField>
        <label>DS Background Family Info B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Background Family Info B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_Background_Family_Info_F__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <formula>Baseline_ID__r.BDOV__c</formula>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Background Family Info F</relationshipLabel>
        <relationshipName>DS_Background_Family_Info_F</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FDOV__c</fullName>
        <description>1. Followup Date of visit</description>
        <label>FDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FETSTAT__c</fullName>
        <description>3. End of treatment status</description>
        <label>FETSTAT</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>98</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FUTYPE__c</fullName>
        <description>3. Followup visit Type</description>
        <label>FUTYPE</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>98</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;1&apos;</defaultValue>
        <label>SECTION</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>DS Background Family Info F</label>
    <nameField>
        <label>DS Background Family Info F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Background Family Info F</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_CBCL_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <formula>Background_ID__r.BDOV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS CBCL B</relationshipLabel>
        <relationshipName>DS_CBCL_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SECTION__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>SECTION</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>DS CBCL B</label>
    <nameField>
        <displayFormat>CBCL-B-{000000}</displayFormat>
        <label>DS CBCL B ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS CBCL B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/classes/CoCap_v4_Controller.cls
public with sharing class CoCap_v4_Controller {
    
    //external processing class initialization
   // public ReportBuilder rb;//on class first
    
    //start and end dates entered
    public Date StartDate{get;set;}
    public Date EndDate{get;set;}
    
   //all data queries
    public List<Client__c> clients{get;set;}
    public List<DS_Background_Family_Info_B__c> backgroundBs{get;set;}
    public List<DS_Background_Family_Info_F__c> backgroundFs{get;set;}
    public List<DS_CBCL_B__c> cbclBs {get;set;}
    
    public List<cocapRec> CocapRecordList {get;set;}
    public Map<String, List<cocapRec>> cocapMap {get;set;} 
    
    public class cocapRec{
        public String cocapRecString{get;set;}      
        
            //client info
          //  public String clientId;
            //age info
            //Integer cAge; 
            public String  ageGroup;
            public Boolean age0_4; 
            public Boolean age5_9; 
            public Boolean age10_12; 
            public Boolean age13_17; 
            public Boolean age18_21;
            //gender info
            public String  genIdentity;  
            public Boolean genMale; 
            public Boolean genFemale; 
            public Boolean genTrans; 
            public Boolean genOther;  
            public Boolean genUnknown;  
            public Boolean genMissing;
            //ethnicity info
            public String ethnicGroup;  
            public Boolean ethnicHispanic; 
            public Boolean ethnicNonHispanic;  
            public Boolean ethnicUnknown;  
            public Boolean ethnicMissing; 
            //race info
            public String  raceGroup;  
            public Boolean raceBlack;  
            public Boolean raceWhite;  
            public Boolean raceAINAK; 
            public Boolean raceAsian;  
            public Boolean raceHIOPI;  
            public Boolean raceUnkNR;  
            public Boolean raceMulti;  
            //military info
            public Boolean milAssociated; 
            //services info
            public Boolean treatMissing;  
            public Boolean treatEnded; 
            public Boolean treatAsPlanned;
        
        public cocapRec(){
            this.cocapRecString = null;
        }
                                                    
    }
    
    public CoCap_v4_Controller(ApexPages.StandardController controller) {
   // ReportBuilder rb = new ReportBuilder();
    cocapRec p = new cocapRec();
        
        System.debug(StartDate);
        System.debug(EndDate);
        System.debug(clients);
        System.debug(backgroundBs);
        System.debug(backgroundFs);
            
    }       
 
    public PageReference getData(){
        cocapRec p = new cocapRec();
        List<cocapRec> l = new List<cocapRec>();
    
        List<Client__c> clients = getClients();//get client
        List<DS_Background_Family_Info_B__c> backgroundBs= getBackBs(clients);     
        List<DS_Background_Family_Info_F__c> backgroundFs= getBackFs(clients);
        List<DS_CBCL_B__c> cbclBs=getCbclBs(clients);
        System.debug(clients);
        System.debug(StartDate);
        System.debug(EndDate);
        System.debug(clients);
        System.debug(backgroundBs);
        System.debug(backgroundFs);
        System.debug(cbclBs);
        System.debug(CocapRecordList);
        
        findGender(backgroundBs);
        genderMapList(clients, backgroundBs);
        System.debug(l);
        return null;
    }
    ////////////////////////////////////////////
    public Map<String, List<Boolean>> genderMapList(List<Client__c> clients, List<DS_Background_Family_Info_B__c> backgroundBs){
        System.debug(clients);
        System.debug(backgroundBs);
        
        List<String> genderList= new List<String>();
        String genderidentity; 
        
        Boolean genMale; 
        Boolean genFemale; 
        Boolean genTrans; 
        Boolean genOther;  
        Boolean genUnknown;  
        Boolean genMissing;
        
        for(Client__c c:clients){
            for(DS_Background_Family_Info_B__c b: backgroundBs){
                if(c.id == b.get('Client__c')){
                   Integer genId = Integer.valueOf(b.get('BIDENT__c'));
                       
                    if(genId == 1){
                        genderidentity = 'Male';
                        genMale = TRUE;
                    }
                    else if(genId == 2){
                        genderidentity = 'Female';
                        genFemale = TRUE;
                    }
                    else if((genId == 3) || (genId == 4)){
                        genderidentity = 'Transgender';
                        genTrans = TRUE;
                    }
                    else if(genId == 98){
                        genderidentity = 'Other';
                        genOther = TRUE;
                    }
                    else if((genId == 96) || (genId == 99)){
                        genderidentity = 'Unknown or declined to provide';
                        genUnknown = TRUE;
                    }
                    else{
                        genderidentity = 'Gender Identity is Missing';
                        genMissing = TRUE;
                    }
                /*    genderList.add(Boolean.valueOf(genMale));
                    genderList.add(genFemale);
                    genderList.add(genTrans);
                    genderList.add(genOther);
                    genderList.add(genUnknown);
                    genderList.add(genMissing );*/
                }
            }
        }
        System.debug(genderidentity);
        System.debug(genderList);
//        genderMapList.put(genderidentity, genderList);
       // Map<String, List<Boolean>> genderListMap = genderMapList;
        
//        return genderListMap<>(genderMapList);//genderidentity, genderList>();
return null;
    }
    
    public void findGender(List<DS_Background_Family_Info_B__c> backgroundBs){
    
        cocapRec p = new cocapRec();
        List<cocapRec> l = new List<cocapRec>();
        System.debug(p);
        System.debug(l);
        
        for(DS_Background_Family_Info_B__c b: backgroundBs){
            
           Integer genId = Integer.valueOf(b.get('BIDENT__c'));
               
            if(genId == 1){
                p.genIdentity = 'Male';
                p.genMale = TRUE;
            }
            else if(genId == 2){
                p.genIdentity = 'Female';
                p.genFemale = TRUE;
            }
            else if((genId == 3) || (genId == 4)){
                p.genIdentity = 'Transgender';
                p.genTrans = TRUE;
            }
            else if(genId == 98){
                p.genIdentity = 'Other';
                p.genOther = TRUE;
            }
            else if((genId == 96) || (genId == 99)){
                p.genIdentity = 'Unknown or declined to provide';
                p.genUnknown = TRUE;
            }
            else{
                p.genIdentity = 'Gender Identity is Missing';
                p.genMissing = TRUE;
            }
            System.debug(p.genIdentity );
            System.debug(p);
            l.add(p);
        }
        System.debug(l);
       // return l;
    }
  //////////////////////////////////////////////////////////////  

    public List<Client__c> getClients(){
       // return getClients(); 
        List<Client__c> clients = [SELECT id, Clinician__c, Center__c, Age__c, CURRENT_AGE__c, INIT__c
                                    FROM Client__c];
        System.debug(clients);
        return clients;
    }
    
    public List<DS_Background_Family_Info_B__c> getBackBs(List<Client__c> clients){
        System.debug(clients);
        System.debug(StartDate);
        System.debug(EndDate);
        
        List<DS_Background_Family_Info_B__c>  backgroundBs = [SELECT name, Client__c, SECTION__c,BDOV__c,
                                                            BMILFAMILY__c, BMILSELF__c,
                                                            BIDENT__c, 
                                                            ETHNIC__c,
                                                            RINDIAN__c, RAKNTV__c, 
                                                            RASIANIN__c, RCHINESE__c, RFILIPINO__c, RJAPANESE__c, RKOREAN__c, RVIETNAMESE__c, ROASIAN__c,
                                                            RBLACK__c,
                                                            RHAWAN__c, RGUAM__c, RSAMOA__c, ROPI__c,
                                                            RWHITE__c,
                                                            RREF__c, RUNK__c  
                                                            FROM DS_Background_Family_Info_B__c  
                                                            WHERE Client__c  IN :  clients];
        System.debug(backgroundBs);
        return(backgroundBs);
    }
    
    public List<DS_Background_Family_Info_F__c> getBackFs(List<Client__c> clients){
        System.debug(clients);
        System.debug(StartDate);
        System.debug(EndDate);
        
        List<DS_Background_Family_Info_F__c>  backgroundFs = [SELECT name, Client__c, SECTION__c,FDOV__c ,FUTYPE__c, FETSTAT__c, FMSTAT__c 
                                                            FROM DS_Background_Family_Info_F__c  
                                                            WHERE Client__c  IN :  clients];
        System.debug(backgroundFs);
        return(backgroundFs);
    }
    
    public List<DS_CBCL_B__c> getCbclBs(List<Client__c> clients){
        List<DS_CBCL_B__c> cbclBs = [SELECT Client__c,BDOACO__c, BDOACY__c
                                FROM DS_CBCL_B__c
                                WHERE Client__c  IN: clients];
        return(cbclBs);
    }
}