Kelsey Development Sandbox/src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>CURRENT_AGE__c</fullName>
        <description>Current age =( today&apos;s date - date of birth)/365 days</description>
        <formula>FLOOR((TODAY() - DOB1__c)/365.2425)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CURRENT_AGE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_Background_Family_Info_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BIDENT__c</fullName>
        <description>What is the child&apos;s current gender identity (for clients 5 or older)?</description>
        <label>BIDENT</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>98</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Background Family Info B</relationshipLabel>
        <relationshipName>DS_Background_Family_Info_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ETHNIC__c</fullName>
        <description>Child&apos;s ethnicity</description>
        <label>ETHNIC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>96</fullName>
                </value>
                <value>
                    <fullName>99</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RAKNTV__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Alaska Native</description>
        <label>RAKNTV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RASIANIN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Asian Indian</description>
        <label>RASIANIN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RBLACK__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Black/African American</description>
        <label>RBLACK</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RCHINESE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Chinese</description>
        <label>RCHINESE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RFILIPINO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Filipino</description>
        <label>RFILIPINO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RGUAM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Guamanian or Chamorro</description>
        <label>RGUAM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RHAWAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Native Hawaiian</description>
        <label>RHAWAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RINDIAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is American Indian</description>
        <label>RINDIAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RJAPANESE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Japanese</description>
        <label>RJAPANESE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RKOREAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Korean</description>
        <label>RKOREAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ROASIAN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Other Asian</description>
        <label>ROASIAN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ROPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Other Pacific Islander</description>
        <label>ROPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RREF__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Refused to Answer</description>
        <label>RREF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSAMOA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Samoan</description>
        <label>RSAMOA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RUNK__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Unknown</description>
        <label>RUNK</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RVIETNAMESE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Race is Vietnamese</description>
        <label>RVIETNAMESE</label>
        <type>Checkbox</type>
    </fields>
    <label>DS Background Family Info B</label>
    <nameField>
        <label>DS Background Family Info B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Background Family Info B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_Background_Family_Info_F__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <formula>Baseline_ID__r.BDOV__c</formula>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Baseline_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Baseline ID</label>
        <referenceTo>DS_Background_Family_Info_B__c</referenceTo>
        <relationshipLabel>DS Background Family Info F</relationshipLabel>
        <relationshipName>DS_Background_Family_Info_F</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS Background Family Info F</relationshipLabel>
        <relationshipName>DS_Background_Family_Info_F</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS Background Family Info F</label>
    <nameField>
        <label>DS Background Family Info F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS Background Family Info F</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_CBCL_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <formula>Background_ID__r.BDOV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS CBCL B</relationshipLabel>
        <relationshipName>DS_CBCL_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS CBCL B</label>
    <nameField>
        <displayFormat>CBCL-B-{000000}</displayFormat>
        <label>DS CBCL B ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS CBCL B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_CBCL_F__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS CBCL F</relationshipLabel>
        <relationshipName>DS_CBCL_F</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS CBCL F</label>
    <nameField>
        <label>DS CBCL F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS CBCL F</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_PTSD_CA_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <formula>Background_ID__r.BDOV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS PTSD CA B</relationshipLabel>
        <relationshipName>DS_PTSD_CA_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS PTSD CA B</label>
    <nameField>
        <label>DS PTSD CA B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS PTSD CA B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_PTSD_CA_F__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS PTSD CA F</relationshipLabel>
        <relationshipName>DS_PTSD_CA_F</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS PTSD CA F</label>
    <nameField>
        <label>DS PTSD CA F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS PTSD CA F</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_SDQ_PSI_CDI_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <formula>Background_ID__r.BDOV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS SDQ PSI CDI B</relationshipLabel>
        <relationshipName>DS_SDQ_PSI_CDI_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS SDQ PSI CDI B</label>
    <nameField>
        <label>DS SDQ PSI CDI B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS SDQ PSI CDI B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_SDQ_PSI_CDI_F__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS SDQ PSI CDI F</relationshipLabel>
        <relationshipName>DS_SDQ_PSI_CDI_F</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS SDQ PSI CDI F</label>
    <nameField>
        <label>DS SDQ PSI CDI F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS SDQ PSI CDI F</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_TSCC_TSCYC_B__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <formula>Background_ID__r.BDOV__c</formula>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS TSCC TSCYC B</relationshipLabel>
        <relationshipName>DS_TSCC_TSCYC_B</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS TSCC TSCYC B</label>
    <nameField>
        <label>DS TSCC TSCYC B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS TSCC TSCYC B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_TSCC_TSCYC_F__c.object
<CustomObject>
    <fields>
        <fullName>BDOV__c</fullName>
        <formula>Background_ID__r.BDOV__c</formula>
        <label>BDOV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>DS TSCC TSCYC F</relationshipLabel>
        <relationshipName>DS_TSCC_TSCYC_F</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS TSCC TSCYC F</label>
    <nameField>
        <label>DS TSCC TSCYC F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS TSCC TSCYC F</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/classes/CoCap7_Controller.cls
/****
*@description another cocap mockup
*
*@date    2/15/17
*@author    KW
*
*@modified  3/3/17  KW  modify logic for clients with services
*
*@group cocap
*@group-content /ApexDocContent/Cocap7_Controller.htm
****/
public with sharing class CoCap7_Controller {
    
    //init start and end dates
    public Date StartDate{get;set;}
    public Date EndDate{get;set;}
    
    //lists of objects
    public List<DS_Background_Family_Info_B__c> backgroundBs{get;set;}
    public List<DS_Background_Family_Info_F__c> backgroundFs{get;set;}
    public List<DS_CBCL_B__c> cbclBs{get;set;}
    public List<DS_CBCL_F__c> cbclFs{get;set;}
    public List<DS_PTSD_CA_B__c> ptsdBs{get;set;}
    public List<DS_PTSD_CA_F__c> ptsdFs{get;set;}
    public List<DS_SDQ_PSI_CDI_B__c> sdqBs{get;set;}
    public List<DS_SDQ_PSI_CDI_F__c> sdqFs{get;set;}
    public List<DS_TSCC_TSCYC_B__c> tsccBs{get;set;}
    public List<DS_TSCC_TSCYC_F__c> tsccFs{get;set;}
    
    //records lists
    public List<clientRec> clientRecords{get;set;}
    public List<targetRec> genderRecords{get;set;}
    public List<targetRec> ageRecords{get;set;}
    public List<targetRec> ethnicRecords{get;set;}
    public List<targetRec> raceRecords{get;set;}
    public List<targetRec> milRecords{get;set;}
    public List<targetRec> newRecords{get;set;}
    
    //class for records
    public class targetRec{
        public String recLabel{get;set;}
        public Integer recValue{get;set;}
        public targetRec(){
            this.recLabel = null;
        }
    }
        
    //class for clients with services
    public class clientRec{
        public Id clientId{get;set;}
        public Date bdov{get;set;}
        public Integer CurrentAge{get;set;}
        public String gender{get;set;}
        public String ethnic{get;set;}
        public String race{get;set;}
        public String military{get;set;}
        public String txstatus{get;set;}
        public Date fdov{get;set;}
        /*public Date cbclDate{get;set;}
        public Date ptsdDate{get;set;}
        public Date sdqDate{get;set;}
        public Date tscDate{get;set;}*/
        public clientRec(){
            this.clientId = null;
        }
    }
            
    //there shouldn't be anything pre-loaded on page        
    public CoCap7_Controller(ApexPages.StandardController controller) {
    }
    
    //function run on click
    public void getData(){
        
        //get clients with services
        List<clientRec> clients = getClientServiceInfo();
        
        //get the lists of objects (start w/ back b/fs)
        
        //maps for records
        
        //lists of records
        
        //loops for each record type
    }
    
    public List<clientRec> getClientServiceInfo(){  
        List<clientRec> clients =  new List<clientRec>();
        List<DS_Background_Family_Info_F__c> backgroundInfo = [SELECT Client__r.id, 
                                                                Baseline_ID__r.BDOV__c, 
                                                                Client__r.CURRENT_AGE__c, 
                                                                Baseline_ID__r.BIDENT__c, 
                                                                Baseline_ID__r.ETHNIC__c, 
                                                                Baseline_ID__r.RAKNTV__c, Baseline_ID__r.RASIANIN__c , Baseline_ID__r.RBLACK__c, Baseline_ID__r.RCHINESE__c , Baseline_ID__r.RFILIPINO__c, Baseline_ID__r.RGUAM__c, Baseline_ID__r.RHAWAN__c, Baseline_ID__r.RINDIAN__c, Baseline_ID__r.RJAPANESE__c, Baseline_ID__r.RKOREAN__c, Baseline_ID__r.ROASIAN__c, Baseline_ID__r.ROPI__c, Baseline_ID__r.RREF__c, Baseline_ID__r.RSAMOA__c, Baseline_ID__r.RUNK__c, Baseline_ID__r.RVIETNAMESE__c, Baseline_ID__r.RWHITE__c, 
                                                                Baseline_ID__r.BMILFAMILY__c, Baseline_ID__r.BMILSERV__c, FMSTAT__c, 
                                                                FDOV__c, FETSTAT__c, FUTYPE__c
                                                                FROM DS_Background_Family_Info_F__c
                                                                WHERE FDOV__c >: StartDate];
                                                                
        for(DS_Background_Family_Info_F__c b : backgroundInfo){
            clientRec client = new clientRec();
            client.clientId = b.Client__c;
            client.bdov = b.Baseline_ID__r.BDOV__c;
            client.CurrentAge = Integer.valueOf(b.Client__r.CURRENT_AGE__c);
          //  client.gender = b.get(Baseline_ID__r.BIDENT__c);
                
                //genderParsing
                if(b.Baseline_ID__r.BIDENT__c == null){
                    client.gender='Missing';
                }
                else{
                    Integer genId = Integer.valueOf(b.Baseline_ID__r.BIDENT__c);
                    
                    if(genId == 1){
                        client.gender= 'Male';
                    }
                    else if(genId == 2){
                        client.gender = 'Female';
                    }
                    else if((genId == 3) || (genId == 4)){
                        client.gender='Transgender';
                    }
                    else if(genId == 98){
                        client.gender='Other';
                    }
                    else if((genId == 96) || (genId == 99)){
                        client.gender='Refused';
                    }
                }
            //client.ethnic = b.get(Baseline_ID__r.ETHNIC__c);
            
           /* client.race = b.get();
            client.militar = b.get();
            client.txstatus = b.get();
            client.fdov = b.get();*/
            clients.add(client);
        }
                                                              
        System.debug(clients);
        return clients;
    }
        
        //demographics
            //total # ever? or total w/ bdov w/i timeframe?
            
        //military
            //background b, background f 
                //where bmilfamily =1 ||2 ||bmilself ==1 ||fmstat==1
            
        //services
            //new clients
                //# w/ bdov w/i range
                //background family info b where client in clients && date in range
                
            //with services
                //(total clients with ageEntered 0-21) - (background f where futype==2 && fdov < startdate)
                //is same as: background f where futype ==2 && fdov >= startdate?
                    //what about enddate?
                    
            //with assessments
                //clients with a date w/i range
                    //any date
                        //background b, f, cbcl b, f, ptsd b, f, psi b, f, tecc/yc b, f, (sdq?)
            
            //ended treatment
                //clients who ended treatment w/i range
                    //background f w/ fdov w/i range && futype ==2 (ageEntered or current?)
            //as planned
                //&&fetstat ==1
    //}
    
}