Kelsey Development Sandbox/src/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/Client_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DS DATA Page</label>
        <referenceTo>DS_DATA__c</referenceTo>
        <relationshipLabel>Client Summary</relationshipLabel>
        <relationshipName>Client_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Summary</label>
    <nameField>
        <displayFormat>summary-{000000}</displayFormat>
        <label>Client Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_DATA__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data_Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variable__c</fullName>
        <label>Variable</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DS DATA</label>
    <nameField>
        <label>DS DATA ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DS DATA</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/objects/DS_TRDETAIL2__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipName>DS_Trauma2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DS TRDETAIL2</label>
    <nameField>
        <displayFormat>TRDETAIL2-{000000}</displayFormat>
        <label>DS TRDETAIL2 ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DS TRDETAIL2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Kelsey Development Sandbox/src/classes/TestClass_DS_TDETAIL.cls
/****
*@description This test provides code coverage for Trauma Details
*includes: DS_TRDETAIL1_Trigger, DS_TRDETAIL2_Trigger, DS_TDETAIL_Controller, DS_TDETAIL_Factory,
*DS_TDETAIL_Interface, DS_TDETAIL_Element_Base
*
*@group Test Script 
*@group-content /ApexDocContent/Test/DS_TDETAIL.htm
*
*@author Kelsey Willett
*@date 11/18/2015
*
*@modified DF Update for the new library and add new test method for Test_DS_TDETAIL_Factory
****/

@isTest (SeeAllData=false)
private class TestClass_DS_TDETAIL {
    
    /****
    *@description Initialize reference to TestClass_A_Utility
    ****/
    public static TestClass_A_Utility test_ut = new TestClass_A_Utility();
    
    /****
    *@description Initialize reference to Utility
    ****/
    public static Utility ut = new Utility();
    
    /****
    *@description Load required data from TestClassData
    ****/
    @testSetup 
    static void setup() {
        TestClassData_DS_DATA importData = new TestClassData_DS_DATA();      
        importData.trauma();
    }
    
    /****
    *@description method to test a bulk creation of object
    ****/
    static TestMethod void BulkTraumaDetail() {
        
        Client__c client = test_ut.createClientGTRAUMA();
        
        List<DS_DATA__c> forms = [SELECT Page__c, Weight__c, Object__c
                                  FROM DS_Data__c
                                  WHERE Category__c = 'TD'
                                  AND Data_Type__c = 'DS_Form_Info'
                                  AND weight__c = 1];
        
        SObject TDObject;
        
        List<Sobject> insertObj = new List<Sobject>();
        
        for(DS_Data__c info : forms) {
            
            Schema.SObjectType TDObjectType = Schema.getGlobalDescribe().get(info.Object__c+'__c');
            
            for(Integer i = 0; i < 200; i++) {
                
                TDObject = TDObjectType.newSObject();
                
                TDObject.put('client__c', client.id);
                TDObject.put('T'+info.Weight__c+'RRODT__c', date.today());
                
                //insert TDObject;
                insertObj.add(TDObject);
                
            }            
        }        
        insert insertObj;        
    }
    
    /****
    *@description method to test controller
    ****/
    static TestMethod void Test_DS_TDETAIL_Controller() {
                
        Client__c client = test_ut.createClientGTRAUMA();
        
        Client_Summary__c summary = [SELECT id 
                                     FROM Client_Summary__c
                                     WHERE Page__r.Variable__c = 'GT8R'
                                     AND Client__c = : client.id];    
        
        String cimi = ut.urlEncode('c='+client.id+'&TDF=TRDOMVIO'+'&summary='+summary.id);
        
        ApexPages.currentPage().getParameters().put('cimi', cimi);
        
        // TRDOMVIO  
        DS_TDETAIL_Controller controller = new DS_TDETAIL_Controller();
        
        controller.getContent();        
        
        DS_TRDETAIL2__c commvio = new DS_TRDETAIL2__c();
        
        ApexPages.currentPage().getParameters().put('cimi', cimi);
        
        controller = new DS_TDETAIL_Controller();
        
        controller.getContent();
        
        Component.Apex.pageBlock block = new Component.Apex.pageBlock();
		
        // Get all the question types and put them into element ganerator
        for (Sobject d :[SELECT CATEGORY__C, COUNT(Id) FROM DS_DATA__c WHERE DATA_TYPE__C = 'DS_TD_Form_Info' AND CATEGORY__C != 'INSTRUCTION'
GROUP BY CATEGORY__C]) {
            controller.elementGenerator(block, (String) d.get('CATEGORY__C'), '1', 'test');
        }
        
        controller.save();
        controller.cancel();
        
        DS_TRDETAIL2__c tr = new DS_TRDETAIL2__c(client__c = client.id);
        insert tr;
        
        // Update record
        commvio = [SELECT id FROM DS_TRDETAIL2__c WHERE client__c =: client.id];
        
        controller = new DS_TDETAIL_Controller();
        
        ApexPages.currentPage().getParameters().put('cimi', cimi);
        
        controller.save();
        
    }
    
    /****
    *@description method to test DS_TDETAIL_Factory
    ****/
    static TestMethod void Test_DS_TDETAIL_Factory() { 
        
        String elementClassNameNotExist = 'DS_TDETAIL_Element_Not_Exist';
        
        DS_TDETAIL_Interface.Element elementInstanceNotExist = DS_TDETAIL_Factory.getInstance(elementClassNameNotExist);
        
        System.assertEquals(elementInstanceNotExist,null,'Instance should be null.');

        
        String elementClassNameExist = 'DS_TDETAIL_Element_Base';
        
        DS_TDETAIL_Interface.Element elementInstanceExist = DS_TDETAIL_Factory.getInstance(elementClassNameExist);
        
        System.assertNotEquals(elementInstanceExist,null,'Instance should not be null.');
        
    }
        
}